### ISSUE TITLE
Custom notification sound

### ISSUE THREAD

**Issue by tomlowenthal** [signalapp/Signal-iOS#1009]
When Signal notifies me of a new message, it plays a sound. I would like it to play a different sound. I can't find a knob or switch for this in the app.

**Comment by FredericJacobs** [comment]
Different sound? like what?

**Comment by flamsmark** [comment]
Yes, I mean that I'd like to pick the message alert tone and the ringtone.

**Comment by FredericJacobs** [comment]
We've been working with some sound designers. Including from CitizenFour to get some new ringtones. It's work in progress.

**Comment by flamsmark** [comment]
That's a fine endeavor, but that's not what I'm asking about in this issue — I'd like to pick from the ring/notification tones *already* on the device. I have no objection to shipping with neat custom sounds; that seems like a lovely ideas. However, all I want is to be able to change the notification and ring sounds.

**Comment by FredericJacobs** [comment]
The ringtones that are on device have no public API to access them.

I know how to play them using AudioServices but there's a risk for Apple to reject the application since the enum containing the values isn't public.

I know a few apps who did it and got away with it it so we might give it a shot.

**Comment by caveman1973** [comment]
Even better would an option to choose a different sound for each contact. It is nice to know who is texting you without having to look at your phone.

**Comment by boompig** [comment]
I have a PR for this. Will be coming in in next few days, just want to test to make sure it works on a real iPhone, not just on emulator. :)

**Comment by mrusme** [comment]
I'd find it really cool if I could simply pick a default iOS tune, so it won't differ from my iMessage tune. :-)

**Comment by ehalsey** [comment]
I would prefer if it could be unique so I know that it isn't another message type and would be even cooler if you could configure different sounds/vibration patterns based on keywords.

**Comment by mkb** [comment]
Yes, I'd love to be able to choose from the sounds I have installed on my phone.

**Comment by hnds** [comment]
Any update changing the default sound?

**Comment by riyapenn** [comment]
Please refrain from "asking for updates" or stating any version of "I agree" "+1" without providing any NEW or additional information like design prototypes or actionable items. Otherwise you are creating noise which takes time away from fixing bugs and actual development of this or other features. 

If you really want, there's the emoji option to the top right of the comment header to "add your reaction" or choose to subscribe to notifications as an option in the right side of the webpage (when viewed in most browsers). Another option is to check out the "What's New" section in the iTunes store when updating the app.

**Comment by jeffmcneill** [comment]
A choice of sounds for the global alert sound seems to be the simplest way of improving the sound situation. That would mean a menu item in preferences and more sounds to select between. Though a "better" sound to replace the current sound is also an option, as in https://github.com/WhisperSystems/Signal-iOS/issues/1094.

My question is, as an unassigned item, is the detail of the feature request being discussed elsewhere?

**Comment by smconner** [comment]
I would really love to have some control over the default sound assignments. What I'm realizing I would love even more than that as a developer (and as a commenter on someone else's project) is a way to register and measure interest without clogging up the threads with annoying "me too" comments like I'm doing now. How about it GitHub?

**Comment by josharian** [comment]
+1. Extra context, in case this is a use case that hasn't been considered much: My father-in-law does not hear the current sound. It is short, low-pitched, and unobtrusive. He has set his phone up to use a somewhat obnoxious, long tone for Messages in order to ensure that he notices them. I'd like to be able to help him do the same for Signal. Custom tones would work, but so would a small default set as long as it includes a tone that is designed for audibility for older ears.

**Comment by richardsj** [comment]
Surely it can't be that hard to offer four sounds: one should be an innocuous 'pop' sound.  The default 'clink-clonk' is horrible and people actually ask "what is that horrible noise?".  So the whole phone has to be on silent when receiving messages.

**Comment by richardsj** [comment]
any sound would be nicer than the current one. There is a pretty nice list here https://notificationsounds.com/notification-sounds - and some of these could be shortened so that the effect is shorter and more subtle. A few loud ones in there and a menu - job done! @FredericJacobs

**Comment by jeffmcneill** [comment]
@smconner The emoji reaction option for the initial issue submission is one way of registering interest without a comment.

**Comment by mattimac** [comment]
+1 for this, any updates on this issue? cant set custom notification sound right now.

**Comment by ikzelf** [comment]
We  use Telegram for standby alerting. So we would be very  happy with a longer/louder sound that is powerful enough to actually  make ppl wakeup.  Current sounds are to subtle and too short for this, for some. Maybe it would help to make sounds repeat a few times?

**Comment by lostence** [comment]
We can already chose between a bunch of sounds per conversation, but allowing a custom sound would be the real definitive answer to this problem.

Thanks for this great app

**Comment by michaelkirk-signal** [comment]
We introduced the option to pick between a range of notifications a while back. 

We don't currently support having custom ring-tones. If you'd like to discuss new features, please do so at the community forum: https://community.signalusers.org
