### ISSUE TITLE
Tutorial should be provided on first startup.

### ISSUE THREAD

**Issue by nanotechz9l** [signalapp/Signal-iOS#1017]
Quick tutorial should be provided when the user first starts up the app. It should also be availble in the settings/help section afterwards.

A user should not have to go to an external support site to learn how to use the app nor its basic functions.

**Comment by mmcco** [comment]
I think the whole idea of the minimalist design is that no tutorial is needed. It's all very intuitive. Maybe something optional and tucked away could be added, but I think a big pop-up on first use would be invasive and kitschy.

**Comment by FredericJacobs** [comment]
I don't think we need a tutorial but an onboarding would be nice. The onboarding would be part of the setup flow and mostly explain why we need the Microphone, Contacts and Notification permission.

**Comment by nanotechz9l** [comment]
Sounds good.

**Comment by Calefornia** [comment]
Didn't want to open a new issue, but this is probably the most relevant one to add a new problem. When you first open Snapchat, you can't use the app without allowing  access to the camera. We shouldn't take that hard stance with Signal, but the problem is that if you receive a phone call before ever using your microphone, you won't be able to talk to your friend.

We need to prompt for microphone access  before allowing somebody to answer a ringing call. Yesterday my friend called me, and I could hear her, but I could not speak to her. I had to hang up and call her again after and allowing microphone access.

on.CallReceived(microphone.permission.status)
    if microphone.permission = false
    prompt("Please allow microphone access")

**Comment by michaelkirk** [comment]
@Calefornia - that sounds like a bug. Can you open a new issue and include a debug log?
