### ISSUE TITLE
Support current iPad resolutions

### ISSUE THREAD

**Issue by themightyoarfish** [signalapp/Signal-iOS#1068]
I am on iOS 9 on an iPad Air 2. The version from the app store looks like this
![image](https://cloud.githubusercontent.com/assets/11613312/12873510/048806a8-cdbf-11e5-9279-10b733732c8c.png)
Which is not very useful. One can expand the view but then all is blurry.

**Comment by FaraoneLele** [comment]
news?

**Comment by EricTousignant** [comment]
I'm not familiar with iOS development, but how hard would it be to create an iPad version that could be exactly the same experience as iPhone (for now), but at least is made for larger interface with the standard iPad keyboard?

Thanks.

**Comment by Dschee** [comment]
@EricTousignant Not so hard. Looking at the benefit earned in the few days it takes to support iPad screen sizes, it really is weird that it was not yet tackled by now. But I'm not sure how many people (or any at all) are working on the Signal app full-time and paid, so maybe that's why?

I could tackle the iPad support myself, but the more imminent problem currently is that the iPad app is configured as a 'master' and can't be used as a 'slave' which means basically, that when you sign into your iPad you'll be signed out of your phone. At least that's what I read on the forums. And fixing that probably includes the backend project, too.

**Comment by ethylmorphine** [comment]
I think, it boils down to the fact that iPad can’t receive SMS. The same reason WhatsApp is not available for iPads. But in contrast with WhatsApp, one can actually connect several devices to Signal account, so... Who knows?

**Comment by Cerberus0** [comment]
This is now being tested in beta:

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-3-0-release/10130
