### ISSUE TITLE
Call Error message text should adapt size to fit localized texts

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1164]
### Bug description

Some of our screens do not fit their translations, resulting in truncation.

**Actual result:** Text is truncated
**Expected result:** Text should be resized, or (as in this case) line wrapped when appropriate.
### Screenshots

![image](https://cloud.githubusercontent.com/assets/217057/14839237/133f339e-0bde-11e6-9aa8-6fecc4567a96.png)

**Comment by big-r81** [comment]
We can set the numberOfLines property from teh callStatusLabel to 0 to use as many lines as needed, or should we set it to (for example) 2 or 3 lines to avoid a filling of the hole screen for long messages?

**Comment by michaelkirk** [comment]
related to https://github.com/WhisperSystems/Signal-iOS/issues/975

**Comment by michaelkirk** [comment]
Three lines should be good.

**Comment by big-r81** [comment]
@michaelkirk 
I have tested a 3 lines label...
<img width="375" alt="longer label" src="https://cloud.githubusercontent.com/assets/9985963/14885657/de1e77cc-0d4c-11e6-840e-7b99bb8b49ac.png">

But there is a vertical spacing before and after the callStatusLabel text (callin label), after resizing the
Conversation contact view. it seems not correct for me, if we only have a one line short text at the label...
![longer label - storyboard](https://cloud.githubusercontent.com/assets/9985963/14885840/089864e4-0d4e-11e6-8459-f957ff1b5f8e.png)

Example for a for a short text on the label...
<img width="375" alt="longer label - call" src="https://cloud.githubusercontent.com/assets/9985963/14886012/cbca9f68-0d4e-11e6-95b1-2643ad31d097.png">

So what to do?

**Comment by big-r81** [comment]
Okay, i updated the constraints, so no resizing of the label required...

I set the word line breaking in the code with
`_callStatusLabel.lineBreakMode = NSLineBreakByWordWrapping | NSLineBreakByTruncatingTail;`
because i don't know how i can set two line breaking modes in the interface builder of xcode.

On iPhone 6:
<img width="375" alt="longer label - call fixed constraints" src="https://cloud.githubusercontent.com/assets/9985963/14889695/21d8da6c-0d60-11e6-92e9-c025016970bd.png">

On iPhone 4s:
<img width="320" alt="longer label - call fixed constraints 4s" src="https://cloud.githubusercontent.com/assets/9985963/14889746/51d0dddc-0d60-11e6-8634-e687567c1df1.png">

So if all is fine, i would prepare a PR.

**Comment by big-r81** [comment]
@michaelkirk If all is fine, i would prepare a PR!

**Comment by michaelkirk** [comment]
Go ahead and make a PR (no need for permission :wink:) and we can have any code related discussion there.

**Comment by Enselic** [comment]
## Summary

This issue can be closed, because the screen the bug report is about was removed in 9db33a9651c75067a9de872f2867a175ac8e6552.

## Details

Proof:
1. The string `Nummer ikke registrert hos Si` from the screenshot was only ever a translation of `END_CALL_NO_SUCH_USER`. You can confirm with `git log -S'Nummer ikke registrert hos Si'`. *
2. The usage of the string key `END_CALL_NO_SUCH_USER` was removed in [the above mentioned commit](https://github.com/signalapp/Signal-iOS/commit/9db33a9651c75067a9de872f2867a175ac8e6552) and has not been reintroduced. You can confirm with `git log -SEND_CALL_NO_SUCH_USER` (but don't get confused by commits that merely removes the obsolete translation of that key).

\* To be entirely sure you'd have to also go back even further when the string was encoded with UTF-16, but it's a bit of a pain to do since e.g. `git grep`, `git log` and friends do not work well with UTF-16. I did it myself just to be sure though.

## Why do I bother with this old issue?

I am looking for issues to fix, and I prefer to start looking into the oldest ones. I was going to fix this issue, but upon investigation noted that this can not be fixed since the entire screen was removed more than 4 years ago.

## But what about the new call screen?

I haven't investigated the new call screen, because this issue is not about the new call screen.
