### ISSUE TITLE
Edit contact's details from within contact's settings

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1481]
In a conversation, tapping on the contacts name, takes you to the conversation settings.

**new feature** 

From there, if it's a contact thread (as opposed to a group thread) you should see an edit button (right bar button) that allows you to edit the contacts name and avatar.

This should work to edit existing contact's details and to create new entries in the user's contacts if they are messaged by an unknown contact.

See https://developer.apple.com/reference/contactsui/cncontactviewcontroller for more.

As Contacts framework is iOS9+ only, this feature will not work for our iOS8 users - the controls should be hidden in that case.

**Comment by roostr** [comment]
Related to #898

**Comment by roostr** [comment]
If we only want to support adding a new contact for a phone number that is not currently associated with a contact, this would be somewhat straightforward.

If this should include editing of contacts, I recommend the best course of action is to refactor OWSContactsManager to pull from the new Contacts API instead of the deprecated ABAddressBook API. Here's why:

1. The [CNContactViewController](https://developer.apple.com/reference/contactsui/cncontactviewcontroller) API expects a CNContact fetched from the [Contacts](https://developer.apple.com/reference/contacts) framework to be passed in.
2. We're currently keying our Contact model objects using the ABRecordID field that we get from the ABAddressBook API.
3. There's no way to fetch a contact from the Contact Framework based on the ABRecordID field. The best you can do is do a name and phone number match to find overlapping records.
4. Because of [Unified Contacts](https://discussions.apple.com/thread/4516512?tstart=0), the ABAddressBook will sometimes return multiple contacts that have the same names and phone numbers (the different records would represent cards on different contact services, but would look very similar).
5. Thus it would be impossible to deterministically match an ABAddressBook record to a Contact Framework record.
6. Thus there is a chance that you could be editing the name of a contact using the CNContactViewController API, but you're not modifying the record that Signal uses, so when you swipe back to return to Signal, the changes would not be picked up.

Here's what the refactor would entail and accomplish:

1. Signal's OWSContactsManager fetches from Contacts Framework API on iOS 9+, while still fetching from ABAddressBook on iOS 8.
2. A new string field is added to Contact to represent the new style of contact identifier in iOS 9+ (They use a GUID string now)
3. All references to the `ABRecordID recordID` field of the Contact model object in the code (there aren't many) are updated to conditionally use a new string identifier instead, or alternatively and more cleanly, the `ABRecordID recordID` field is changed to be an NSString (@"%d", recordID) so both iOS 8 and iOS 9 are using a string key.

Once this change is in place, we would be able to display the CNContactViewController with the assurance that we're modifying the contact that we're monitoring.

**Comment by michaelkirk** [comment]
@roostr, sorry to let this sit. 

Thanks for your thoughts. I think your approach sounds reasonable. 

> All references to the ABRecordID recordID field of the Contact model object in the code (there aren't many) are updated to conditionally use a new string identifier instead, or alternatively and more cleanly, the ABRecordID recordID field is changed to be an NSString (@"%d", recordID) so both iOS 8 and iOS 9 are using a string key.

I think I came to a similar conclusion with some recent work related to the new invite flow, and in fact Contact.m now has a uniqueId field which is set to `return [NSString stringWithFormat:@"ABRecordId:%d", recordId]` for AB Contacts and just `CNContact#identifier` for CNContacts.

**Comment by roostr** [comment]
No problem!

I saw the work you did in the invite flow, and that @"ABRecordId:%d" approach looks good to me. I would recommend that be extended out so this string field is the defacto identifier as part of this work, eliminating the current ABRecordID based identifier.

If you'd like to minimize change impact to SignalServiceKit users who are still relying on the ABRecordID identifier, we could use an auto-incremented private global int of our own to distinguish the different records, and still move away from the old APIs on iOS 9+ devices. This will screw things up for SSK users who were counting on those IDs remaining stable between launches of their app, but Apple's documentation already says that [there's no guarantee that ABRecordID will be stable](https://stackoverflow.com/questions/16922150/is-abrecordid-a-reliable-way-to-identify-unique-contacts/16926742#16926742).

Either way, it wouldn't be hard to shift identifiers from the ints to strings, because the identifier is only used in a handful of places currently.

The refactoring aspect would be best done when conflicting work isn't in flight (such as the current invite improvements) so we get a clean merge. I'll leave it up to you to indicate when a good time would be. Feel free to reach out to me in email or here if you think the timing would be good to work on this refactor. I'm not sure what my availability will look like, but I can at least update you at that time.

**Comment by michaelkirk** [comment]
> I would recommend that be extended out so this string field is the defacto identifier as part of this work, eliminating the current ABRecordID based identifier.

This sounds good. There may also be some name formatting or sorting logic outside of this class that would best be pulled in.

> If you'd like to minimize change impact to SignalServiceKit users who are still relying on the ABRecordID identifier, we could use an auto-incremented private global int of our own to distinguish the different records, and still move away from the old APIs on iOS 9+ devices. This will screw things up for SSK users who were counting on those IDs remaining stable between launches of their app, but Apple's documentation already says that there's no guarantee that ABRecordID will be stable.

I think it's OK for the `recordId` (ABRecordID) to be null on ios<9, as long as there is some documentation.

```
// This will be null on iOS9+, where we prefer to use the Contacts framework
@property (nullable, readonly, nonatomic) ABRecordID recordID;

// This will be null on iOS8, where we use the ABRecordID
@property (nullable, nonatomic, readonly) CNContact *cnContact;
```

And as an identifier of uniqueness, the new `uniqueId` field will be exactly as stable as the ABRecordID was (since it's just `stringConstant  + ABRecordID`).

> The refactoring aspect would be best done when conflicting work isn't in flight (such as the current invite improvements) so we get a clean merge. I'll leave it up to you to indicate when a good time would be. Feel free to reach out to me in email or here if you think the timing would be good to work on this refactor. I'm not sure what my availability will look like, but I can at least update you at that time.

Now is a good time actually - no changes planned for the ContactManager or Contact in the next couple weeks, except maybe adding some new fields unrelated to the contact frameworks.

**Comment by roostr** [comment]
Thanks for the clarification, agreed on all points.

Personally, I can't commit to this right now. If my availability changes, I'll check back in to see if it's still a good time. If someone else jumps on it, please note it to avoid duplicated effort.

**Comment by michaelkirk** [comment]
FYI, I'm doing some work on the contacts code at the moment, so hold off on grabbing this for now.

**Comment by denver-s** [comment]
This feature exists now, should we close this issue?
