### ISSUE TITLE
Option to open links by default with googlechrome

### ISSUE THREAD

**Issue by illicitonion** [signalapp/Signal-iOS#1514]
I use Google Chrome as my default browser on iOS. Currently when I tap links they open in Safari, and there's no way to change this default.

I propose (and am happy to give a go at implementing, if it would be accepted) a new setting on the settings screen, which would only appear if Chrome is detected to be installed, which allows you to toggle whether Chrome should be the default link handler.

**Comment by kunickiaj** [comment]
+1 for this. Would be nice to also add Brave (https://brave.com/) as a browser option.

**Comment by kunickiaj** [comment]
Thought I'd take a stab at this one, but I'm somewhat new to iOS.

It looks like the UITextView that displays the message uses data detectors to automatically create links. In order to open them in Chrome, they need to be rewritten with a googlechrome/googlechromes URI (ref: https://github.com/GoogleChrome/OpenInChrome).

Figure this should be fairly simple to add, but I'm not familiar enough with the codebase to understand where you can hook it in. TextViewDelegate may work, but not sure how to instantiate / assign it to newly created cells.

Any tips on how to implement this are welcome.

**Comment by kunickiaj** [comment]
Working on a patch for this.

**Comment by inoas** [comment]
Ref https://github.com/signalapp/Signal-iOS/issues/4243

**Comment by inoas** [comment]
@kunickiaj it is not even a Signal bug as iOS lets you disable Safari and then links just dont work as there is no valid handler... other apps work fine just in Signal links dont.
