### ISSUE TITLE
Feature Request: Option to auto-save received images/video to camera roll

### ISSUE THREAD

**Issue by eharris** [signalapp/Signal-iOS#1567]
Nearly all other chat apps allow some form of auto-save to camera roll/image gallery of received images and videos.  Matching this functionality in Signal would be great option, preferably on a per-conversation/per-contact basis.

**Comment by GPMueller** [comment]
I absolutely agree that this should be available, but I suggest that in contrast to other apps, this should be **opt-in** (i.e. *off* by default).

**Comment by NiklasBr** [comment]
I also wish Signal could auto-save my sms history, (only to the encrypted iTunes backup if possible).

**Comment by p0ll3** [comment]
That feature is essential, at least if you try to get whatsapp users to join signal. Most of my Friends beef about that.

**Comment by NiklasBr** [comment]
@p0ll3 please add your voice to #2542

**Comment by Berghopper** [comment]
I also agree that this should be an option (maybe also make it configurable during first use?).
Especially in the case where, let's say your screen is broken, recovery of media can be much more difficult.

**Comment by Meteor0id** [comment]
automated saving to camera roll would go against the idea that users should never be given an option to compromise their own security without continuous consent for every time such compromise is made.
I my view Signal is setting an example for real secure messaging. Giving people the option to export images outside the encrypted app is fine, but doing it on every image without keeping the user aware is bad security practice and that options shouldn't be offered to the user because the app should alos keep the user safe from his own mistakes.

**Comment by GPMueller** [comment]
Then how about some sort of button, which would appear below each received image (or set of images)? It would make exporting much easier compared to now, as one would not have to navigate any menus. It could in principle also indicate if an export has previously taken place.

**Comment by Meteor0id** [comment]
I have no opinion about how it should look and where such button would be shown, but what you propose does resolve the privacy concern of decrypting without keeping the user aware.

Seeing the image or group of images before you activly decide if you want to save them to the camera roll  is the way to go.

**Comment by Berghopper** [comment]
@GPMueller @Meteor0id 
Why not a global option that is off by default? Make it per chat (type) too. I do agree automatically saving to camera roll could potentially be a privacy risk, but a lot of people are just used to the idea of having it there, which would make transition into Signal easier. 

I think it should be selectable at setup time of the app as well, to highlight this option is off by default.

**Comment by eharris** [comment]
I agree this option should be off by default, buy I cannot comprehend why some people think it is right to not even *allow* people to enable this if they want.  It seems to me to be the height of arrogance to think *your* security preferences should be the *only* way that is allowed.  If you don't want to do it, don't enable it, but don't disallow me from doing what I wish with my own device and my own media.

I am using Signal only for private communication, not for private storage.  I do not believe that media sent to me is any more secure just because it's supposedly only accessible inside an app rather than in my camera roll, it is just a lot more inconvenient (and uselessly so) for me to use that content how I want without any security gain.   Once media is sent to me, I should have the right to do with it what I want without having to jump through manual hoops every time.

**Comment by Meteor0id** [comment]
What the original post suggested was a single switch to send all inconing messages to the canera roll without further user actions. This shouldn't be allowed because it compronises security of the user, and it does so without confronting him about it.

When media are send to you in Signal, they are stored on your device as encrypted data. Even if some law enforcement (say the Chinese customs when you enter their country) were to look into your device, if they can't unlock Signal they can't see those media. If a mallicious app is installed on your phone which scans or uploads some of your media, it can't do that to media you receive on Signal because those are encrypted. An encrypted Signal media item can be deleted permanently eithout fear that it still lingers on your storage and a forenstic tool could recover it.

Signal should offer a button to export media, but that should remain a contious action of the user on a per item or per group of sekected items. By limiting this functionality to a manual action, the user is forced to consider the security risk, and to stay aware of the existance of some risks.

You not believing that your media are more secure if bot exported is just an example of how humans are not good at assesing risk ahead of time. The decision to export media should be taken when you know what this media is, not ahead of time.

Is it arrogant of anyone to not always permit you to do what you want with Signal? I don't think so. Signal is an app about secure and private messaging. Its scope is limited to secure messaging. If you want to opt for insecure, than you do have that freedom, by choosing another app.

I am not member of Signals developing team, I'm just another user, so maybe you'll get lucky and they agree with you. But my opinion is that security by design can sometimes also require that the user can't shoot himself in the foot even if he would like to.

**Comment by ksnell88** [comment]
Opt-in autosave makes perfect sense (with the ability to tweak chat-by-chat) so the default is more privacy yet a useful feature can be added.

The concerns about "shooting yourself in the foot" are unwarranted IMHO considering you can already toggle on "Show Calls in Recents" in the iOS Phone app under the Privacy settings. Signal already interfaces with the Phone app so what is the difference with the Photos app?

**Comment by z4ndr3i** [comment]
Similar to WhatsApp, there should be an option within each 1:1 or group chat to automatically save received media to the camera roll. I'm not of the opinion that it should be a global switch (like in WhatsApp), but it should be available to be turned ON/OFF on a convo-by-convo basis. 

One size does not fit all & I cannot wait to get rid of WhatsApp, but I'm not going to manually save or export each [insert-your-harmless-type] picture I get from fam & friends.

**Comment by onnokleen** [comment]
I agree - I am not taking many photos myself and rely on my friends :) An opt-in per conversation would be great (for example that with my wife).

**Comment by norcon** [comment]
Please add this feature. That would be great

**Comment by themartorana** [comment]
Trying to move my family to Signal away from WhatsApp and Facebook, and this is the single complaint I've gotten from everyone. Opt in makes sense. Even a warning or periodic reminder makes sense (Google Photos started doing this with auto-sharing.)

**Comment by PiWakeTV** [comment]
This feature is what I currently miss the most at Signal. Privacy and security first, but the choice and freedom for users second! :)

**Comment by evertvh** [comment]
This issue prevents many of my contacts from using Signal.

**Comment by Meteor0id** [comment]
I personally think that adding a global option to save all incoming media in an unencrypted fashion woukd cause many users to expose their media to other apps on their device, and I think many people do not know or do not believe that there us a real risk that other apps fingerprint or even steal your media, or they don't believe it matters if any app does that.

I think Signal should not offer a global save all media unencrypted option, but should instead start writing articles or videos to explain this thread and make people aware that it really exists and that it's wise to keep media encrypted at all times.

**Comment by NiklasBr** [comment]
All iOS devices are encrypted [since a very long time ago](https://support.apple.com/en-gb/guide/security/sece3bee0835/1/web/1), _including Data Vaults_.

**Comment by eharris** [comment]
Also, what's being asked for isn't a "Global save all media" option.  I, and probably most others, would be fine with a *per contact* or *per group thread* opt-in option.

Part of the problem is the arrogance of the mindset that just because some users' choices aren't *your* choices, that you are somehow justified in refusing to allow them to use software in the way they want, or that they need to be educated/indoctrinated to adopt your mindset.  You are denying users the ability to use Signal's superior "in-transit" security when some people don't want or need super strict (and sometimes very inconvenient) "at-rest" security.

**Comment by onnokleen** [comment]
> Also, what's being asked for isn't a "Global save all media" option. I, and probably most others, would be fine with a _per contact_ or _per group thread_ opt-in option.
> 
> Part of the problem is the arrogance of the mindset that just because some users' choices aren't _your_ choices, that you are somehow justified in refusing to allow them to use software in the way they want, or that they need to be educated/indoctrinated to adopt your mindset. You are denying users the ability to use Signal's superior "in-transit" security when some people don't want or need super strict (and sometimes very inconvenient) "at-rest" security.
> 
> My data is exactly that: **MY** data. I should be able to do with it what I want, including save it automatically/conveniently.

I agree completely. I would be even happier about a **per-chat opt-in** than about a global option.

**Comment by eharris** [comment]
I should also note, that for me (and likely others) **LOSS** of data is a much bigger concern/risk than **BREACH** of data.  Disallowing any form of auto-save practically guarantees that people will forget to save something and thereby lose it, or when something completely innocent (from a security aspect) occurs, like when their phone gets unexpectedly broken and has to be replaced.

**Comment by Meteor0id** [comment]
The problem of an opt-in to autosaving is that you are opting-out of additional security, and you can then forget it for years to come.
You opt-out of encrypted storage in 2021, and in 2026 you have some nalware on your device which fibgerpribts or copies all your media.
Yes you should be allowed to take a risk, but you should be kept aware that you're taking risk.

**Comment by eharris** [comment]
Do you really think someone is going to still be using the same phone 5 years later?  In any case, fine, make the option have to be reconfirmed once a year if you like, as long as the means of re-confirmation makes absolutely CERTAIN that the auto-save opt-in doesn't get accidentally turned off without the user being aware (and thus risking the unrealized loss of their data).

What you call it probably doesn't matter, as long as the functionality is there and what the option does is made clear.

**Comment by evertvh** [comment]
Is there a way we can bring more attention to this issue? Or just wait and see and hope it will be picked up at some point?

**Comment by langbnj** [comment]
Please add this as an opt-in feature, yes!

It's important to me to have photos and videos in one place (namely iCloud) so they will be backed up, rather than being locked inside one of five messaging apps.

**Comment by wali-khan** [comment]
So if am guessing it right... this isn’t considered to get developed cuz of security concern?

**Comment by thisisbhavin** [comment]
I don't understand how is this a security issue if there is a warning when users opt-in. If they consciously choose to save media then they should be allowed to do so. This is the single feature holding me from recommending my friends and family to use this app.

**Comment by thisisbhavin** [comment]
If nothing else then give the user the ability to save multiple media at a time. Currently, you have to save single media at a time, and looking at 50 remaining photos to save, I just give up!!

**Comment by Marco1097** [comment]
> 
> 
> I don't understand how is this a security issue if there is a warning when users opt-in. If they consciously choose to save media then they should be allowed to do so. This is the single feature holding me from recommending my friends and family to use this app.

Also it is possible to save the photo when it is received, so this feature would be just an extra convenience
Opt-in option for every single chat would be great

**Comment by darraghenright** [comment]
At the risk of sounding like a +1 comment, I'd like to lend my support to this feature as well. 

The number of non-tech savvy friends and relatives (including my seventy-something year old aunt) who have contacted me asking about Signal this week has been astonishing — people are really spooked about WhatsApp's upcoming changes and are seriously looking into alternatives.

Making a speculative leap that this is happening elsewhere, this seems like an incredible opportunity for Signal to convert users, and any features that enable familiarity can only help. I very much appreciate that usability and security can be at odds with each other, but an auto-save feature with explicit opt-in seems reasonable to me, if implemented thoughtfully.

When a user is presented with the question, let's assume for argument's sake that the setting is per chat: "do you want to save images sent to this chat? y/N" they are given an ample opportunity to weigh up their own priorities in this matter, and decide accordingly. Especially if they are provided with useful information outlining the implications of their decision if they accept.

**Comment by z4ndr3i** [comment]
Signal's website reads: 

"Say "hello" to a different messaging experience. An unexpected focus on privacy, combined with all of the features you expect."

I expect the feature of saving media automatically, per 1:1 chat or group basis, to the phone's camera roll. Thank you in advance.

**Comment by huian** [comment]
We are in the midst of converting a large amount of friends/family groups (messaging platform across countries we live in), from Whatsapp to Signal. Two issues are preventive and standing in our critical path 1.) Auto-save media (voice, images, videos) - we are fine with an explicit opt-in model. And 2.) Web version of using the Signal platform. We consider 1. as absolute essential, and 2. as a second priority (prefer but can be delayed).
If Signal wants to capture this golden opportunity there is no better time than NOW to get this feature delivered. Once Feb 8 hits, some users may quickly become complacent to Whatsapp's "renewed" privacy policy, and if you can't get the majority switch over the tipping point, you will not see the major adoption. Download is through the roof, but it's a smoke screen for now - it does NOT equate Migration. Most who downloaded Signal are still running Whatsapp - the next month will be the most important decision period.

**Comment by GPMueller** [comment]
It was [recently tweeted](https://twitter.com/signalapp/status/1348785240819466242) that Signal will be rolling out this feature soon 🎉

> Here's a sneak peek at some new Signal features that will start rolling out in a few days:
> • Chat wallpapers!
> • About field for your Signal profile
> • Animated stickers
> • For iOS: Media auto-download settings and full-screen profile photos (to match Android)

At least that's what I'd expect from "media auto-download settings".

**Comment by Marco1097** [comment]
> It was [recently tweeted](https://twitter.com/signalapp/status/1348785240819466242) that Signal will be rolling out this feature soon 🎉
> 
> 
> 
> > Here's a sneak peek at some new Signal features that will start rolling out in a few days:
> 
> > • Chat wallpapers!
> 
> > • About field for your Signal profile
> 
> > • Animated stickers
> 
> > • For iOS: Media auto-download settings and full-screen profile photos (to match Android)
> 
> 
> 
> At least that's what I'd expect from "media auto-download settings".



auto-download for me indicates that it will be possible, once I receive the photo/video, to download it immediately or wait and do it later

auto-save is another thing

**Comment by FinixFighter** [comment]
> > • For iOS: Media auto-download settings and full-screen profile photos (to match Android)

Only for iOS? What about Android? :(

**Comment by manideep444** [comment]
Please add this feature to Android!

**Comment by NiklasBr** [comment]
@FinixFighter, the Android repository is at https://github.com/signalapp/Signal-Android you can ask there. Judging by the _"...(to match Android)_" part of the change log the ability to download images to the chat without having to tap on them should already work on Android

**Comment by whng8** [comment]
> 
> 
> > > • For iOS: Media auto-download settings and full-screen profile photos (to match Android)
> 
> Only for iOS? What about Android? :(

The ability to auto-download media already exists for Android via Settings > Chats and media > Media auto-download. However, this does not save the images to the image gallery.
I suppose now iOS is getting the same feature. That's how I interpret the "to match Android" announcement.

I wish Signal had the ability to automatically save images to the image gallery, like WhatsApp does. I tried to convert some family members from WhatsApp to Signal and each time this issue arose.

**Comment by fre-lax** [comment]
We were planning to install Signal on my grandmother's tablet but it doesn't make any sense if she cannot see the pictures in the camera roll...

**Comment by N-Prime** [comment]
I really hope this is in the works and coming soon. I got my family to migrate from WhatsApp to Signal and one of the main ways we use it is for my sister to send the group photos of her new baby. 

I've already told them that they need to manually save each photo if they want to get copies to their camera roll and to be backed up with their other photos, but I don't know if it's sank in yet. I'm worried they're going to have a rude awakening in a few months when they realize what I've said and find they're going to need to go back and manually save each photo going back those months.

To compensate I will probably save all photos so I can easily transfer copies to them if they start making noise about it (my sister could do it too, but I don't want to put her through more trouble, especially since this is supposed to be a way of easily giving copies of photos to people in the family).

The problem is accessibility - yes, it gets the photos to people, but when they're saved by default in Signal's encrypted storage separate from the camera roll, the photos aren't 100% accessible.

**Comment by fre-lax** [comment]
If Signal cares so much about privacy, just add this function to the feature:
If I send a picture to a person who has turned on auto export I get a message "This person has turned on auto export. That means pictures you send will be saved on their phone outside of Signal and can be accessed by other applications." [Send anyways and don't show this message for this person again], [Send anyways and remind me later], [Don't send the picture/ Cancel]

And mabye there even should be an option [Turn off auto export for this picture]

I think that would solve the security issue.

**Comment by Marco1097** [comment]
> 
> 
> If Signal cares so much about privacy, just add this function to the feature:
> If I send a picture to a person who has turned on auto export I get a message "This person has turned on auto export. That means pictures you send will be saved on their phone outside of Signal and can be accessed by other applications." [Send anyways and don't show this message for this person again], [Send anyways and remind me later], [Don't send the picture/ Cancel]
> 
> And mabye there even should be an option [Turn off auto export for this picture]
> 
> I think that would solve the security issue.

You should then put the protection from screenshots and apply the same procedure for each photo, since at this moment the photos can be manually saved on the device

This would be just an extra inconvenience, Signal must protect the communication between users, but then it's up to users to trust each other

**Comment by fre-lax** [comment]
> > If Signal cares so much about privacy, just add this function to the feature:
> > If I send a picture to a person who has turned on auto export I get a message "This person has turned on auto export. That means pictures you send will be saved on their phone outside of Signal and can be accessed by other applications." [Send anyways and don't show this message for this person again], [Send anyways and remind me later], [Don't send the picture/ Cancel]
> > And mabye there even should be an option [Turn off auto export for this picture]
> > I think that would solve the security issue.
> 
> You should then put the protection from screenshots and apply the same procedure for each photo, since at this moment the photos can be manually saved on the device
> 
> This would be just an extra inconvenience, Signal must protect the communication between users, but then it's up to users to trust each other

If someone wants to save something he:she will anyways, even unnoticed. But I like the idea of being able to turn off auto export for single pictures. It doesn't say it can't be saved but it won't be exported without action.

**Comment by ksnell88** [comment]
Perhaps it would make sense that even after the potential auto-save feature is explicitly enabled on device, anything send while disappearing messages is enabled would not be auto-saved. Best of both worlds.

**Comment by ArnaudLM** [comment]
Hello,

I too need the same feature... :(

In the meantime, here is the "least worst" workaround I found (on Android, to be checked on iOS) : when in a conversation, you go to settings (the 3 dots on the top right), all media (sorry if it is not the proper text since I am using a localized version), you select one then select all media, and download.
I still need to see how it performs over time since I auto backup elsewhere (local NAS) and delete frequently...

**Comment by Madd33n** [comment]
Essential feature - I couldn't believe that this is not possible at the moment. 
Hopefully this will implement asap -- because lazyness always eats data security for breakfast - and a lot of people will keep using other messengers - because ALL of them do it. 

And for the security addicted guys - that isn't a feature - it's just a solution for unsecure OS's like Android. 
In iOS everybody can set an individual option to ANY application on accessing the camera roll.

**Comment by mdeguzis** [comment]
>In iOS everybody can set an individual option to ANY application on accessing the camera roll.

...Android has and has had that ability for ages. Permissions can be always set per app to anything the application is seeking to access, but I digress...

**Comment by Madd33n** [comment]
> .Android has and has had that ability for ages.

Ohh - but then I dont understand the discussion about security concerns and that there is the possibility of unwanted access by other apps.. 

Anyway - hopefully this feature will be realized asap

**Comment by Intelli32** [comment]
Chiming in to add auto save option (opt in). This is currently the only reason why my friends and family won't switch over to the app.

**Comment by marbentz** [comment]
"Chiming in to add auto save option (opt in). This is currently the only reason why my friends and family won't switch over to the app."
same here

**Comment by neiljdick** [comment]
Just to +1 this, I've managed to convince most of my Whatsapp groups to switch over to Signal, but I'm currently getting pushed to switch back to Whatsapp because of this missing feature. My family uses a group to share pictures when we get together, and my dad doesn't like that he has to go through and manually save pictures individually.. With whatsapp, all the pictures of his new grandson just show up on his phone where he expects them to be. 

100% agree it should be opt-in, not apply to disappearing messages, apply to individual chats/groups etc.

**Comment by emgab** [comment]
+1 auto save feature for pictures/videos on IOS

**Comment by gadabout84** [comment]
2016-2021: Please consider this feature. It prevents people from switching over from other messenger and opt-in gives users the control.

As written earlier above: Let users trust other users.
It is not your right to decide that for your users.

**Comment by mheimlich** [comment]
How about an opt-in where images are exported only when you first view them within your chat and after a countdown (like 15 seconds or whatever is feasible) displayed within the chat has timed out. This way you can still cancel the export.

**Comment by marovelo** [comment]
I think that the approach described here is interesting: https://community.signalusers.org/t/automatically-save-attachments-to-device-and-possibly-link-to-them-from-inside-the-app/5147/50?u=marovelo
The sender decides whether the receiver is allowed to autosave the photo unencrypted.

**Comment by eharris** [comment]
> The sender decides whether the receiver is allowed to autosave the photo unencrypted.

Personally, I think the whole snapchat mindset of "disappearing" messages and other restrictions placed on the receiver is the stupidest idea (and promotes an entirely false sense of security) that has come out of technology in recent history.  Not only that, it is reminiscent of DMCA-like stupidity (the seller/sender gets to tell me what I can and can't do with my media) and seems to go against the open-source mindset that I think most people involved in open source think they are furthering.

Does no one remember the "analog hole" discussions of yesteryear?  No matter what technological "restrictions" are in place, there is absolutely nothing that prevents someone from taking a photo of any media or messages with another device before they disappear.  This false sense of security is especially true in open source, since there's nothing to stop someone from forking the code and changing the app they are using so that it doesn't actually perform any of those "disappearing" or other restrictions.  Pretending otherwise just gives users a false sense of security.

Personally, I'm entirely and vehemently against any support of those kinds of restrictions being put into Signal (or other apps).  The only way I'd be willing to tolerate it is if I (as the receiver) can also restrict it so that the people I communicate with can't send me "disappearing" or otherwise rights-encumbered restrictions on what I can do with what I'm sent.  If someone feels that restricting (what they only think I can or can't do with it) is necessary, then they just shouldn't be sending it, full stop.

**Comment by signalapp-libre** [comment]
If someone wants to submit a PR to add auto-save of media to https://github.com/signalapp-libre/Signal-iOS that would be welcomed.

**Comment by berkay-senturk** [comment]
In addition to the **opt-in** tweak for automatically downloading Signal chat media, there must be a way to choose the directory. I would love to be able to save them in my external card, and not in my internal card which is always full.

**Comment by Marco1097** [comment]
> 
> 
> In addition to the **opt-in** tweak for automatically downloading Signal chat media, there must be a way to choose the directory. I would love to be able to save them in my external card, and not in my internal card which is always full.

This is the IOS repository, so this option is not needed here

**Comment by danielavdh** [comment]
yes, please, at LEAST 'select all' feature to download all photos of a chat in one swoop, not picture by picture - am on iOS... but better opt-in auto-save to photo.app

**Comment by hammy1988** [comment]
But with the right time stamp. Every month i save my Pictures, but in my photo-app they aren't in the right order.

**Comment by nitram777** [comment]
+1
I´ve just quit WhatsApp and pulled nearly all of my family and friends to Signal. For me and my wife I use an automated backup of picture and video files to my Synology NAS. This worked fine for all photos shot, all WhatsApp media, etc. But on Signal I have no chance to backup the media?

The only possibility is to download each media file manually? If this is the case, I´m thinking about leaving Signal as manageable media backup functionality is essential to me.

Backup is one layer of security! So please let me do my backup.

**Comment by Arkq** [comment]
Recently I've switched to Signal and one of my contacts is using iOS, and what has struck me was the lack of a convenient way to save images.... All other apps auto-save images to camera app, so for iOS users such functionality is a normal and expected behavior. We might elaborate whether it is safe or not, but if build-in iOS mechanisms are not safe, why there is a Signal iOS app after all if Signal architects are so much security and safety oriented?

Also what bothers me is the lack of any response from Signal developers (or maybe there are some but they are not in the [signallapp](https://github.com/signalapp) organization?). Anyway it is strange, that 4 years long conversations is not worth a single official statement from the Signal authors.

And speaking about security. All this talk about "user might forget about the opt-in and get hacked"... If I was concerned that my recipient might get hacked I would not send a confidential information at the first place. Also, one can make a screenshot or take a photo of a screen with another phone. So, the trustiness in the recipient is essential and any app feature or anti-feature will not change that.

And lastly, as a a cherry on top, does anyone know that there is a desktop Signal app for Linux which is based on Electron framework (sic!)? And, user can connect his iOS app with this Linux app and then miracles happens - all the so called "security" is thrown into the garbage can. This app stores all images in the not encrypted form (that's strike one). And what is worst (from the naive sender point of view), the "one time view" images are also stored not encrypted and are available *BEFORE* viewing them in the desktop app (that's strike two)... And since we are all security-freaks, these images are (for sure safely, because security is all we care about) removed from the disk after they have been viewed. Uff, and now we are all safe, no one will hack us any more.... Very sad story... :/

**Comment by norcon** [comment]
Wake up please

**Comment by langbnj** [comment]
This is the main reason people I know aren’t switching away from WhatsApp. It’s really a missed opportunity if this basic feature isn’t added.

**Comment by Madd33n** [comment]
I`m out and working on to push the people I successfully convinced to use Signal back to WhatsApp. 
Nothing happens here (and similar requests) for months. As I said - lazyness beats security. I dont want to save any fxxxx single image I get... what a stupid idea.

**Comment by oberlon** [comment]
This request is open since 2016! In my personal area I convinced many people to join and use Signal. All of them can handle with Signal but! everyone asks why the pictures and movies were not saved to the camera role of the phone. 
So please don't ignore user experience  and add an opt in option to save this memories. 
Otherwise the people will move...

**Comment by mintsv** [comment]
Please make this option available! 
I would like to be able to decide for myself if I want to use a functionality that lessen the security in the app. 
I switched to Signal for security reasons,  because I want/need that. 
But almost all media files I send or receive in the app are pictures of my grandchildren in a group chat. Why can't I automatically save the media from that explicit chat? How would that threaten the security of the rest of my chats?
Tha sheer number of files being sent every day in that chat makes it really inconvenient having to manually save one media file at a  time!
I can't really see us staying on Signal for long for this reason.

**Comment by akuma91** [comment]
I'd love to have this feature on Signal, so this comment is just another +1

**Comment by rwinjanssen** [comment]
+1 +2 +3 👍 
Please add this (opt-in sounds good), I've just got my family to Signal, but this is really bugging them...

**Comment by Viatorus** [comment]
Any update on this? We really want this.

**Comment by Smileynator** [comment]
Same here, i want this as an opt in, like whatsapp, i like to sync my phones media to my phone and vice versa. Having this feature allows me to sync/filter/backup all media content on my computer in an easy way. Please add it.

**Comment by derasd** [comment]
This feature has been requested 4.5 years ago and it is still missing. It really is an important feature for adoption!

**Comment by kevinmce** [comment]
Please make this feature, same as everyone here. Multiple people in my group a complaining that shared photos are not easily available outside the app.

**Comment by Dahaniel** [comment]
Yes please, add this option (speaking for Android here). My gallery is bein backed up automatically but pics received via Signal are being excluded because this feature is missing.

**Comment by rreinhardd** [comment]
Vote up! Please implement this…

**Comment by norcon** [comment]
+1

**Comment by Helyux** [comment]
+1 from me aswell, how is there no official Statement yet? ping! @alan-signal @scottnonnenberg-signal @Imperiopolis-Signal @jrose-signal

**Comment by norcon** [comment]
Please das this option with global opt in 🙏

**Comment by bskp** [comment]
I finally managed to convince my family to use **Signal** instead of **Whatsapp**. My parents, however, are **about to switch back**: Automatically saving all images to the camera roll is a **must-have for them**. _How else to keep track of all the nephew's and niece's pictures?_
Therefore a +1 from me too. I'd be delighted to see this feature realized!

**Comment by ssprakhar** [comment]
Make it happen

**Comment by WinnetouL** [comment]
I mean technically there is already an option available to do this, which would mean for me there is not really an argument left against it. It really would be a nice feature to have an option to opt in, which would save the images to the gallery automatically. :)
+1

**Comment by akuma91** [comment]
@charlesmchen-signal a lot of requests for this feature here... can we at least get a yes or no? :)

**Comment by norcon** [comment]
Please!

**Comment by hkystar35** [comment]
Echoing pretty much every comment here: This is a huge blocker to getting people to switch to Signal, myself included, because many people are not aware, and maybe unable to mitigate, that media files are not auto saved to the device's camera roll.

You're shooting yourselves in the foot here by not having a basic feature, even if it's opt-in, that would enable a plethora of new users.

**Comment by jakobschumacher** [comment]
Same same. That would be a good option

**Comment by Raphencoder** [comment]
Hi @signalapp-libre @michelle-signal @michaelkirk-signal and other contributors of this awesome project.

This FR has been open for 5 years, can we have an answer about your point of view of this request ?

It's really a wanted feature and it will be appreciate by every user on this thread if we can have an answer about the dev of this kind of request.

Hope to hear from you soon !

**Comment by ophl55** [comment]
The same for me. I'd like to store my pictures automatically and getting them with the right timestamp to use them later on. Opt-In would be great so everyone is free to decide.

**Comment by dazbradbury** [comment]
This is clearly an ideological standpoint - which is fair enough for the application owners to have. 

But just stating like many others, it's also the reason my most important conversations have left the platform and ultimately I may do the same to avoid having multiple messaging applications (pain when switching phones). 

Media is important to people, ensuring it's backed up and easily accessible is also important. Right now signal makes this difficult, and is hostile to users who would like to use a 3rd party media manager. 

If signal is to become more than a secure alternative text-based messaging app and really offer mainstream appeal as the default messaging app then it needs to change on this point. 

Suggestions beyond global setting / per contact settings would be: 

- media prompts to save after viewing
- visible indicator media isn't saved to device (until it is)
- anything to help users actively make the choice that media is safe / needs to be kept private or secure.

Ignoring this issue will make it go away, sadly with a large % of users. The type of users who won't come to GitHub and write up an issue.

**Comment by tk1** [comment]
For a non-technically user it's absolutely essential to have auto-save of images to the camera roll. I know many users who tried Signal but left because of this missing feature and returned to whatsapp.

**Comment by eogut** [comment]
I agree to everybody. It's super frustrating to not have this option. My phone is encrypted, I don't need this extra layer of security. Downside is that if I don't download the pictures, they will be buried somewhere in a chat, making it bothersome to bulk delete pictures that are occupying my phone's storage. Please, introduce this function.

**Comment by kaktusztea** [comment]
Hi,
while devs tracks only bugs on Github and feature requests were moved to the forum, could you move the conversation to there and close this ticket?

You can find the auto-save feature request topic here:
https://community.signalusers.org/t/automatically-save-attachments-to-device-and-possibly-link-to-them-from-inside-the-app/5147

**Comment by eogut** [comment]
@kaktusztea thanks for the info. This ticket is opened by @eharris, so I can't close it.

**Comment by vedal** [comment]
This issue annoyed me today again, so I really hope it won't be dropped.

**Comment by tk1** [comment]
I would highly appreciate this feature. I don’t understand why the developers block it. It is one of the main reasons that deters non-technical  users from switching from WhatsApp to Signal.

**Comment by akuma91** [comment]
Bump!!

**Comment by kaktusztea** [comment]
Please comment feature requests on the forum:
https://community.signalusers.org/t/automatically-save-attachments-to-device-and-possibly-link-to-them-from-inside-the-app/5147

Let this ticket close.

**Comment by vedal** [comment]
@kaktusztea Interesting to write the exact same thing in the suggested community thread and have the comment flagged almost immediately "by the community". Not sure why it would be.

**Comment by vedal** [comment]
@kaktusztea I see.
Is there another way to record support for a feature request than 1) bumping or 2) adding "+1" such as with the emoticons of OP here (> 200 emoticons in favor of the feature). 
Otherwise it seems like, in closing this issue, we would lose this useful user feedback.

**Comment by kaktusztea** [comment]
Well, the standard way for +1 is to add a ❤️ reaction to the first comment in the **forum topic**.
If you have other thoughts, scenarios where it could be useful then comment. Threats like "Me and my friends will uninstall Signal if you don't implement this" are kinda pointless IMHO.

Devs have a backlog and they keep track on feature requests from the forum, but also prioritize or even disagree with some implementations.

**Comment by vedal** [comment]
@kaktusztea Thanks for explanation! I added a heart at the OP and [commented](https://community.signalusers.org/t/automatically-save-attachments-to-device-and-possibly-link-to-them-from-inside-the-app/5147/284?u=vedal) reference link to this issue, as you suggested. I also agree with your humble opinion, and accept the constructive criticism. :)

**Comment by Herohtar** [comment]
Note that there is no need to post links to this issue, as that was already done in the [9th post](https://community.signalusers.org/t/automatically-save-attachments-to-device-and-possibly-link-to-them-from-inside-the-app/5147/9?u=herohtar), and it likely exists in others. Re-posting the link only serves to bump the topic and does not contribute to the topic, which is against the forum guidelines.

**Comment by lkwg82** [comment]
Still!

**Comment by Harmelodic** [comment]
> Is this still relevant? 

Yes. It is a feature that still does not exist, and is still highly desirable - given it is the most 👍 'd issue for this repository.

> If so, what is blocking it? 

Other than the developers prioritising other features, I genuinely have no idea.
If the devs need help working through a design for how this might work, then I'm happy to contribute.

> Is there anything you can do to help move it forward?

Other than attempting to prevent a bot from marking it as stale and continuing to ask the developers to implement the feature, and offer to contribute in some way?...not sure!

**Comment by Cerberus0** [comment]
Please ignore the stale bot, it does not know the difference between bugs and feature requests because [this is no longer the right place to submit or discuss feature requests](https://github.com/signalapp/Signal-iOS/blob/main/CONTRIBUTING.md). As requested by others earlier, please let this GitHub issue be closed and continue this discussion on the community forum:

https://community.signalusers.org/t/automatically-save-attachments-to-device-and-possibly-link-to-them-from-inside-the-app/5147

Thanks!

**Comment by lkwg82** [comment]
Still relevant.

**Comment by Dahaniel** [comment]
Still very relevant. In addition: this is creating issues as the Signal db is accumulating media files, occupying huge amounts of storage on my device. The only practical solution would currently be to delete them all which is not where I want to go.
