### ISSUE TITLE
Generic "New Message" notification despite settings

### ISSUE THREAD

**Issue by poke22** [signalapp/Signal-iOS#1617]
- [x] I have searched open and closed issues for duplicates - probably related to #1554 

----------------------------------------

### Bug description
Receive "New message" alert even when "Show Sender name & message" is selected in settings.

### Steps to reproduce
- Set "Show Sender name & message" in settings
- Lock iPhone/exit Signal
- Receive a notification

**Actual result:** "New Message" Notification
**Expected result:** Notification showing Sender name and message content.

### Device info

**Device**: iPhone 7
**iOS version**: 10.2.1
**Signal version:** 2.16.12

### Debug log
2017/01/18 19:45:09:248  [AppDelegate] applicationWillEnterForeground.
2017/01/18 19:45:09:775  [AppDelegate] applicationDidBecomeActive.
2017/01/18 19:45:11:167  [AppDelegate] applicationWillResignActive.
2017/01/18 19:45:11:172  [TSSocketManager] closeWebSocket.
2017/01/18 19:45:11:824  [AppDelegate] applicationDidEnterBackground.
2017/01/18 19:45:17:623  [AppDelegate] applicationWillEnterForeground.
2017/01/18 19:45:17:636  received: -[PushManager application:didReceiveRemoteNotification:fetchCompletionHandler:]
2017/01/18 19:45:18:062  [AppDelegate] applicationDidBecomeActive.
2017/01/18 19:45:18:518  Got message with verb: PUT and path: /api/v1/message
2017/01/18 19:45:25:775  [AppDelegate] applicationWillResignActive.
2017/01/18 19:45:25:780  [TSSocketManager] closeWebSocket.
2017/01/18 19:45:26:815  [AppDelegate] applicationDidEnterBackground.
2017/01/18 19:45:30:721  [AppDelegate] applicationWillEnterForeground.
2017/01/18 19:45:31:705  [AppDelegate] applicationDidBecomeActive.

**Comment by michaelkirk** [comment]
Is this reproducible 100% of the time someone sends you a messages? Or is it intermittent?

It sounds like you are experiencing an issue related to not receiving voip notifications, which goes something like this:

**What *should* happen:**

Alice sends the message: "Hi Bob"
(Invisibly: Bob's device immediately receives a voip push, pulls the new message from SignalService, decrypts it and displays the content in a local notification)
Bob immediately sees "Alice: Hi Bob" on his lock screen.

**Failure case:**

Alice sends the message: "Hi Bob"
(Invisibly: Something in the above-outlined message fetch process fails)
...30 seconds pass
(Invisibly: Unacknowledged messages cause SignalService to send a fallback, generic push notification after 30 seconds)
Bob sees "New Message" on his lock screen.

**Comment by poke22** [comment]
It is reproducible 99% of the time. The notification "New Message" shows for 'Bob' instantly after the message was sent from 'Alice', so there is no 30 seconds pass.

What **did** show a full message on lock sreen:
-Go to settings, change notification type to something else, change it back to "Show Sender name & message"
-Lock iPhone, have 'Alice' immediately message 'Bob'
-'Bob' will see the message on lock screen, however, only for the first message, any subsequent displays "New Message" for 'Bob;

**Comment by michaelkirk** [comment]
@poke22 - interesting, sounds like a separate issue than what I was describing. Thanks for the report.

**Comment by poke22** [comment]
@michaelkirk Not at all. I was wondering, are notifications dealt with within the app or server-side?

**Comment by michaelkirk** [comment]
> I was wondering, are notifications dealt with within the app or server-side?

Both.

The Signal Service requests that Apple sends a voip-push notification to the app which says something like: "App, wake up and check your messages" (no information about the message is included in the notification).

When (if) the app receives the voip push notification, the device wakes up, and pulls the actual encrypted messages from the Signal Service, and renders the contents of the decrypted message on your lock screen (as configured in your settings).

By pulling the messages from SignalService, your client acknowledges receipt of the message (this is how delivery receipts work). If your client hasn't acknowledged receipt of the message within 30 seconds (because your device was offline, or **was** online but failed to receive the voip-push for some reason), then the Signal Service follows up by requesting Apple sends a generic (non-voip) push notification to the app. Generic non-voip pushes cannot wake up the app to fetch and decrypt the message, so it will show up as "New Message" in your lock screen. Note that this is the same text that would appear if you *were* receiving voip push but configured your lockscreen notifications to be generic in Signal's privacy settings.

Despite the limitation of generic-push notifications not being able to show the decrypted message to the user in the lock screen, having a fallback push is desirable for two reasons: 
1. voip-push delivery seems less reliable.
2. If the device was offline, generic-push notifications will be delivered as soon as the device is back online. Voip-push notifications will not; a missed voip notification is gone forever.

**Comment by michaelkirk-signal** [comment]
This should no longer be an issue. Let us know if you're still experiencing this.
