### ISSUE TITLE
Limited/ No connection on iOS 10.2 and IPv4 only network / Vodafone in Romania

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-iOS#1633]
- [X ] I have searched open and closed issues for duplicates closest related issue: https://github.com/WhisperSystems/Signal-iOS/issues/1190

----------------------------------------

### Bug description
Can not connect or send/receive messages when connected to mobile network that is IPv4.  Works fine when connected to WiFi

### Steps to reproduce
- Update to iOS 10.2 (worked prior to iOS update)
- Connect to Vodafone in Romania over 3G (user called Vodafone support to determine it is IPv4)
- Check Signal's network Status via Signal > Settings wheel (top left)
- Also check whispersystems.org or support.whispersystems.org via browser

**Actual result:** Offline status and no ability to view whispersystems.org webpages
**Expected result:** Status is Connected and can send and receive messages and calls

### Device info

**Device**: iPhone 6+
**iOS version**: 10.2
**Signal version:** 2.6.12

### Link to debug log

 https://gist.github.com/e45b2362de7940343c97b358f00db33a

**Comment by michaelkirk** [comment]
@riya Could you ask the user to submit a log immediately after unsuccessfully sending a message and unsuccessfully making a call?

**Comment by riya** [comment]
@riyapenn I think @michaelkirk meant you :)

**Comment by riyapenn** [comment]
@michaelkirk https://gist.github.com/daadb9fa88890b58812a6df2f2243467 
User also tested with a T-mobile SIM and had success.  Then this user received a new vodafone SIM and there was no change from the original issue.

**Comment by michaelkirk** [comment]
From the log:


2017/02/04 11:25:35:472  The network request failed because of a connectivity error.
2017/02/04 11:25:35:487  [MessagesViewController] Failed to deliver message with error: Error Domain=org.whispersystems.signal.networkManager Code=0 "Signal was unable to connect to the internet. Please try from another WiFi network or use mobile data." UserInfo={NSLocalizedDescription=Signal was unable to connect to the internet. Please try from another WiFi network or use mobile data., NSLocalizedRecoverySuggestion=Please check you're online and try again.}
2017/02/04 11:25:38:690  Error connecting to socket Error Domain=NSOSStatusErrorDomain Code=-9806 "(null)" UserInfo={_kCFStreamErrorCodeKey=-9806, _kCFStreamErrorDomainKey=3}


Looks like we’re being blocked? To determine if it’s domain based, can you see if the user can browse: https://www.whispersystems.org/ <https://www.whispersystems.org/> while connected to the vodaphone wireless in Romania?

**Comment by riyapenn** [comment]
User can not access the webiste when connected to Vodapgone 3G mobile network, but can do so on WiFi.
