### ISSUE TITLE
Can't resend "all link" messages.

### ISSUE THREAD

**Issue by charlesmchen** [signalapp/Signal-iOS#1756]
If a message fails to send, there's a "tap message to resend" indicator.  However, if the entirety of the message is a link (URL), tapping the message opens that link.  And a similar but less severe issue would apply if the message was partially a link.

Design possibilities:

* If you tap in a link of a failed message, we should see an action sheet with "open link", "resend message", and "cancel" buttons.

![signal-2017-02-12-203631](https://cloud.githubusercontent.com/assets/625803/22868375/2a94624c-f163-11e6-9408-63d9179f236e.jpeg)

**Comment by christophhagen** [comment]
Is it possible to intercept the tap on a link? I thought that's done automatically by iOS with data detectors.
I'm not sure if JSQMessagesController has support for that, but maybe it's possible to show an exclamation mark icon to the left of the message. A tap on that could then give the desired options, I think this might be similar to the behaviour in iMessage, but not sure. I would like this option, because an icon next to the message would also give the possibility to indicate other features to the user, like delete or copy the message, or share to different conversation (like #1788)

Does anyone have more knowledge about these possibilities?
I could look into it if someone asks nicely :)

**Comment by TreatyOfRome** [comment]
#849
