### ISSUE TITLE
More attachment-related changes.

### ISSUE THREAD

**Issue by charlesmchen** [signalapp/Signal-iOS#1760]
Proposed changes:

- [ ] Generalize `FullImageViewController` into a `MediaViewController` or `AttachmentViewController` and use it for audio and video as well. 
   * Will make scrubbing audio easier.
   * "Edit actions" (e.g. "save", "copy" and eventually "share") should be consistent across these attachment types.
   * Would also be nice to have a consistent "done/back" design for all attachment types.
- [x] "Copy/delete/save" controls are positioned outside the image/video, which is not consistent with other apps.  It should appear just above/below the touch. Current positioning is also ambiguous about which attachment will be affected, since the controls can easily appear above a different attachment.
- [ ] Audio attachment's "play" button sometimes disappears if pressed.  
- [x] Tapping the audio attachment's "play" button doesn't work - you have to tap the waveform.
- [ ] Although the pragmatic short-term fix is to dismiss the image attachment view with a "swipe" gesture recognizer, in the long run it'd be nice to use a "pan" gesture recognizer so that the gesture animates and thus indicates its effect and is cancellable.
- [ ] It'd also be nice in (a hypothetical future) "combined image/video/audio attachment view" to allow users to left- and right-swipe through the media in this conversation. WhatsApp and iMessage both let you do this and it's quite convenient for media-heavy conversations.

**Comment by anatoli26** [comment]
I just wonder why not to copy the UI from Telegram (the actual visuals and the code, it's open-source)? It's so well polished, no need to reinvent the wheel.

**Comment by jerclarke** [comment]
Love these ideas! 

Want to give a big +1 to "combined image/video/audio attachment view" to swipe between media sent in a conversation. FB Messenger also has this and it's invaluable as a way to jump to media that might be very far back in the convo extremely quickly, especially because there is no "conversation gallery" feature (which also exists in FB and is really useful). Having one or the other of these two features is kind of mandatory. 

Swiping left and right gallery references: #759 

Per conversation media gallery References: #2647

**Comment by jerclarke** [comment]
I say it's still relevant :)

**Comment by jerclarke** [comment]
Yeah, still relevant to me!
