### ISSUE TITLE
Use different UI elements for disappearing messages

### ISSUE THREAD

**Issue by jauderho** [signalapp/Signal-iOS#1991]
I find that having the hourglass under the message bubble breaks up the flow of the conversation. 

I would like to suggest moving the hourglass inside the message bubble to either append or prepend. Otherwise, maybe having a different color than blue for the message bubble would signify a disappearing message much like a green bubble signifies SMS in iMessages.

**Comment by rocknjohn** [comment]
I agree the hour glass could be improved. It messes up the spacing between message bubbles making it less visually appealing.

Some ideas:
1.) Use a 'thought cloud' style message bubble. This would be a solid blue dot separated from the larger message bubble, instead of the current sharp adjoined tail. It would look nice on it's own and signify a disappearing message. This style message would be for disappearing messages and the regular message bubble tail for regular messages.
2.) Or move the hour glass inline with the message and next to the message bubble (not inside it & not underneath it so spacing isn't affected)

**Comment by denver-s** [comment]
I think this can be closed now.
