### ISSUE TITLE
Contacts don't refresh without closing the app

### ISSUE THREAD

**Issue by hodgesmr** [signalapp/Signal-iOS#2021]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
If one of my contacts joins Signal, they don't show up as a Contact in my __New Message__ screen without completely closing the app.

### Steps to reproduce
- Leave app open
- Have a contact install Signal on their iPhone
- Open __New Message__ Contacts screen in Signal
- _Contact not present_
- Completely close app from app switcher
- Reopen app
- _Contact present_

**Actual result:** Contact not present until I completely close an reopen the app
**Expected result:** My contacts screen should refresh with the new contact without having to close the app

### Device info

**Device**: iPhone8,1
**iOS version**: 10.3.1
**Signal version:** 2.10.1

### Link to debug log
https://gist.github.com/anonymous/53fde209dc18eaabe56d009105384ec2

**Comment by michaelkirk** [comment]
How long was the other user registered before you noticed they were not in your contacts list?

Unfortunately, it can’t be immediate. Since we don’t store anything about your contacts on the server, you won’t see that Alice has installed Signal until the next time your client initiates a contact intersection.

However, we should fix the contacts list so you can pull-to-refresh to trigger a manual sync.

**Comment by hodgesmr** [comment]
>you won’t see that Alice has installed Signal until the next time your client initiates a contact intersection.

Ah, I was probably just checking too fast.

**Comment by michaelkirk-signal** [comment]
The original issue was a misunderstanding of the limitations imposed because Signal does not store your contacts on the service.

If Alice has *just* registered, ideally your device would reflect that. But how would your device know that Alice just registered?

Services that store your contacts list can do a reverse search and update all clients which have Alice in their contacts, but since Signal doesn't store your contacts, we have to rely on a cruder mechanism - polling. Your device polls for new contacts on startup, when your contacts change, and then every-so-often based on time passed.

I'm going to close this as the original issue was addressed by offering a manual way to refresh contacts, but if you are experiencing something other than what I described, please open a new issue, completing the issue template (importantly including a debug log) so we can get to the bottom of this.
