### ISSUE TITLE
confusing UI causes user to send unencrypted signal messages

### ISSUE THREAD

**Issue by outsideyourbox** [signalapp/Signal-iOS#2382]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Signal UI, especially pop-ups and notifications, looks a lot like other messaging apps.  The result is that the user workflow easily gets changed from using Signal to using another app, without the user intending this, and without the user realizing this has happened.  The main thing you have to understand is that the human mind automatically filters out a lot of information and unfortunately a small word saying "Signal" or not saying "Signal" in the title of the notification will get filtered out by the human user, and so if you want to have a UI that is actually useful for real users, as opposed to a UI that literally gets real users killed as is presently the case, then you have to take into account how real users will filter and perceive the information in the UI.  There is very little opportunity for the user to recognize that the Signal message they are sending (or receiving) is not a Signal message.

more description of this problem is in this youtube video:
https://twitter.com/NyanRat0/status/888588376726790145

### Steps to reproduce
- you're using signal, you're sending and receiving signal messages.
- all of a sudden you've clicked a pop-up or whatever, and you're now using a different messaging app
- the user experience makes it too difficult to notice that you are now sending your signal messages via the wrong app.

**Actual result:** 
the NSA or other hostile parties now have unencrypted copies of one or more of my signal messages, which can result in problems up to and including the death of the user.  I look on the signal web site for info on how to report a severe security bug, finding no info I e-mail signal asking how to report a severe security bug, and I get an e-mail back stating 'just e-mail us the bug' with no mention of this github bug tracker, and I never hear back from Signal employees ever again, despite trying for weeks to get ahold of them and asking for followup.  It seems from this that the folks at Signal don't really care about user security.

**Expected result:** 
the signal UI should not be camouflaged to be easily confused with the UI of non-encrypted messaging apps.  It should be easily apparent when I am sending messages via Signal and when I am not.  The Signal web site should have info on how to report security problems with signal.  When employees of signal receive a report of a security problem, they should not ignore it.  Signal employees should at least appear to care about user security.

### Screenshots

Please see attached screenshot

### Device info

**Device**: iphone 5s, and android phones too
**iOS version**: various
**Signal version:** 2.14.1.2
![signal bug](https://user-images.githubusercontent.com/30580450/28759172-78d3a9e2-755f-11e7-84b3-2cec23c6b13a.png)

**Comment by sheparddw** [comment]
One potential solution to this is to recommend users disable notifications from unknown users in iOS Messages via iOS in Settings > Messages > Filter Unknown Senders. This would prevent anyone not a contact from displaying notifications.

**Comment by 3WfMeCuUqzgXBh** [comment]
I see the point and maybe some slight tweaks to the UI could help with this issue being raise however the rambling in those videos are both confusing and misleading.

If what you are transmitting is so incredibly sensitive then stop take a breath and make sure you are using signal before you send yea? If I was about to transmit something sensitive via email, signal or whatever medium I sure as hell would take a few seconds to make sure I have encrypted AND that I am sending it to the right person.

**Comment by outsideyourbox** [comment]
Dear 3WfMeCuUqzgXBh,

Ya know how guns have a safety lever on them?  Well according to your logic here, there's no need for a safety on a gun, because hey, if you were about to use something "so incredibly sensitive" as a gun, you "sure as hell would take a few seconds to" "stop, take a breath, and make sure" the gun is pointed at the right target.

Congratulations 3WfMeCuUqzgXBh, your failure to understand the first and most basic concepts of user design and your complete failure to care about the welfare of the user qualifies you to work on the Signal project.

Oh and by the way, there's this other bug whereby Signal randomly routes Signal messages via unencrypted SMS even when the user hasn't been misled by the Signal UI, which the good folks at Signal also have not fixed this bug, so why don't you go encourage more apathy in the comments for that bug also:
https://github.com/WhisperSystems/Signal-Android/issues/5531#issuecomment-341828812

**Comment by 3WfMeCuUqzgXBh** [comment]
@outsideyourbox 
Don't you think you may be overreacting just a little? You are drawing a comparison between shooting someone and sending a text message...

Anyway I agreed with your point about the UI and the fact that it could be possible to accidentally mistake the signal messages with the standard IOS messaging app. I think it could be worth looking in to changing the UI to ensure that the user can be 100% certain that they are in signal and not in another app.

I will also agree with you that sometimes the responses from Signal support leave a lot to be desired and it can be hard to get a point across.

What I disagree with is your approach and some of the things said in that video because I feel they are misleading even in your reporting of the issue here you say:

'the NSA or other hostile parties now have unencrypted copies of one or more of my signal messages, which can result in problems up to and including the death of the user'

This sounds ridiculous I am sorry. If you are really dealing with life and death situations you can't put the onus on signal to ensure that you use the right app to send the message. Furthermore if you are genuinely involved in something this serious then you are potentially the target of the NSA or other agency in which case Signal isn't going to help you my friend. If they really want your messages they will target you directly rather than bothering to try to intercept them.

I still stand by my comments that if the content of your messages are that critical you would take some responsibility yourself to ensure they are communicated securely. In fact IMO you would have to be out of your mind to be using signal on a phone along side all these other messaging apps if you had something genuinely super sensitive to communicate.

For the record I don't work on the signal project I just try to help out with testing where I can.

**Comment by michaelkirk** [comment]
Every comment you leave notifies every subscriber in the repository. That's why we only use Github for reporting issues and for requesting features, not for discussion. 

For discussions, move to the forums: https://whispersystems.discoursehosting.net/

If you'd like to voice your concern for / opposition to a particular issue, use Github's "reaction" feature which doesn't result in spamming every subscriber of the repository.
