### ISSUE TITLE
Automatic removal of messages based on a time (or number of messages per thread?)

### ISSUE THREAD

**Issue by FredericJacobs** [signalapp/Signal-iOS#254]
It's technically really easy to implement since we're already using a similar database index to sort messages in the MessagesViewController.

Ephemerality ftw

**Comment by FredericJacobs** [comment]
Screenshot from the Android setting
![image1](https://cloud.githubusercontent.com/assets/400296/5600017/0f9ab654-92d2-11e4-9f4f-744b6bb15729.JPG)

**Comment by corbett** [comment]
cool, let's do that then (but egads so many settings)

On Fri, Jan 2, 2015 at 9:52 PM, Frederic Jacobs <notifications@github.com>
wrote:

> Screenshot from the Android setting
> [image: image1]
> <https://cloud.githubusercontent.com/assets/400296/5600017/0f9ab654-92d2-11e4-9f4f-744b6bb15729.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/254#issuecomment-68565933>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by abolishme** [comment]
Clarifying question @corbett and @FredericJacobs, please mention me in your answer: would the conversation history still be available on the server side, and just the local copies deleted? So you'd have a pull to refresh style "loading more messages" UI like most other clients? Or would they just be gone forever?

**Comment by corbett** [comment]
@abolishme conversation history is never available server side. the server
does queue up undelivered messages but once they are delivered the server
doesn't know or doesn't care. they would be gone forever.



On Fri, Feb 27, 2015 at 1:46 PM, Tyler Reinhard <notifications@github.com>
wrote:

> Clarifying question @corbett <https://github.com/corbett> and
> @FredericJacobs <https://github.com/FredericJacobs>, please mention me in
> your answer: would the conversation history still be available on the
> server side, and just the local copies deleted? So you'd have a pull to
> refresh style "loading more messages" UI like most other clients? Or would
> they just be gone forever?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/254#issuecomment-76477851>
> .
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by abolishme** [comment]
One concern I have @FredericJacobs and @corbett: if someone texted me something I want to save, then they send me 200 texts tomorrow and the max-message X was set to 200, i would lose it? 

If that's the case, we should make it possible to pin/save messages that won't disappear with the rest (snapchat does this) ... i'll add that to my brainstorm list.

**Comment by FredericJacobs** [comment]
@abolishme: Keep it simple. We already have enough complexity with archiving and deleting. Pinning is really not needed.

**Comment by Baigle** [comment]
There wouldn't be an easy and secure way to save messages like that without something similar to #738. 
Legality (local to user) and threat of death aside, these are all just ways of hiding/ protecting past conversations that the protocol tries to protect so desperately in transit.

How well would this cooperate on its own, or with existing anonymity systems where users really are in a very desperate situation regarding communications?

**Comment by roadkillazpartybird** [comment]
I agree it should mirror the android 'Delete old messages' option as seen in the above picture. Then there won't be any confusion! :)

Can't wait to see this implemented in iOS.

**Comment by campingisintents** [comment]
This is an essential, yet missing feature: inactivity-based deletion. The best way to analogize this would be to talk about like Google's inactive account manager. After a certain period of time of the app/device not being used, a message would then automatically be deleted. Otherwise, if the person continues use of app, no auto delete for older messages. The importance of this time-based deletion policy cannot be overstated for unapproved searches and/or seizures of devices for local attacks.

**Comment by Wikinaut** [comment]
👍 I also would like to see the "Delete old messages" option (which is in the Android version) in the iOS version.

**Comment by tomj** [comment]
While this issue is a feature request and so should be closed regardless, I can additionally confirm this feature has been implemented and shipped to production in 2.38.1.2 in the form of "Disappearing messages".

**To use feature:** click on a chat in the chats list, click on "Tap here for settings" next to contact avatar on UINavigationBar, toggle the "Disappearing Messages" switch and adjust duration for message lifetime using the revealed slider.

An announcement of the feature [was made on the blog](https://signal.org/blog/disappearing-messages/) on 11 Oct 2016 and there is a [Signal support page](https://support.signal.org/hc/en-us/articles/360007320771-Set-and-manage-disappearing-messages#ios_disappearing) with slightly more detailed usage instructions.

**Comment by u32i64** [comment]
@tomj However please note that the specific feature shown in https://github.com/signalapp/Signal-iOS/issues/254#issuecomment-68565933 **is not implemented in iOS**.

I'm not sure if the *Conversation trimming based on message count* is available on Android but surely it's not available on iOS, while *Disappearing messages* is available on all platforms.

*Conversation trimming based on message count* `!=` *Disappearing messages*.

**Comment by tomj** [comment]
@u32i64 thanks for the heads up - my closure recommendation was based on the current issue title but I get what you're saying about that comment. 

Regardless of whether it has been shipped to prod, this issue is a feature request and should be recognised as such in some form, and closed/[transferred](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) to a listing of feature requests.

From there any further discussion can ensue in a separate but related thread.  Here's a [placeholder](https://github.com/tomj/signal-ios-feature-requests/issues/1) for now to keep track of any further discussion you want to throw out while the upstream krew work out a strategy to pipeline feature request issues to working feature requests and clear out this backlog.

**Comment by ReallyReally17** [comment]
How is this issue closed?

How can you justify an ever increasing consumption of space?

**Comment by KaloyanTanev** [comment]
Can we open this one again? Currently Signal is taking 25.32GB of space on my iPhone without providing any neat way of reducing that.

**Comment by obinoby** [comment]
> Can we open this one again? Currently Signal is taking 25.32GB of space on my iPhone without providing any neat way of reducing that.

+1

**Comment by ameckl** [comment]
> > Can we open this one again? Currently Signal is taking 25.32GB of space on my iPhone without providing any neat way of reducing that.
> 
> +1

+1

**Comment by Wikinaut** [comment]
Again +1

**Comment by ReallyReally17** [comment]
And again +1.Sent from my iPhoneOn 30 Mar 2025, at 10.41, Wikinaut ***@***.***> wrote:﻿
  Again +1—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



Wikinaut left a comment (signalapp/Signal-iOS#254)
Again +1

**Comment by Napsterbater** [comment]
This is absolutely silly that this is not an option on iOS, why does the Android app get it but not iOS?

**Comment by obinoby** [comment]
> This is absolutely silly that this is not an option on iOS, why does the Android app get it but not iOS?

Now that Signal offers a paid option to back up and remove old content from the phone while keeping it available in the Signal Cloud Backup, I guess this feature will likely never come... ?

**Comment by Napsterbater** [comment]
Which would be a little ridiculous if that was the decision-making process. But I would caution that that's probably not the issue just based on how long this has been open.
