### ISSUE TITLE
Debug log should fully redact phone number

### ISSUE THREAD

**Issue by rocknjohn** [signalapp/Signal-iOS#2540]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Signal's debug log currently contains part of the phone number of both the sender and recipient in the following form and posts it publicly to a gist:
Sender: [ REDACTED_PHONE_NUMBER:xxx999 ]
Receiver: [ REDACTED_PHONE_NUMBER:xxx123 ]

IMO all personally identifiable information should be removed from these. More users such as myself will be willing to submit debug logs.

### Steps to reproduce
- Settings > Advanced > Enable debug log
- Perform an action on the phone
- Click submit debug log and choose link. View the gist to see the contents.

**Actual result:** Partially redacted phone numbers exist.
**Expected result:** No personally identifiable info should exist in the debug log

### Possible solutions
1. Redact/remove the phone number entirely (preferred)
2. If this info is sometimes needed by devs, hash the exposed digits for privacy. And then it could be compared against the hashed last digits of numbers in the DB if needed. Although this is probably rarely needed.
3. Use a random UUID for users both locally and in the DB if needing to identify the users so part of phone number isn't exposed.

### Device info
**Device**: iPhone 6
**iOS version**: 10.3.3
**Signal version:** 2.15.3.2

**Comment by oonimooni** [comment]
yeah truly i agree with this bug , why the fuck i would c the last digits of my phone number in the debug report ???????? what kind of privacy shit we are talking about ?

**Comment by mailinglists35** [comment]
not just the phone number, if you pay attention there are lots of other unique ids there for signal devs to make a link between your github account and the signal account, including the timestamps (as they have sub milisecond resolution).

**Comment by oonimooni** [comment]
_|_ if signal provide any privacy

**Comment by michaelkirk-signal** [comment]
Often we're debugging issues that involve the interactions between multiple clients. If we completely removed this information, fixing some of these cases would become much harder, if not impossible, since we couldn't have any coherency as to a sequence of events between clients.

Keep in mind: We already mostly redact the phone number, and debug logs only live on your device, unless you choose to submit one to us. 

If you aren't comfortable with that, feel free to disable debug logging in Settings > Advanced.
