### ISSUE TITLE
iOS Import/Export

### ISSUE THREAD

**Issue by white8785** [signalapp/Signal-iOS#2542]
This was closed, but was on the roadmap 2 years ago.  Is there any progress here?
https://github.com/WhisperSystems/Signal-iOS/issues/905

Thanks

**Comment by NiklasBr** [comment]
Yes, [I would also like to know](https://github.com/WhisperSystems/Signal-iOS/issues/901). I would also like to know why we are not allowed to back up if we only back up using encryption (iTunes). Are there any known [flaws in the iTunes backup process](https://www.apple.com/business/docs/iOS_Security_Guide.pdf) or macOS file vault that put data at risk?

**Comment by ejpcmac** [comment]
@NiklasBr Same concern for me. I was about to ask this as I need to restore my iPhone —I don’t receive any push notification anymore— but I don’t want to loose all my history and verified numbers. It’s a pain to verify all contacts again.

Signal data was backed up in encrypted backup only a few years ago, but this feature suddenly disappeared I had a really bad surprise figuring that after a restore.

**Comment by nicokaiser** [comment]
I think a simple "export as text email" feature would already be a huge step (yes, unencrypted, but that is a decision the user has to make). Currently it is not possible at all to save a conversation.

**Comment by SuperDisk** [comment]
I might take a stab at this over the weekend.

**Comment by vsivsi** [comment]
IMO this is a *must have* feature for iOS. I have recommended Signal to a large group of friends (20+) and I am about to regret that because if this issue. 

Let me explain...

This group of friends are all now actively using Signal for 1:1 and group conversations, with lots of multiperson subgroups etc.

Out of 20 some people, somebody is going to lose/destroy/upgrade their mobile device every 1-3 months. And every time that happens, there is literally no current way for them to cleanly and easily migrate their “Signal Life” to the new device. Instead, they lose all of their history, and everybody gets a warning that their connection to this person is no longer trusted and needs to be reverified. 

After this happens a few times (the first was this weekend) everyone will realize that Signal sucks for everyone when anyone gets a new device. 

This is a purely technical problem, that has a purely technical solution. The fact that every user in a large social group is negatively impacted every time some user gets a new device is just an intolerably bad user experience. 

I truly hope that this is fixed very soon, or I will stop reccommending Signal to new people, and will instigate an orderly migration of my social group(s) to other platforms before this bites us again, and again, and again.

**Comment by aklef** [comment]
Quite the same as @vsivsi I went as far as to (from a jailbroken iOS8.4 to a jailbroken iOS10.2) try SSH'ing into my old device, grabbing the encrypted ".sqlite" and throwing it onto the new device.

NO luck ;/ I've wasted an hour of my life try to get back all of my verified contacts, my chat history and attachments.

Please add this feature somehow. 

maybe give us an option to export the whole DB and the attachments as one big encrypted file with some kind of super encryption and require some kind of token to identify on the receiving end (maybe a key file sent over bluetooth or something perhaps) maybe even have the old phone verify with the new phone that it is allowed to decrypt and import the old data.

I'm a broke student but boy if I had money I'd be trowing it in your faces right now to get you to develop this. This one feature literally made me do a 180 on my opinion of the app, and my ability to use it has been reduced to nothing effectively... which may the the desired effect but its incredibly non-user firendly

/rant over
/gowhispersystemsgo

**Comment by basnijholt** [comment]
I recently moved from iOS to Android and now (one month later) back with my old iPhone again that I was keeping, just to keep my messages on Signal.

Unfortunately, I ran into this https://github.com/WhisperSystems/Signal-iOS/issues/1812 issue and now I am forced to delete my whole chat history because I need to reinstall Signal. However, I don't want to lose more than a year's worth of messages, so for the moment, I cannot use Signal.

I am a programmer, unfortunately without any knowledge of Swift or Objective-C, so my options to contribute here are limited. 

Is it possible to retrieve my messages in any way?

**Comment by marrinan** [comment]
I'm willing to make a substantial contribution to @NiklasBr 's [bounty](https://www.bountysource.com/issues/28598496-message-export-backup/backers), as this a mission-critical feature for me as well. Any Objective-C wizards out there looking to make some cash over the weekend?

**Comment by basnijholt** [comment]
@marrinan I've also just upped the bounty (although not that substantial.)

**Comment by SuperDisk** [comment]
I actually tried giving this a go a couple weekends ago (since honestly the code is already all there in the Android version, it just needs porting) but I couldn't set up the dev environment. I'll get around to it eventually if someone less lazy than me doesn't step up.

**Comment by accendosystems** [comment]
Hi SuperDisk, any idea of a timeline when you think you will be working on this?
Thank you!

**Comment by seanpianka** [comment]
@superdisk I’m interested in contributing to this but am new to the Signal codebase, could you provide any links to the implementation of import/export for Signal-Android?

**Comment by EricaJoy** [comment]
I just upped the bounty for this.

**Comment by jschneier** [comment]
Signal Android implements backups/exporting by allowing the user to write to an SD Card (I believe). I don't think that iOS doesn't permits that action which is why backups were never implemented. Has there been a change in opinion from anyone at Whisper Systems or in iOS functionality (or am I mistaken)?

I believe the logic was that since backups are stored in plaintext (you lose the private key if your device explodes) putting it in iCloud doesn't make a ton of sense/defeats the purpose? WhatsApp obviously makes a different compromise and does just that. I personally don't have iCloud enabled and would be really happy if I could back up to iTunes with encrypted enabled.

**Comment by white8785** [comment]
+1 for direct to pc backup and not relying on iCloud.

**Comment by KHarshawat** [comment]
I just upped the bounty. Please please someone add this feature. I'm an iOS user but having replaced my phone twice within the last two months I can attest that this is a major pain point.

**Comment by NiklasBr** [comment]
@michaelkirk you have participated in similar discussions, do you have anything to add?

**Comment by jacksenechal** [comment]
Upped the bounty. This needs to happen. It's the one major usability hole in Signal, and it's a major one.

**Comment by lhl** [comment]
Just upgraded to a new iPhone and discovered that I can't transfer my history to my new device. If the intention is to make messages irretrievable for security reasons then it should 1) make this clear when installing and 2) delete or not keep message history at all (otherwise what's the point if your history is on a misplaced or confiscated. If not, then I can't understand why an export doesn't exist? Doing a search, I found #967 as an open issue from 2 years ago. Is this really that low on the priority list? Does no one on the team actually use Signal like a normal person?

**Comment by vsivsi** [comment]
@lhl I suspect that this is perhaps explained by iOS being the secondary platform of the targeted user base.  If to them a “normal person” is an Android user, then that answers your question.  My understanding is this is an iOS-only issue. 

What I find bemusing is that iOS Signal has had literally a couple dozen updates since this issue was opened in September, and not a single Whisper Systems representative thas come here to even notice this conversation and acknowledge the issue.  In this meantime they’ve been working on lots of important core features like Jumbo Emoji and Embedded GIF animations. It’s like they’re really focused on matching Telegram’s most frivolous consumer facing features (can Stamps be far behind?) while such a basic and essential bit of missing core functionality is literally being ignored. 

I just don’t get it.

**Comment by NiklasBr** [comment]
Maybe @moxie0 can chime in?

**Comment by mateoeh** [comment]
@vsivsi The backup situation on Android is far from perfect, too: group messages and images aren't backed up and the encrypted backup option has been 'temporarily removed' for something like 2 years now. (see WhisperSystems/Signal-Android#1619, WhisperSystems/Signal-Android#1705, WhisperSystems/Signal-Android#4577, etc.) Backups are just a time-consuming and non-fun item to implement in general. Of course, since Signal is a completely free and open source product, there's always room for pull requests...

**Comment by jschneier** [comment]
@mateoeh I and likely others would be happy to look at contributing a backup solution if there was one that was blessed by OWS. Since there is no SD card access on iOS and that is how Signal-Android performs them there is no clear path forward. I imagine many people don't want to put in the considerable effort to implement this feature only to see it then languish sans comments and feedback or see it closed altogether as an unacceptable solution.

**Comment by EvanHahn-Signal** [comment]
As was mentioned, we'd like to use GitHub for bug reports, not feature requests. Please use [this community forum thread][0] to discuss this feature further, and the community forums to discuss other feature requests in general.

[0]: https://community.signalusers.org/t/ios-backup-keeping-message-history-when-switching-phones/1736
