### ISSUE TITLE
Messages after safety number changed when marked as verified.

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#2900]
If i mark as verified one of my contact for example "Bob" and he changes his phone is up to me to choose if receive messages from him or not. Whereas you just advise that the safety number is changed but his messages continue to arrive without any problem. I think that if I mark someone contacts as verified than i have to choose if receive messages from him or I want to wait and verify again his safety number. This because of MITM and other types of attacks.

Leonardo

**Comment by michaelkirk** [comment]
@leonardoporpora - this was an intentional decision and is unlikely to change.

We try to keep the GH traffic to all our subscribers dedicated to concise and accurate bug reports and feature requests, so for further discussion on this issue, please take it to the forums: https://whispersystems.discoursehosting.net/
