### ISSUE TITLE
[New feature]

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#2948]
Due to vulnerabilities found also in signal for not right authentication in groups I would like to add a feature. To close groups so that one member could close the group. Example there are 5 person in this group one member close it so that no one else can enter in it.

**Comment by michaelkirk** [comment]
Thanks for your thoughts on this, but we're not going to implement something like this.

It sounds like you're talking about a recent academic paper which partially describes how group messages work in Signal, but to join a Signal group you'd have to know the unguessable 128-bit group secret. Also keep in mind, **any** change in group membership is **always** visible to all group members.

Also, in the future please do not delete the issue template. We use github for bug reports and complete feature requests. If it's a partially formed idea that you'd like to discuss, the forum is the best place for that, otherwise our repository subscribers get tons of notifications as the details are hashed out.  https://whispersystems.discoursehosting.net/
