### ISSUE TITLE
Calls feature not working after building on Xcode

### ISSUE THREAD

**Issue by kuala-lumpur1** [signalapp/Signal-iOS#2958]
Hi ,,
I'm trying to build the app using xcode. Everything works perfect except the calls feature from iPhone to iPhone or from android to iPhone .. 

but calling works perfect from iPhone to android.

i have tried with iPhone 5s and 6 ,, same issue.

i have checked the permission for signal app and everything is enabled !

The iPhone receive the ringing but when i answer the call the app crashes and take me to this screen

![signal-2018-01-24-002945](https://user-images.githubusercontent.com/35842753/35445623-4599689a-02c3-11e8-8f18-54c789b4fd8c.jpg)

all pods are installed successfully with no errors

<img width="740" alt="screen shot 2018-01-26 at 6 35 03 pm" src="https://user-images.githubusercontent.com/35842753/35447309-69aae66e-02c8-11e8-977d-c7a6cfd0a1a4.png">

Link to Debug log
https://gist.github.com/kuala-lumpur1/f324e83e631fdd96bf9f2b9b655c0c42

**Comment by michaelkirk** [comment]
Just to clarify - that's not a crash, but a failed call screen within Signal - i.e. there won't be any crash report with more details.

Your report makes it sound like you were unable to connect any calls **to** Signal-iOS.  But to me, the log looks like the call recipient declined the call at approximately the same moment as the caller hung up, which incorrectly displays the "call failed" dialog. Is that what happened?

Or if in fact you aren't able to connect calls to iOS, could you please reproduce and submit a debug log from both the call sender and the call recipient? (ideally both are iOS clients).

One thing to be aware of, your home-built client will not be able to receive notifications from Apple (this is an iOS restriction, and not something we can do anything about), so your app must be running in the foreground to receive messages and connect calls.

**Comment by kuala-lumpur1** [comment]
Yes i'm unable to make any calls to any Signal-iOS .. i tried with two iphones with me ..  and i didn't declined the call. once the recipient receive the ringing and answer the call he gets the picture of Signal call Failed.

i know already about the notification part. both apps are opened when we try to make calls.

here's the logs for call sender and the recipient devices.

https://gist.github.com/2c926215d2989ab54c1f2fbf38f096ca

https://gist.github.com/ecb6bea0f651322ad978614f92f0bf74

Hope this helps and i can find soultion for this.

**Comment by kuala-lumpur1** [comment]
thank you for your help
now the call working perfect
just theres small error after answer the call 

this video will show you the error .. once the recipient answer the call it takes him to the screen logo for signal app .  .. then the call working with no proplelm 
https://youtu.be/1MJqqz1c-qc

this issue is happening on both signal from store and also when building signal from xcode


this is the log for two iphones

https://gist.github.com/kuala-lumpur1/2cb4a39ef2f6c3c32ecfc41c0f89bd30

https://gist.github.com/kuala-lumpur1/28bf44a6a27a7fda96f928395f840714

**Comment by michaelkirk** [comment]
> this video will show you the error .. once the recipient answer the call it takes him to the screen logo for signal app . .. then the call working with no problem
https://youtu.be/1MJqqz1c-qc

I think you are saying that you are seeing:

- System call ringing screen, you tap answer
- See the Signal Logo
- See the "in call" screen

But what you are expecting to see is just:

- System call ringing screen, you tap answer
- See the "in call" screen

Is that right?

Unfortunately, that's expected behavior when you have screen security enabled. 

Screen security obscures the contents of the signal app whenever the app is not in the foreground. Displaying the system call screen actually entails leaving the app momentarily.

To be explicit, here's what's actually happening

- iOS wants to report an incoming call, so Signal leaves the foreground
- Signal, whenever leaving the foreground, checks if Screen Security is enabled, and if so obscures it's content with the logo.
- iOS displays the system call screen.
- You tap "answer" on the iOS system call screen.
- iOS system starts to return Signal to the foreground.
- (Signal Logo is still obscuring content)
- Once Signal is in the foreground it removes the Screen Security logo.
- You can now see the "in call" screen within Signal

To get rid of this, you can disable screen security in Signal > Settings > Privacy, but be aware that you'll be displaying app content in the app switcher.

**Comment by kuala-lumpur1** [comment]
Perfect .. i have followed the instructions to disable screen security and that works good with me.

Thank you so much for your help  @michaelkirk . really appreciate it
