### ISSUE TITLE
Support Call Holding - Signal call is being disconnected when trying to switch to regular incoming phone call

### ISSUE THREAD

**Issue by arekm** [signalapp/Signal-iOS#3019]
- [x ] I have searched open and closed issues for duplicates

Scenario is like this:
- I'm talking via signal (video in this case but probably the same problem happens in audio only call, too)
- someone calls me via regular phone
- I see notification (just like when having regular phone conversation and second call comes in) and I'm presented with a button to switch to the other - phone - call. See screenshot.
- when I try to switch to incoming call signal call is disconnected instead of waiting in background

That's what iOS user sees when someone is calling with regular phone call. Removed photo of calling person (that was as a background for this image):

![someone-calling](https://user-images.githubusercontent.com/50869/36276472-607118e0-128e-11e8-93c8-f77f1c4c1d2d.jpg)

Odrzuć - means reject the call
Przełącz - means switch to incoming call

**Device**: iphone 7 plus
**iOS version**: 11.2.5
**Signal version:** 2.19.5.0

Integration with iOS calling turned on in signal

Note that with regular phone calls when second call is coming in I can switch easily between these two without any problems. The issue is only when using signal for first call.

**Comment by michaelkirk** [comment]
Ending the current call is the expected behavior for that button. In the English iOS localization, the button says "End & Accept". 

But this issue is a legitimate request, since Signal doesn't yet support call "holding". 

Once we do you'll see a third button on that call screen which will place the current Signal call on hold, allowing you to switch to the other call.

I'm going to leave this issue open, but rename it for clarity.
