### ISSUE TITLE
Registration lock reminder prompt should have an option to disable it.

### ISSUE THREAD

**Issue by LogalDeveloper** [signalapp/Signal-iOS#3140]
- [x] I have searched open and closed issues for duplicates
----------------------------------------
### Feature request description
When I noticed the registration lock was available, I immediately got started using it. I prefer generating long PINs and storing them in my password manager instead of creating a short PIN and remembering it. My issue with the registration lock is it occasionally prompts for you to enter the PIN again so you can remember it, something my password manager is already doing for me. I think this reminder should have the ability to be disabled in some matter so that everyone who might have a long PIN in their password manager doesn’t have to dig it out every time it asks.

### Device info
**Device**: iPhone 7
**iOS version**: 11.2.6
**Signal version:** 2.22.0.4

**Comment by askielboe** [comment]
I don't mind the reminder prompts. I think it's a great feature, but it seems to me that showing it every day (as has been the case for me since I enabled it), is a bit too much?

I'm also using a rather long PIN and it quickly get tedious to type it every time I open Signal in the morning.

**Comment by riyapenn-signal** [comment]
Signal includes a built-in reminder feature that uses [spaced repetition](https://en.wikipedia.org/wiki/Spaced_repetition). The reminder becomes less frequent as you consistently enter your Registration Lock PIN correctly. You'll only see it [once a week after the first few days](https://support.signal.org/hc/en-us/articles/360001842431).

**Comment by askielboe** [comment]
Thanks for the explanation. So the spaced repetition is added purely to force people to remember their PIN codes? I guess that makes sense insofar that you want people to remember their PIN codes, in order to avoid tricky support issues.

That said I still very much support the suggestion to have a option to opt-out of the spaced-repetition. For people who use a password management system (or simply remember their passwords), having to enter the PIN code ever so often, might scare them away from using the feature at all.

I know I'll turn it off for now to avoid having to look up my PIN code whenever I need to text my friends. But then maybe I'm lazier than most people.. :)

**Comment by caveman1973** [comment]
I would prefer not receiving the messages since I use a password manager too. Unfortunately most people don't. 

Imagine having your phone permanently locked without the possibility of using Signal with your own number. That's why it's safer to bother users initially with the pin code. 

This feature is very useful if you use another phone number just to register. It's a way to avoid someone else taking control.

**Comment by b-meson** [comment]
My issue, even with the spaced repetition is that I recently typoed my (long) PIN (which was in my password manager) and now I have to reset it in the privacy menu. Which is fine since I maintain physical possession of my phone. But now I, as a user, am going to be tempted to type a new PIN and make it very short because the UX is quite unpleasant. Also, the fact that this prompt opens _every single time_ I open Signal is extremely frustrating. This kind of design pattern is beginning to have design smell.

**Comment by michaelkirk-signal** [comment]
>  Also, the fact that this prompt opens every single time I open Signal is extremely frustrating. This kind of design pattern is beginning to have design smell.

Provided you're getting your PIN correct more often than getting it wrong, you shouldn't be seeing it every time you open the app. If you are getting it wrong all the time we have reason to believe you could benefit from some extra practice.

The time between presentations are thus defined:
```
    @(6 * kHourSecs),
        @(12 * kHourSecs),
        @(1 * kDaySecs),
        @(3 * kDaySecs),
        @(7 * kDaySecs),
```

If you get it right, you go up a bucket. If you get it wrong you go back a bucket. 

For example, if you never get it wrong, after your fourth entry, you'll be asked once a week. At that point, if you get it wrong once, you'll be next asked after 3 days, which doesn't jive with your report @b-meson. 

If you're seeing something other than that, please open a new issue a submit a debug log next time you get a reminder.

Otherwise, we hear what you all are saying about having an option to disable it altogether - we haven't decided yet how to best deal with it, that's why this issue is still open. No more "me too"'s necessary (though reacting with a 👍 on the original issue is helpful).

 If you'd like to discuss this feature request further, please take it to the forum.
https://community.signalusers.org/

**Comment by GoCyberEd** [comment]
I've had to disable the feature because of this. Even once a week is too often.

**Comment by lbm** [comment]
I’ve also disabled registration lock because of this issue. I completely understand the reason behind the reminders, but they should still be configurable for users who are using password managers.

**Comment by ftobin** [comment]
Whatsapp has the same silliness.  I use a password store on a separate box so I don't have to remember n different pins.  I can look up the pin in the maybe 5 times in a lifetime I'll need to reference it.  I don't need more things to memorize in my life.

Unfortunately Signal is incidentally encouraging the bad practice of people re-use pins across products.

**Comment by jakebasile** [comment]
I hardly use Signal, so no matter what I do I get this annoying prompt almost every time I open the app. Had to remove it, thereby reducing the security of my account. 

Let me handle my own password, please.

**Comment by zee0** [comment]
leaving a comment as this has been open for over a year, clearly folks are interested, but it's still assigned to no one.

this feature, though i appreciate and use it, is implemented in a manner that encourages users to:
a. disabe a feature designed to protect them.
b. dumb down their pass code because they're asked to enter it so often.

while registration lock is making individuals more secure, it's actively discouraging widespread adoption in the community. in a security landscape that continues to get more sophisticated, as more and more groups turn to signal for secure communication, universal adoption of registration lock becomes am imperative.

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

**Comment by anahata0108** [comment]
The forums are *not* a better place to discuss new features. Forums don't have any of the functionality that github does. Why was this change made?
