### ISSUE TITLE
Random iOS authentication requests

### ISSUE THREAD

**Issue by waterweasel4** [signalapp/Signal-iOS#3339]
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

 This isn't a feature request or a discussion topic
Bug description
Signal asks for fingerprint authentication randomly when typing or in a call.

Steps to reproduce
Ensure that the fingerprint authentication is turned on
Start a call/video call.
Chat for 30 minutes or more.
Actual result:
Randomly, the fingerprint notification will appear in the call. This typically happens after 30 minutes or so but it's completely random when it does. I'm not switching networks or moving around so not sure what actually triggers it. I do know this was not present in the previous version of the iOS app if that helps at all.

Expected result:
Don't ask for authentication unless I close the app or do something else.

Device info
Device: iPhone 6s
Signal version: 2.23.4

Link to debug log
Will attempt to get one when this occurs again.

**Comment by rmathus4** [comment]
I do indeed have screen lock timeout set to Instant.  I believe I
changed that in the last update to Signal prior to the latest version
mentioned.  I don't believe I had that problem then though but I suppose
it's possible.  I don't mind setting it from Instant to something else
if you think it might help?

On Thu, Apr 26, 2018, at 11:52, NSDestr0yer wrote:
> Do you by chance have the *Screen Lock Timeout* set to *Instant*?


> Also did you see any other system alerts appear after dismissing the
> screen lock?> I've had a separate app perform background fetch and consequently
> display the "Sign In to the iTunes Store" prompt which inactivates
> signal while I'm typing - that case isn't a bug, but I know it's
> possible for other cases like this because the screen lock will appear
> from OWSApplicationDidBecomeActiveNotification and
> OWSApplicationWillResignActiveNotification notifications as opposed to
> OWSApplicationWillEnterForegroundNotification and
> OWSApplicationDidEnterBackgroundNotification (which is good).> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/signalapp/Signal-iOS/issues/3339#issuecomment-384692734

**Comment by CollinStuart** [comment]
Temporarily changing it to **1 minute** would fix the case where a system alert briefly interrupts the application state of Signal.

I believe this behavior is going to be changed anyway in a recent Signal update (#3202), so that the lock screen timer won't start when the app becomes inactive (at least until 45 seconds of the inactive state), which might potentially fix your issue.

**Comment by rmathus4** [comment]
I'll give it a shot.  Thanks so much!


On Thu, Apr 26, 2018, at 13:08, NSDestr0yer wrote:
> Temporarily changing it to *1 minute* would fix the case where a
> system alert briefly interrupts the application state of Signal.> I believe this behavior is going to be changed anyway in a recent
> Signal update (#3202[1]), so that the lock screen timer won't start
> when the app becomes inactive (at least until 45 seconds of the
> inactive state), which might potentially fix your issue.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/signalapp/Signal-iOS/pull/3202
  2. https://github.com/signalapp/Signal-iOS/issues/3339#issuecomment-384717338

**Comment by rmathus4** [comment]
For what it's worth, it seemed to lessen the issue potentially but during a call last night at 37m10s into the call, I received the authentication pop up even with the screen timeout lock set to 1m.   Debug logs are here if they help at all (I retrieved them this morning rather than last night so it may not have the data needed).  I believe the authentication popup was around 10:15PM Eastern or so. 

https://debuglogs.org/39a566032b6d086ad447f40b5f951c476d0280de7882d043d759b77449065127.zip
