### ISSUE TITLE
Disappearing messages disappear before I open the app

### ISSUE THREAD

**Issue by littleporkchop** [signalapp/Signal-iOS#3470]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by leonardoporpora** [comment]
Hi @littleporkchop could you please include step by step instructions of what you are doing - describe every tap in the app and every screen that you see which leads up to the issue, and then clarify how often you see the issue. For example: Launch Signal Go to thread with Alice Tap paperclip Choose “media library” Select a photo See it uploading and send to Alice As soon as it’s uploaded the app freezes indefinitely. This happens intermittently, maybe 25% of the time. It happens the same way regardless of who I’m messaging. Once frozen, I can’t do anything in Signal at that point unless I force kill and relaunch it. Does that describe your issue? Always include steps like that in your report. It give us a foothold into solving the issue, and will help you help developers to make Signal work better.
If you don't know the steps could you please tell if the issue is systematical or not and include a debug log, the device you are using, the version of iOS and Signal version? :+1: 
Ensure that "Enable Debug Log" is on in Signal's settings then make the bug happen and immediately after that tap "Submit Debug Log" from settings and paste the link below.
Thanks! :)

**Comment by michaelkirk-signal** [comment]
Without more details we can't pursue this. Please re-open with a debug log if you can reproduce this @littleporkchop.
