### ISSUE TITLE
Feature reguest: Show shared media in one place (per chat)

### ISSUE THREAD

**Issue by maxbrandes** [signalapp/Signal-iOS#349]
Since messengers are more and more used to send others pictures and videos, it is easy to lose track over a longer period of time. When searching for a picture, the actual signal build forces me to go through the whole conversation view, with all text messages. 
It would be nice if you would implement an option to display all media in one place, per (group)chat.

![brandy 2015 01 15_479](https://cloud.githubusercontent.com/assets/5220611/5754075/a680b594-9c93-11e4-90e8-ccf70abeebeb.PNG)

**Comment by corbett** [comment]
#539

**Comment by basnijholt** [comment]
This would be really great!

Is it possible to donate specifically for this feature? Something like GitPay.

**Comment by tomj** [comment]
While this issue is a feature request and so should be closed regardless, I can additionally confirm this feature has been implemented and shipped to production in 2.38.1.2

**To use feature:** click on a chat in the chats list, click on "Tap here for settings" next to contact avatar on UINavigationBar, click "All Media" on resulting Contact Info screen.

**Comment by janschoenherr** [comment]
It would also be nice to be able to store multiple, selected Media to the device in a single action.
