### ISSUE TITLE
Unable to link with Signal Desktop after upgrading to 2.26

### ISSUE THREAD

**Issue by NFM-8** [signalapp/Signal-iOS#3568]
### Bug description
Unable to link with Signal Desktop after upgrading to 2.26. No change in Signal Desktop in between.

### Steps to reproduce
- Open fresh installation of Signal Desktop
- Try to link with latest Signal iOS

**Actual result:** Linking process stops somewhere and Signal Desktop does not work

**Expected result:** Linking succeeds and Signal Desktop is functional

### Device info
**Device**: iPhone SE

**iOS version**: 11.4

**Signal version:** 2.26.0.26

### Link to debug log
https://debuglogs.org/ac326a821dcc59e83cc6c6a4c700ec30cb867f444f1f394603c657e152d84a36.zip

**Comment by michaelkirk-signal** [comment]
This should be fixed in the 2.28.0 beta. If you'd like to try it, send an email to support@signal.org with the subject "Sign me up for the iOS Beta".

As I understand it, this issue only affected newly linked devices. So if you have an existing device linked which isn't seeing your Signal Contacts / Groups, you'll need to manually import one time via the "Signal Desktop > Preferences/Settings", then click "Import Now" under "Contacts". 

After updating, if you still have an issue, please re-open this issue.
