### ISSUE TITLE
No Contacts Sync with Signal Desktop

### ISSUE THREAD

**Issue by khashyarkh** [signalapp/Signal-iOS#3608]
- [x] This isn't a feature request or a discussion topic
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I've tried linking to Signal Desktop but failed every time, I tested the same Desktop Device with Android and it worked. 
I've also reported this issue on Signal Desktop:
https://github.com/signalapp/Signal-Desktop/issues/2484

### Screenshots

![image](https://user-images.githubusercontent.com/34171942/41981138-77795130-7a3d-11e8-9e6a-2b2b26765ef2.png)

### Device info

**Device**: iPad 2

**iOS version**: 9.3.5

**Signal version:** 2.26.0

### Link to debug log

https://debuglogs.org/8248909b303137749689dc66638fbbfecab0391873102e6ebbf4d3ddf62f33cc.zip
Desktop Log: https://debuglogs.org/373e628fd6d6adb128f283e3fdc805aca98e7240be06a58c3139782d9ae34406

**Comment by michaelkirk-signal** [comment]
To help debug, can you go to Settings/Preferences in Signal desktop and launch a manual contact sync to see if that works?

**Comment by khashyarkh** [comment]
![image](https://user-images.githubusercontent.com/34171942/41985693-4ccc8dc4-7a49-11e8-96e0-c3962cd8cc0e.png)

**Comment by khashyarkh** [comment]
I Logged out from Desktop and linked again (import failed again) here are the new logs:

https://debuglogs.org/90ce98e232974471e1c5f4dab4318e3ae56a4ecd52b8f6937b4e24dd1051bde9.zip
https://debuglogs.org/0cff3d48e250c9ce4d13a21df633bdccaa923d858204e467757a3f9bdc2759b9

**Comment by NFM-8** [comment]
I think this is the same issue as #3568 and #3589.

**Comment by khashyarkh** [comment]
@NFM-8 Yes, it's only possible to receive messages from other contacts.

**Comment by michaelkirk-signal** [comment]
This should be fixed in the 2.28.0 beta. If you'd like to try it, send an email to support@signal.org with the subject "Sign me up for the iOS Beta".

As I understand it, this issue only affected newly linked devices. So if you have an existing device linked which isn't seeing your Signal Contacts / Groups, you'll need to manually import one time via the "Signal Desktop > Preferences/Settings", then click "Import Now" under "Contacts". 

After updating, if you still have an issue, please re-open this issue.
