### ISSUE TITLE
In a bad need of spin doctors

### ISSUE THREAD

**Issue by Spinnen** [signalapp/Signal-iOS#3670]
Actually the issue #3638, which was posted 4 days ago, and closed right away, shows impressively, that the signal project is in a bad need of some spin doctors.

The way, in which the team communicates here with its customers/users, supporters, fans, cooperative supporters, is just such a mess, that I start to believe again, that most programmers are just nerds, who have absolutely no idea, how to interact with other people.

That the feature landscape mode was requested more than 3 years ago (most products of the competition did not even need such a request), and is still not implemented, is sad enough. And it is hard to find an explanation for that, since even huge differences in programming capabilities cannot explain such a long time.

But the worst issue is, that in this long period of over three years, not one single member of the team has ever written a comment on that, where supporters could help, why this is a problem at all to add this simple feature, this is absolutely not understandable. 

All people who use a software product are very important for the project, no matter, whether they pay for it, or not. People who use Signal and make an account here to report errors or ask questions, or even ask if they can help, are even more important. They way these people are treated by the Signal team, is just despicable.

A team of spin doctors could maybe support the programmers of Signal and teach them, how to communicate with people, who like Signal, use Signal, suggest features and waste their private time to write here.

Three years ago I loved Signal, I recommended it to everyone, I reported errors. Today I hardly use Signal anymore, and started to become sceptical about the project, and to strongly dislike the people in the team.

I am a programmer myself, and I have worked in a few software projects, which lasted for several years. The communication with the users of the software has always been an important matter, which was highlighted in every single project I have seen.

**Comment by michaelkirk-signal** [comment]
We're a small team (but we [are hiring](https://signal.org/workworkwork/)) and sometimes that means that we have to make tough decisions about what to prioritize. We know that landscape mode is a feature that some users want. We're working hard on new features every day, and we have made a lot of recent progress.

We don't use GitHub for discussions or feature requests, which is why that issue was closed (and why I'm closing this one). However, the team regularly participates on the community forums, and you're welcome to join fellow Signal users there if you would like to discuss landscape mode or any other feature requests.
