### ISSUE TITLE
Signal iOS shows local contact picture instead of avatar

### ISSUE THREAD

**Issue by Geblaat** [signalapp/Signal-iOS#3717]
When you have added photos to your contacts in the iOS contacts app, Signal will show them as well. However, if a contact has set their own avatar in their Signal profile, the app will still show the local contact picture instead of the avatar chosen by the contact.

**Comment by Cerberus0** [comment]
Thank you for taking the time to submit this issue. However, it is not a bug. [This is currently the intended behavior in Signal](https://signal.org/blog/signal-profiles-beta/):

>You will start to see more pictures and fewer colored letters in Signal, but **the contact information that is stored on your device will always take precedence.** If you saved someone’s picture to their contact card back in 2007 and it has traveled through time across the vast chasm of a decade of smartphone upgrades, you’ll continue to ride that wave of blurry nostalgia every time they call.

As mentioned in the project's [contributing guideline](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md), this issue tracker is for bug reports and not for feature requests or other non-bug discussions. If you would like to have this behavior changed so that the contact's Signal profile information take precedence over the information that is stored on your device, you are welcome to start a new discussion about this topic at the [community forum](https://community.signalusers.org/) (you can sign up/login with your GitHub account).

Please make sure to read and fill out the [bug report template](https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/ISSUE_TEMPLATE.md) when you submit new issues in the future. Thanks!

**Comment by Geblaat** [comment]
Sorry, I thought this was a bug instead of intended behaviour.
