### ISSUE TITLE
request: option to choose between text and icon for message delivery status

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#3737]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by mailinglists35** [comment]
latest testflight changed delivery status (sent, delivered, read) from text to icons.

this is very confusing. please add option to choose back the text.

**Comment by michaelkirk-signal** [comment]
Hey @mailinglists35  - we only use Github for reporting bugs with existing behavior.

Our community forum is a better place to discuss feature requests and changes to intentional functionality. In particular, check out the thread dedicated to the recent design changes:
https://community.signalusers.org/t/feedback-on-the-new-visual-changes-in-android-4-24-ios-2-28-and-desktop-1-15/3532/3
