### ISSUE TITLE
Signal does not apply suggestion/auto-correct last word before sending

### ISSUE THREAD

**Issue by quickmaths** [signalapp/Signal-iOS#3774]
### Bug description
Signal does not follow through with Auto-Correct (if applicable) to the last entry before pressing send. This causes spelling mistakes usually on the last word of a sentence, which is an annoyance. 

### Steps to reproduce
- Type a word that is purposely mis-spelt with auto correct on
- Press Send
Signal: Word that would have been auto-corrected is not (after pressing send). 
Other Messaging Apps: Word that would have been auto-corrected is corrected after pressing send.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Pressing send while an auto-correct would have taken place as if you continued typing, does not.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Pressing send while an auto-correct would have taken place as if you continued typing, should apply after you press send.
### Screenshots

Signal Result:
![s1](https://user-images.githubusercontent.com/42085539/43673511-ab5ef68e-9807-11e8-8d80-f261c31fb012.jpg)
After pressing send
![s2](https://user-images.githubusercontent.com/42085539/43673510-ab31e982-9807-11e8-927b-419408163447.jpg)

iMessage Result (This is the same outcome on apps such as WhatsApp, Telegram, Messenger etc)
![im1](https://user-images.githubusercontent.com/42085539/43673516-c31a8e14-9807-11e8-91e0-125ad797d6fa.jpg)
After pressing send
![im2](https://user-images.githubusercontent.com/42085539/43673867-426f2968-980d-11e8-8127-51e150c11e81.jpg)

### Device info

**Device**: iPhone X

**iOS version**: Latest (11.4.1)

**Signal version:** Latest (2.28.0)

### Link to debug log

https://debuglogs.org/841d67899db2c0255cf5d464cd099e80bc30541e50c2e50923076dafeff9df71.zip

**Comment by oxling** [comment]
I looked into this, and was able to duplicate the problem. Apparently `UITextView.text` doesn't reflect pending autocorrect changes; hard to say if this is an intentional feature of UIKit or not.

The simplest fix would be to quickly toggle the input view as first responder when the message is sent, like [this](https://gist.github.com/oxling/875139e3feb5e5be7c9abe04ec33c6fe), but at the risk of strange keyboard and notification side effects. I also found [a decent discussion with more esoteric workarounds on StackOverflow](https://stackoverflow.com/questions/4611525/execute-current-uitextfield-autocorrect-suggestion-when-another-button-is-presse).

Might be worth a second look from someone more familiar with the particulars of the messaging view controller 😄

**Comment by bencgreen** [comment]
+1 for this - it’s seriously annoying!

**Comment by denver-s** [comment]
I cannot reproduce this bug on 3.0.0.2

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
