### ISSUE TITLE
Jumbomoji Regression

### ISSUE THREAD

**Issue by FacelessJ** [signalapp/Signal-iOS#3776]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Jumbomoji no longer appear on iOS client when emoji-only messages are sent or received.

### Steps to reproduce
- Send message containing only emoji to iOS client
OR
- Send message containing only emoji from iOS client

**Actual result:** Message contains regular sized emoji

**Expected result:** Message should contain jumbo sized emoji

### Screenshots
Behaviour on signal-ios displaying bug
![signal-ios](https://user-images.githubusercontent.com/3193053/43683268-562d72a2-98cb-11e8-994e-a5b4cc4b767b.jpg)

Behaviour on signal-desktop displaying expected result
![signal-desktop](https://user-images.githubusercontent.com/3193053/43683271-6d9e3282-98cb-11e8-8e5b-da30a6856dc3.jpg)

### Device info
**Device**: iPhone 6s

**iOS version**: Latest - 11.4.1

**Signal version:** Latest - 2.28.0.15

### Link to debug log
https://debuglogs.org/33f3df2b0b8bfb5b5f79a700d1b14a930d8b4f9d7cf582d29e4ee1f12ef6b4b9.zip

**Comment by michaelkirk-signal** [comment]
This wasn't a regression, we've never sized 3-5 emoji much larger than the default sizing.

BUT, the sentiment is correct, and jumbomoji have been made larger for the 2.29 release.

It's in beta now, contact support@signal.org with the subject "Sign me up for the iOS beta" to check it out. Be aware that since it's a beta it may be less stable and could lead to crashing and/or data loss. Do not apply if you have a peanut allergy, etc.
