### ISSUE TITLE
custom ring tone - application stopped working

### ISSUE THREAD

**Issue by MtaTech** [signalapp/Signal-iOS#3883]
Custom ring tone change and stop working app

Xiaomi Mi 8
Android 8.1.0
Signal vers 4.25.10

**Comment by michaelkirk-signal** [comment]
Hi @MtaTech  - this is the issue tracker for Signal on iOS. It looks like you're using Signal on Android. 

Can you follow up with the Android team?

When you do, make sure you fill out the entire issue template, otherwise it's going to be hard for them to diagnose and fix your issue.

https://github.com/signalapp/Signal-Android/issues
