### ISSUE TITLE
Not possible or hard to open context menu for message when message is a link

### ISSUE THREAD

**Issue by laberkeks** [signalapp/Signal-iOS#3885]
iOS 12
Signal 2.29.2.4

Step to reproduce:
- Send somebody a short link (only one line)
- Tap the message and hold to open the context menu for messages 
=> you get only the menu to open the link, but no context menu e.g. to delete the message. Even if you tap on the border of the message

Workaround is to tab on the free space beside the message.

It would be more intuitively if it’s possible to tap the border of the message to open the context menu

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stufflesimpsons** [comment]
3885

**Comment by michaelkirk-signal** [comment]
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by muellermartin** [comment]
Should this be fixed in the current release of Signal for iOS (version 2.40.1.3)? Because I still can't open the menu for a message with a link in it, e.g. for replying, copying, details – or most importantly: deleting a message.
Regardless of where I press and hold in the message box, the menu of iOS with link actions (open, add to reading list, share, etc.) is shown instead of the aforementioned Signal menu. The workaround to click next to the message box still works, but I only learnt of this while wanting to report this issue, so this is a usability issue.
