### ISSUE TITLE
[Beta] Dark theme not available when you use iOS sharing from other apps

### ISSUE THREAD

**Issue by gakudva** [signalapp/Signal-iOS#3942]
- [x] I have searched open and closed issues for duplicates
- [x] am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Dark theme is not displayed when navigating from other iOS app

### Steps to reproduce
- Chose dark theme in Signal iOS app
- Go to photo gallery
- select a photo and click on share
- among various choices, chose Signal

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Signal starts with white theme, despite being set on dark theme

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Signal must start with selected dark theme.

### Device info
**Device**: iPhone 8 plus

**iOS version**: iOS 12

**Signal version:** 2.30.2.9

**Comment by michaelkirk-signal** [comment]
This is intentional - since share extensions are presented in the context of a bunch of different external applications, like most other apps, we also maintain a relatively generic iOS theme for the share extension.

We could revisit this, but if you'd like to discuss this further, the [community forums](https://community.signalusers.org/) would be the place to gather examples and put together a case.
