### ISSUE TITLE
Some messages are not flagged as received, while others are

### ISSUE THREAD

**Issue by tzs1** [signalapp/Signal-iOS#4062]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It happens that when sending multiple messages one after another, some messages are received by the other user, while others aren't, even if they are "between" received messages.

### Steps to reproduce
- send multiple messages to another user

**Actual result:** sometimes, a few messages are not flagged as received while others are.

**Expected result:** every message in chronological order should be flagged the same as their predecessors and successors.

### Screenshots

![___issue_github](https://user-images.githubusercontent.com/31325316/49070341-b93b8000-f22b-11e8-9ffc-b4e11c285a86.png)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.1

**Signal version:** 2.32.0.16

### Link to debug log
 https://debuglogs.org/73f07e44de643e7ed04de6485d9c3b471c52a9aeeb3103a4eaba6a78dcfabe40.zip

**Comment by michaelkirk-signal** [comment]
Thanks for the report, and for being a beta tester. We're going to need some more information to be able to pursue this.

Was this in a group thread or a 1:1?

Can you confirm if the user did in fact receive the messages or not?

Do you know if that user has a linked desktop device?

Could you ask that user to submit a debug log?

Can you send me the timestamps of the not received messages?

To get a message timestamp:

- long press on the message
- tap "more info"
- long press on the "sent field"

There's no indication, but at this point you'll have copied the timestamp onto your pasteboard. 

When you paste it should be a long number like: 1543270384266

Could you do that for both of the "not received" messages and the subsequent "received" message?

**Comment by tzs1** [comment]
>Was this in a group thread or a 1:1?

One-to-one chat.

>Can you confirm if the user did in fact receive the messages or not?

User did receive the messages.

>Do you know if that user has a linked desktop device?

Yes, user has a linked Win10 device.

>Could you ask that user to submit a debug log?

I'll ask if possible.

>Can you send me the timestamps of the not received messages?

s: 1542982724072 / r: 1542982724072 (double check)
s: 1542982736813 / r: 1542982736813 (single check)
s: 1542982745312 / r: 1542982745312 (single check)
s: 1542982754602 / r: 1542982754602 (double check)
s: 1542983713177 / r: 1542983715990 (double check)

**Comment by the-x-at** [comment]
I experienced a similar issue, just stronger. It appears to be a backward compatibility issue. My conversation partner used Signal 2.31.1.3 (stable), whereas I am using 2.32.0.21 (beta). Pretty much when @tzs1 opened this issue, I also noticed *consistent* missing of acknowledgment of receipt (only one check mark instead of two). This went on for days, so obviously the messages arrived on the other side. The very moment my conversation partner upgraded to Signal 2.31.2.0 (stable), the issue was solved. Notably, this behavior is unidirectional: During that time, I have never gotten the acks of receipt, whereas my conversation partner with the stable Signal version always got them.

### Technical details
**My device**
iPhone 5s, iOS 12.0.1, Signal 2.32.0.21 (beta)
**Conversation partner's device**
iPhone 5 or 6, iOS unknown, Signal 2.31.1.3 (stable)/2.31.2.0 (stable)

**Comment by tzs1** [comment]
This bug has not happened again for a while. Seems to be fixed.

**Comment by michaelkirk-signal** [comment]
Thanks for following up on all these issues @tzs1, if it recurs please reopen.
