### ISSUE TITLE
Text color of navigation bar remains white (dark theme) when you cancel the image sending

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4085]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Navbar text color doesn't go back to light theme if image is not sent.

### Steps to reproduce
- open a chat
- open media library and chose a picture
- click "cancel" and avoid sending that picture

**Actual result:** navbar text color is white on a white background.

**Expected result:** navbar text color is black (?) on a white background.

### Screenshots

![signal-2018-12-13-152556](https://user-images.githubusercontent.com/31325316/49945037-29185e80-feec-11e8-979b-f525367b3337.jpeg)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.1

**Signal version:** 2.33.0.9 beta

**Comment by sdsdsasad12312** [comment]
https://debuglogs.org/d17e729fd3d4679f353c5dfb5ee8880556ac0626b69cb42d06d3acbb9dd13e57.zip

**Comment by sdsdsasad12312** [comment]
I can reproduce this issue and you don't even have to go to your Photo Library and select an image to do this; by simply tapping on the attach file button (+) and then cancelling by either tapping on the cancel button or tapping anywhere outside the context menu will be enough to reproduce this issue. 

Another way to get this issue is by using 3D touch to preview your Signal conversations (only peek, do not pop).

System settings: iPhone 7 Plus, iOS 12.1.3

Signal version: 2.34.0.26

Debug logs: https://debuglogs.org/d17e729fd3d4679f353c5dfb5ee8880556ac0626b69cb42d06d3acbb9dd13e57.zip

**Comment by ftlno** [comment]
I want to fix this now, but can't reproduce it. Neither by building the master branch, nor by using the current app from AppStore(2.35.0). I'v tried on iPhone 7 Plus 12.1.2 and iPhone 8 Simulator.

Can you still reproduce it @tzs1 @sdsdsasad12312 ? I'd love to fix it today :)

**Comment by tzs1** [comment]
@ftlno seems to be fixed. I now experience a similar bug when clicking the "+" button beside text area. When clicking it, the navbar text color goes black and if you are using dark theme it will basically become invisible.

**Comment by denver-s** [comment]
This bug seems to be fixed in 3.0.0.2
