### ISSUE TITLE
CarPlay Integration 

### ISSUE THREAD

**Issue by F3000** [signalapp/Signal-iOS#4120]
Hi ,

is this feature planned in the future ? So I can send voice mails and phone calls in my car ... 

Thanks

**Comment by bconway** [comment]
Yes, this is still very relevant. My understanding is that iOS is now much more capable when it comes to on-device text-to-speech and transcription.

**Comment by Cerberus0** [comment]
Please ignore the stale bot, it does not know the difference between bugs and feature requests because [this is the wrong place to submit feature requests to begin with](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md). Please let this GitHub issue be closed and continue this discussion on the community forum:

https://community.signalusers.org/t/carplay-support/4226

Thanks!
