### ISSUE TITLE
Signal Community  IOS 12.1.2, signal version 2.33.1.0, some videos blank

### ISSUE THREAD

**Issue by trellz** [signalapp/Signal-iOS#4124]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal Community
![unnamed](https://user-images.githubusercontent.com/29633569/52180731-edd53600-279e-11e9-9a85-961c69a11dcc.jpg)

[8EC2541431B806A6D0FFF9A792F2E4B6.zip](https://github.com/signalapp/Signal-iOS/files/2825846/8EC2541431B806A6D0FFF9A792F2E4B6.zip)

IOS 12.1.2, signal version 2.33.1.0, some videos blank

### Steps to reproduce
Videos sent from some android users download, shows play button, but grey square background.

**Actual result:** opens full screen black background, no video or audio, not playback controls.

**Expected result:** Opens full screen and plays video, or plays in preview window.  Neither works.

### Screenshots

Attached screenshot, and a video that won't play.  I had them send it via allo instead of signal and it works.  It will also play from the camera roll, just not in signal.

### Device info

**Device**: iphone 8 plus

**iOS version**: 12.1.2

**Signal version:** 2.33.1.0

### Link to debug log

https://debuglogs.org/cee9d693c4249f8e32e6f29f559b6187fbffb56e6c072ccac02dc693c5c67d27.zip

**Comment by ZeFifi** [comment]
I have the same issue, but with PNG sent from a contact from the desktop app (tested from Windows). Should I open another issue?

**Comment by taw6** [comment]
I have exactly the same issue with both 5s ,6s and X phone receiving videos from Android devices. All devices are running IOS 12.1.4, it works fine when sending between two Samsung S8's. When sending videos from the 5s (iOS) to the S8 Android) it works fine.

**Comment by purpleplatypus** [comment]
I can't reproduce this behavior with the video trellz provided, could anyone else provide a test file?

**Comment by taw6** [comment]
yes, I can reproduce it, here is my test file

I made a video on my Samsung S8 and then attached it and sent it to iPhone 5s

[signal-attachment-2019-02-21-072217.zip](https://github.com/signalapp/Signal-iOS/files/2887926/signal-attachment-2019-02-21-072217.zip)

**Comment by taw6** [comment]
I get the attachment on the iPhone app, but when I play it the screen goes black and I need to restart the app or scroll up to get back to the signal application it self, if I send the same file using the Windows PC client I get the same result. I also tried the latest Update android client 2.36.0.7, see screenshots

![iphone signal app print screen](https://user-images.githubusercontent.com/47479012/53176044-8c5df580-35ed-11e9-8698-cc8f169cf19c.jpg)

![how it looks after pressing play](https://user-images.githubusercontent.com/47479012/53176521-86b4df80-35ee-11e9-9171-19180d86fafb.jpg)

**Comment by taw6** [comment]
Is anyone working on this, do you need me to test again?

**Comment by taw6** [comment]
It turns out that is only with 4k videos (i.e. resolution of 3840x2160), other resolutions work as expected

**Comment by cdenyar** [comment]
Can confirm, same issue for recipients in a group of mine (one using an iPhone, the other on a moto android.) When tapping videos sent from my pixel 2 xl they opened to a black screen. After reading the above comments, I set my camera to record in 1080p instead of 4k and those videos opened fine for all recipients. Sharing the same video via Google Photos or a link via Google Drive all recipients could again open the video file without an issue. I'm going to attempt to collect debug logs from on of the recipient devices and will post here.

**Comment by Justin12121** [comment]
Seeing this with a lot of mp4 files I share from Android with iOS users... I'm happy to share examples and logs if additional details are needed.

**Comment by topas-rec** [comment]
I have a group of about 25 people. Since corona keeps us separated, we send more and more videos. Some people are unable to open videos (one reported pictures - they look like the screenshots posted here already.

I found out that:
- all devices with this issue were IOS devices
- No Android device reported issues so far
- Videos that were unable to play on IOS were mpeg files. Videos tha played successfully on IOS were 3gpp files so far (Found out the file type by dimply downloading the video) (These files came from the same (Android) device - why do they have different file types?)

**After downloading the problematic video and uploading the downloaded video file again by an android device in that specific group, the devices that had problems with that video were able to open it.** (Important side note: the file was transformed to mp4 - again downloading it after upload revealed the file type)

That means:
Since this is a critical issue in my eyes: **A workaround seems to be (for groups with Android devices) to download and reupload the video.**

A cause might be the video format (mpeg container?).
If someone experiences this issue please post the file type here.
Perhaps make sure if other devices (Android) are also affected.
Check if the workaround works for you.

Here are the screenshots of the IOS devices. They show the video that cannot be opened. I removed personal information:

![signal-attachment-2020-05-07-153605_001](https://user-images.githubusercontent.com/20391449/81336059-edfe6880-90a8-11ea-909e-53901262d7dd.png)
![signal-attachment-2020-05-07-153605_002](https://user-images.githubusercontent.com/20391449/81336138-079fb000-90a9-11ea-9b75-fc47d2581ce2.png)
![signal-attachment-2020-05-07-153605_003](https://user-images.githubusercontent.com/20391449/81336146-0b333700-90a9-11ea-80d9-846f710228ca.png)

**Comment by topas-rec** [comment]
It seems that one android phone is affected by this. I don't write an issue on android for this too. This might be a protocol issue or something else. I think the cause should be located and then it should be moved to the right place.

Additional information: The version of the sending phone of the issues mentioned in my last comment was: 4.58.5.

**Comment by codepushr** [comment]
This is still an issue... I could provide more details, anyone working on this?

**Comment by taw6** [comment]
I believe this issue was resolved and it was related only to certain videos taken on a Samsung phone and sent to iPhone users. I have had no issues recently so in my opinion it can be closed

**Comment by ZeFifi** [comment]
No, the issue hasn't been solved. When friends send me 4K videos (from the PC desktop app), I get them blank. When the encode them to FHD, it's OK. Maybe I could provide the latest video I got if someone's interested!
