### ISSUE TITLE
Does everything look ok here?

### ISSUE THREAD

**Issue by justicesolutions2** [signalapp/Signal-iOS#4125]
I on the new iPhone  
Using 12.1.2 (16c101)
https://debuglogs.org/908025c27b75594f0d07b4a85feeadf03b5a4af47d28d52c1d66a71fd5e72d4f.zip

**Comment by michaelkirk-signal** [comment]
Hey @justicesolutions2  - we don't use Github for user support, can you follow up with support@signal.org?

Since lots of folks subscribe to the repository and are notified whenever theres traffic on an issue, we restrict Github for reporting bugs with intended behavior.

For discussions check out the community forum: https://community.signalusers.org/
