### ISSUE TITLE
I get an incoming Signal audio call, but my Apple Watch does not notify me

### ISSUE THREAD

**Issue by notDavid** [signalapp/Signal-iOS#4158]
### Bug description
I get an incoming Signal audio call, but my Apple Watch does NOT notify me

### Steps to reproduce
initiate an audio call from another device to your device

**Actual result:**
I see an incoming Signal audio call on the lockscreen of my iPhone, but my Apple Watch does not notify me

**Expected result:**
My Apple Watch displays a notification of an incoming Signal Audio call

I'm aware that Signal does not have an Apple Watch app. However, would it at least be possible to display a notification (as with text messages) of incoming audio calls ?
Please consider implementing that :)

(currently, when the mute switch on the side of the iPhone is enabled, all calls and notifications will be sent to/seen as notifications/vibrations/sounds on the Apple Watch. But not for incoming Signal audio calls...)

### Device info
**Device**: iPhone X
**iOS version**: 12.1.4
**Signal version:** 2.37.2.0

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

**Comment by fitzgerg** [comment]
In my opinion, I think I'd class this as a bug rather than a feature request. For example, my wife is an Apple Watch user. When receiving an incoming Signal call to her iPhone there is no incoming call notification mirrored to her watch, only a missed call notification when the caller hangs up. Notifications for other (non-call) Signal messages are mirrored correctly, as are normal (i.e. non-Signal) calls. It’s not a huge problem because at least she knows she’s been called and can return the call, but obviously it would be better if she could get the incoming call notification on her watch and pull her phone out of her bag to answer, as she does with non-Signal calls.
