### ISSUE TITLE
Registration Lock is not recognised

### ISSUE THREAD

**Issue by uselpa** [signalapp/Signal-iOS#4241]
- [X ] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal iOS 2.41.0.21. Using registration lock since it came out. Today 
- I got the regular reminder 
- copy/pasted the reglock from 1Password
- got an error message that the code was incorrect 
    - but was able to bypass.

Disabled the registration lock for now.

### Device info

**Device**: iPhone 8

**iOS version**: 12.4

**Signal version:** 2.41.0.21

**Comment by charlesmchen-signal** [comment]
Update to Signal to v2.41.1 in order to register. Earlier versions of Signal iOS only supported 16-digit PINs but allowed longer PINs during registration, causing a mismatch. If you wish to use a longer pin going forward, you can reset it after updating in Signal Settings > Privacy > Registration Lock.
