### ISSUE TITLE
Media error for iphone ios 13.1.3

### ISSUE THREAD

**Issue by liuem607** [signalapp/Signal-iOS#4293]
After I updated my ios to 13.1.3 on my iphone7, i can no longer send any media files(use cameras, sending pictures or videos or gifs eyc)

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by michaelkirk-signal** [comment]
Sorry that you're having trouble, but you haven't provided enough information for us to be able to pursue this.

Can you please complete the issue template? 

Least of which, we'll need a debug log right after you see this error.

And how does the error manifest? 
Does it show an error message? 
Or does it stay stuck in sending indefinitely? 
Or a crash? 
Or does someone rush through the door and slap the phone out of your hand every time you try to send media since updating?

**Comment by liuem607** [comment]
Hi, thanks for the quick follow up. 
Device: iPhone
iOS version: 13.1.3 & 13.2
signal version: 2.44.0

Issue: the app crashes and closes itself the second I tried to send a image/video/gif...., or if I try to use the camera(I mean camera inside signal app).

Attached is my debug log:
[2019.10.29 11.07.56 9BD84C70-CE9A-4906-97AA-4BB3E82EE6E4.zip](https://github.com/signalapp/Signal-iOS/files/3784254/2019.10.29.11.07.56.9BD84C70-CE9A-4906-97AA-4BB3E82EE6E4.zip)
