### ISSUE TITLE
Sharing PDF doesn't show Signal as suggested app

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4321]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes, when sharing a PDF from within an app, Signal is not one of the suggested apps.

### Steps to reproduce
- open app
- open a PDF within the app
- click the share button

**Actual result:** many messenger apps are suggested, but not Signal.

**Expected result:** Signal should be a suggested app.

### Screenshots
When clicking share button:
![image](https://user-images.githubusercontent.com/31325316/69982071-e522cd00-1533-11ea-8ecc-d4edae315d62.png)

Click on "options" and select PDF instead of "Automatic":
![image](https://user-images.githubusercontent.com/31325316/69982100-f79d0680-1533-11ea-88a1-dc2f0c7b56dc.png)

Now Signal icon appears!
![image](https://user-images.githubusercontent.com/31325316/69982135-0d123080-1534-11ea-9ed1-b31dcf5a5d81.png)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 13.2.3

**Signal version:** 3.0.2.1

**Comment by andyggg** [comment]
Dear @denver-s 
Tried to reproduce this issue on iPhone X, but Signal shows up in the list of suggested apps for sharing a PDF from Acrobat Reader. 

Did you check if Signal is enabled for sharing? In the line of your share sheet starting with the AirDrop icon, horizontally scroll to the very right, tap on the three-dots symbol, tap “edit”, and check (and enable) Signal in the list. Does that work?

**Comment by denver-s** [comment]
It occurs only on a particular app (that I can think of). I should try with more apps.

**Comment by chrische** [comment]
I am experiencing the same as @denver-s, using iOS 14.3.

In my situation I tried to share a PDF which I opened in Safari.

I am going to answer @andyggg [questions](https://github.com/signalapp/Signal-iOS/issues/4321#issuecomment-562931763), according to my situation.

Also, have you seen the small lines between the pictures explaining the workaround,  in @denver-s [ bug report](https://github.com/signalapp/Signal-iOS/issues/4321#issue-531352786)?

> Tried to reproduce this issue on iPhone X, but Signal actually shows up in the list of suggested apps for sharing a PDF from Acrobat Reader as expected. I also frequently use this feature...

What does it show for you in such case, when you click on _options_ within the sharing sheet? Is _automatic_ or _PDF_ pre-selected?
 
> Did you check if Signal is enabled for sharing? In the line of your share sheet starting with the AirDrop icon, horizontally scroll to the very right, tap on the three-dots symbol, tap “edit”, and check (and enable) Signal in the list. Does that work?

For me it does not show up to be enabled after all - in case I keep the pre-selected _automatic_ in options. Changing it to _PDF_ manually allows me to edit the enabled apps, and also shows Signal right away.
 
> Does this issue always occur? Or only under particular circumstances?

I agree with @denver-s description: Clicking on _Options_ and selecting _PDF_ instead of _ Automatic_ is a workaround for the issue. However, does not feel like a great UX. Especially due to the fact that my other messengers show up.

**Comment by ITaluone** [comment]
Trying share a PDF from Safari leads to this issue.

**Comment by moonclimber1** [comment]
Can this issue be reopened? 
I am experiencing the same problem when trying to share a pdf from safari. I have to select pdf instead of automatic for it to work, but only found out in this thread about this workaround. Before I always had to save the files in Downloads and then select it again in Signal, which is an annoying UX.

iPhone 14 on iOS iOS 16.3.1
Signal 6.36.0.10
