### ISSUE TITLE
Calls not switching over to Apple AirPods

### ISSUE THREAD

**Issue by grantwest** [signalapp/Signal-iOS#4327]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I put my charged airpods in my ears and saw that they connected and then started a Signal call and the audio was still coming out of the phone. The only thing I could do was switch between normal phone and speaker phone. Putting the airpods back in the holder and then back into my ears did not fix the problem. In the iOS Phone app you can select the audio device. If this was also possible in the Signal call interface this would have fixed my issue.

### Device info

**Device**: iPhone XS

**iOS version**: 13.1.3

**Signal version:** 2.45.2.0

**Comment by MacUserMiss** [comment]
Hello! 

Same issue over here. When I am recording voice messages on Signal the iPhone records the sound from the internal microphone and ignores the fact I am wearing my AirPods Pro. Annoying when you want to carry your phone in your purse and keep your hands warm in your winter jacket! 

Same issue described here:
https://www.reddit.com/r/signal/comments/id6nfn/using_the_mic_airpods_with_signal_voice_messages/

Is there gonna be a fix soon?

**Comment by jan-webdev** [comment]
Same problem in 2022.
Signal 5.34.1
iOS 15.4.1 on iPhone 8
AirPods Pro A2084 (4C165)
(so everything is as up to date as can be)

Even while using the Airpods, Signal will still exclusively use the iPhone‘s built-in microphone, although it uses the Airpods‘ mic for other apps without problems. And there seems to be no way to change the input mic from neither iOS nor Signal.

So I think closing this thread might have been too early, the problem seems to be unsolved.

**Comment by scannerGT** [comment]
Same problem:

- iPhone XS, iOS 16.2
- AirPods A2031 v. 5B58
- Signal 6.7
