### ISSUE TITLE
Rotating phone aborts voice message

### ISSUE THREAD

**Issue by jonas7654** [signalapp/Signal-iOS#4359]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hello, 
I don't know if it is a bug or intentional but when recording a voice message it stops recording when rotating the screen.

### Steps to reproduce
-Start recording a Voice Message without locking the recording.
-Turn your phone in order to rotate the screen.

**Actual result:** The current recording will stop.

**Expected result:** It would be great if the Signal app would turn of the screen rotation feature while recording in order to prevent the cancelling mentioned above.

### Device info

**Device**: iPhone X
**iOS version**: 13.3

**Signal version:** 3.1.1.1

### Link to debug log
https://debuglogs.org/8d6a4175c8cc8269613888514aa85bf1268a8ca8188a7a7841e9a42f18eaaccb.zip

**Comment by thegesuser** [comment]
+1. Expiriencing the same issue since the iPad App was released.

**Comment by SawkeeReemo** [comment]
Same here, on iPhone 11 Pro Max running iOS 13.3. Hopefully a fix is in the works. Also, if I'm interrupted by a call or something, instead of sending an incomplete message (like Voxer does), it just cancels the voice message.

**Comment by vjcharles** [comment]
This has been a longtime issue with Signal iOS. A workaround is to lock the orientation before recording, which is cumbersome to remember to do and unlock for other apps.
It may go without saying, but losing a recorded message can be frustrating and lead to less trust the app is able to properly handle content.

**Comment by axldd** [comment]
Having the same issue on iPhone XR (iOS 13.3.1). Already lost many 5 minutes + recordings due to that bug.

**Comment by collysucker** [comment]
I have the same issue on an iPhone 11, iPhone 7, iPhone SE (always latest iOS, currently iOS 14.3). I and others already lost many minutes of voice messages due to this bug, which is really annoying, after mostly it happens when you record long voice messages and you accidentily rotate your iPhone while doing that. This also already happend often to some friends and my family. Please fix this issue :) 👍

**Comment by major-mayer** [comment]
A friend of mine told me just today that He experienced the Same issue in signal ios multiple times, which was very annoying.

I was suprised, bc on Android this isn't a problem and IT shouldn't be one on ios too

**Comment by vjcharles** [comment]
this has been fixed by temporarily locking the screen orientation while recording audio.

**Comment by flostyen** [comment]
Yes, however: It is so frustrating when recording a voice message in signal which is 10 minutes long and you lose it completely due to accidentally clicking on abort instead of the tiny send button.

It would be awesome when a voice message is over 15 seconds long —> you get an „do you really want to abort your voice message? yes or no“ popup warning instead of immediatley losing the whole thing.

**Comment by flostyen** [comment]
You still might lose voice messages: It is so frustrating when recording a voice message in signal which is 10 minutes long and you lose it completely due to accidentally clicking on abort instead of the tiny send button.

It would be awesome when a voice message is over 15 seconds long —> you get an „do you really want to abort your voice message? yes or no“ popup warning instead of immediatley losing the whole thing.

**Comment by SawkeeReemo** [comment]
Yes! Still an issue. Please fix.

**Comment by SawkeeReemo** [comment]
As of right now it looks like the app has been changed so that while you are recording it temporarily locks your screen rotation. Now when I'm recording a message and turn my phone to the side, it stay in portrait mode and the recording continues. Elegant fix! Thank you!

iPhone 11 Pro Max
iOS 15.5
Signal v5.40.0.11

**Comment by flostyen** [comment]
You still might lose voice messages: It is so frustrating when recording a voice message in signal which is 10 minutes long and you lose it completely due to accidentally clicking on abort instead of the tiny send button.

Some friends of mine find this frustrating about signal, too.

It would be awesome when a voice message is over 15 seconds long —> you get an „do you really want to abort your voice message? yes or no“ popup warning instead of immediatley losing the whole thing.

**Comment by SawkeeReemo** [comment]
Good note... but also... 10 minute voice message?! ...please don't message me. 🤣

**Comment by tr1ng0** [comment]
This is fixed since version v5.47 see: #5404

**Comment by mogwai** [comment]
This is still an issue!

**Comment by kevinahuber** [comment]
github.com/signalapp/Signal-Android/issues/14421 <-- same issue on Android

Maybe there was a regression in a common library recently? I think the solution of Signal preventing rotation during a recording is graceful, adding an interstitial to allow for folks to choose to delete & rotate is even better. But the current state is accessibility violating- its a destructive action without a confirmation.

**Comment by mogwai** [comment]
> Maybe there was a regression in a common library recently?

Has been happening for years on iOS
