### ISSUE TITLE
Green "Return to call" Area is difficult to hit

### ISSUE THREAD

**Issue by kpcyrd** [signalapp/Signal-iOS#4364]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've noticed I'm having trouble returning to signal call frequently and blamed it on myself, but today I learned a friend also experiences the same issue, so I was wondering if this is a more common issue

### Steps to reproduce
- Start a signal call
- Use the "Back" button on the top left
- Try to tap on the green "return to call" area

**Actual result:** Returning to the call takes multiple attempts, sometimes accidentally hitting the notch or the control-panel icons instead.

**Expected result:** I return to the call on first try.

### Device info

**Device**: iPhone Xs

**iOS version**: 13.3

**Signal version:** 3.2.0.10

---

**Device**: iPhone 7

**iOS version**: 13.3

**Signal version:** 3.2.0.10

**Comment by te2dy** [comment]
Yesterday, I encountered **a similar issue by following the same steps**. Back on the conversation screen, I couldn’t find a way to get back to the call screen. When I tapped on the green zone, the conversation scrolled back to older messages instead of going back to the call screen.

Besides, it seems that **Signal considered the call to be over**. During the call, it showed me a button to call my contact back although the call was not finished, and the duration of this supposedly finished call corresponded to the currend call duration and it was updated every minute.

### Screenshot

![A screenshot of the issue](https://adextre.fr/wp-content/uploads/2020/07/signal-2020-07-27-155937.png)

It’s in French.
"_Touchez pour revenir à l’appel_" means "Tap to go back to the call".
"_Appel sortant_" means "Outgoing call".
"_16 M_" means "16 minutes" – in fact, the current call duration. This value was updated every minute.
"_Rappeler_" means "Call Again".

### Device info
**Device**: Apple iPhone SE (1st generation)
**iOS version**: 13.6
**Signal version**: 3.13.2.6 (beta)

### Debug Log
[debuglogs.org/…](https://debuglogs.org/0d450412611342cbee969b00fa9ed682cedd565c5eaf42a74463b71ec8c02b90.zip) (submitted immediately after the call)
