### ISSUE TITLE
Sharing 1Password items not working properly

### ISSUE THREAD

**Issue by notDavid** [signalapp/Signal-iOS#4368]
### Bug description
Sharing an item with 1Password via Signal results in a not working/clickable `onepassword://xxxxx` link in the message

### Steps to reproduce
- Open the 1Password app in iOS or macOS
- In any 1Password item click on the 'share' arrow and select Signal to share the 1Password item with someone
- This will result in a text message containing some text and in the end of the message an url to automatically open (add) the item in 1Password.

**Actual result:**
The `onepassword://share/1?d=xxxx` url in the text message is NOT clickable. It's just displayed as plain text and clicking/tapping it does nothing

**Expected result:**
The `onepassword://share/1?d=xxxx` url should be clickable and open the 1Password app and add the item to the 1Password database (it does work in iMessage and Whatsapp.)

### Screenshots

![Share](https://user-images.githubusercontent.com/1530401/73186368-e16c8a80-411f-11ea-979a-27a3c6418256.jpeg)

Signal:
<img width="558" alt="Signal_Desktop_v1_30_0" src="https://user-images.githubusercontent.com/1530401/73186582-47591200-4120-11ea-9bdb-948bd735ac09.png">

iMessage:
<img width="564" alt="iMessage" src="https://user-images.githubusercontent.com/1530401/73186665-6b1c5800-4120-11ea-804f-993998081c21.png">

### Device info

**Device**: iPhone X

**iOS version**: 13.3

**Signal version:** 3.2.1.0

**Comment by momenabdelkarim** [comment]
If you copy the same link from iMessage, paste it into Signal, and send to "Note to Self", is it still un-clickable? Trying to see if it's a share sheet problem or not.

**Comment by notDavid** [comment]
@momenabdelkarim Hi, yes if i copy the link from iMessage in iOS and paste it in Signal iOS it's still un-clickable.

Also, if i paste this text in iMessage:  `onepassword://test` it will become a clickable link, but if i paste it in Signal it becomes un-clickable. So you should be able to reproduce this yourself easily this way.

**Comment by momenabdelkarim** [comment]
@notDavid Okay, thanks! I don't plan on looking into it immediately, but when I'm free, if this is still a problem, I should be able to look into it.

**Comment by momenabdelkarim** [comment]
I am not 100% sure why custom links are not linkified. As part of my testing, I set the `kOWSAllowedDataDetectorTypes` and `kOWSAllowedDataDetectorTypesExceptLinks` in OWSTextView.m to `UIDataDetectorTypeAll` so everything the detector can detect in a UITextView will be detected. Doing this added support for detecting additional types such as flight numbers, but still did not add support for detecting and linkifying custom links on the UITextView side. If you look at `linkDetector` in DisplayableText.swift, the `linkDetector` does successfully find custom links and acknowledges them. 

I did not have any Objective-C experience before looking into this issue, so I can't make any conclusions with certainty. However, if I had to make an educated guess, what NSDataDetector defines as a link and what the UIDataDetectorType `UIDataDetectorTypeLink` defines as a link are different. I believe the former includes custom links in its definition of a link while the latter does not. In turn, this might just be an API limitation of how the UITextView and/or NSMutableAttributedString are implemented in Objective-C (I was able able to linkify custom URLs in Swift in my own test app).

I was hoping to find an open source app that detects and linkifies custom links so I can see how they do it but was not able to find one. As @notDavid mentioned, Apple apps and WhatsApp do. However, Telegram and Wire do not. If anyone finds an open source app that linkifies custom URLs (preferably using Objective-C), please mention the software's name here and hopefully we can find a solution by looking into their implementation.

I would like to spend more time on this but am unable to because I'll be busy with my internship soon and then school/other projects. If anyone else would like to tackle this issue, please feel free to do so.
