### ISSUE TITLE
Do not require contact access

### ISSUE THREAD

**Issue by bkazez** [signalapp/Signal-iOS#4373]
Signal works just fine without synching contacts. The nag screen when Signal has no contact access is not dismissable, which feels pushy and creepy. Would you consider adding a "No Thanks" button? Even WhatsApp lets the user get away without granting contact access.

<img width="320" alt="signal-2020-02-03-192357" src="https://user-images.githubusercontent.com/64005/73812103-7e6a9b80-4790-11ea-834a-01fd84a65a62.png">

**Comment by Cerberus0** [comment]
Hi @bkazez,

The Signal iOS app hasn't required the contacts permission [since May 2017](https://github.com/signalapp/Signal-iOS/issues/1610). Having the option to dismiss this banner is technically a feature request. As mentioned in the project's [contribution guidelines](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md), this issue tracker is only meant for bug reports and all feature requests belong on the community forum. This particular request is already being [discussed and tracked there](https://community.signalusers.org/t/can-t-get-rid-of-contact-permission-request-banner/3521). I suggest closing this issue and continuing the discussion on the forum. You can easily sign up / log in with your existing GitHub account.

**Comment by bkazez** [comment]
The community forum thread does not seem to be making any progress.  https://community.signalusers.org/t/get-rid-of-contact-permission-request-banner/3521/22

It seems like a bug to have a persistent alert - this is extremely annoying and clearly not expected behavior. Is there any other channel to try to get this addressed?

**Comment by egberts** [comment]
Still nagging.  Why is this closed?
