### ISSUE TITLE
Camera screen goes black when trying to take a photo

### ISSUE THREAD

**Issue by mauri5hut** [signalapp/Signal-iOS#4401]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic
----------------------------------------

### Bug description
When trying to take a photo out of the app, the camera screen is going black after 1-2 seconds.

### Steps to reproduce
Taking a photo within the signal app.

**Actual result:** 
Not possible to take a photo.

**Expected result:** 
Not possible to take a photo.

### Device info
**Device**: 
iPhone 11

**iOS version**: 
13.3.1

**Signal version:** 
3.5.1.0

### Link to debug log
https://debuglogs.org/0c1934c237c6614b1c7741aa724b4ba96f83c14cad0044f9014ef1e0f5a3c2bc.zip

### Snippet from debug log
2020/03/02 18:53:04:687  ❤️ [PhotoCaptureViewController.swift:513 showFailureUI(error:)]: error: Error Domain=AVFoundationErrorDomain Code=-11803 "Aufnahme fehlgeschlagen" UserInfo={NSLocalizedRecoverySuggestion=Aufnahme erneut versuchen., NSLocalizedDescription=Aufnahme fehlgeschlagen, NSUnderlyingError=0x280c2a3d0 {Error Domain=NSOSStatusErrorDomain Code=-16409 "(null)"}}
2020/03/02 18:53:12:178  ❤️ [PhotoCaptureViewController.swift:513 showFailureUI(error:)]: error: initializationFailed
2020/03/02 18:53:21:919  🧡 [AppDelegate.m:756 -[AppDelegate applicationWillResignActive:]]: applicationWillResignActive.

**Comment by philbert** [comment]
I have been seeing the same issue for a while. Same version of iOS. Same version of Signal.

The error persists even after terminating the Signal app and occurs in all conversations.

Restarting the phone fixes it.

Attached is a screenshot:
![IMG_1848](https://user-images.githubusercontent.com/5618563/76152694-c13ace80-60c2-11ea-97ca-8a54f52287ea.jpeg)

Also, perhaps unrelated, when I tried to ```Submit Debug Log``` I received another error saying "Could not upload logs." This error persists after restart however.
![IMG_1847](https://user-images.githubusercontent.com/5618563/76152778-fdbafa00-60c3-11ea-8255-7df3499f72cb.jpeg)

**Comment by mauri5hut** [comment]
This issue seeems to be fixed with version 3.6.1.4 :)

**Comment by michaelkirk-signal** [comment]
> This issue seeems to be fixed with version 3.6.1.4 :)

I'm glad to hear things are working for you - but we've made no relevant changes that would have fixed it from our end. Did you perhaps update iOS in the meanwhile?

Keep a lookout! 👀

**Comment by mauri5hut** [comment]
The problem is back :( 
Don't know, why it was temporary gone...

**Comment by midnightmagic** [comment]
iOS 13.3.1
Older model iphone. Also an issue here.. restarting entire phone via powerdown fixes it for a short time only.

**Comment by elguaposghost** [comment]
I have the same issue and just noticed the issue this morning. I am running iOS 13.4 and Signal Beta 3.7.1.0.

**Comment by chrisdavies76** [comment]
same issue here on iphone XS and signal version 3.8.3.5. Restart phone has fixed but sounds like this will be temporary?

**Comment by guimspace** [comment]
https://debuglogs.org/02d88d4ff0ea7188830197d7c5f436c3dc6ece447e9c749a5b76e9a4220bc49c.zip

**Comment by philbert** [comment]
I hit this issue again and have a few more details about how the bug occurs. 
I'm running iOS 13.6.1. Signal version is 3.14.2.2. Phone is an XS Max.

A little background: 
I'm a regular signal user and the app is always running in the backgound on my phone.
My phone had been on for at least a week or two since the last time I restarted it.

Scenario:
- I was listening to an audible audiobook via bluethooth on my Airpod Pros. 
- I clicked on the Signal app to send a message 
- I clicked the photo button and the picture displayed for about half a second then the screen went black **and** the audiobook stopped playing
- The play/pause button in the audible app did not appear "paused", but the time of the book had stopped ticking. 
- I had to push the play/pause button twice for the audio to start playing again. (i.e. pause first and then play.)
- I started listening to the audiobook again via bluetooth on my Airpod pros.
- I want back to the signal app and tried to take another photo and again the screen went black after half a second and the audio stopped playing in exactly the same way as the first time.

The behavior of the app was now as described in this issue. I restarted the app and the photo screen would go back after half a second. Even when not listening to audio, the behaviour was the same. 

I restarted my phone to fix the issue in signal and tried to reproduce the scenario described above. Unfortunately it did not occur again are the restart.

Logs are uploaded and sent to you separately in an email.

**Comment by dustin-ob** [comment]
Hey team, I'm introducing this app to some family members in an effort to get away from WhatsApp but this video problem has popped up. Anything you need to diagnose? Happy to help if I can. Cheers! 🙏

**Comment by flodaho** [comment]
Hi, 

i See this issue again with the following config: 

- iPhone 16 Pro
- iOS 18.5
- Signal 7.66 (860)
- language is German

I press the photo button in a chat and the preview shows a black screen. After taking a photo the error "Ein unerwarteter Fehler ist aufgetreten" and the button "Verwerfen". ("unexpected error occurred" and "dismiss").

Should I open a new issue or will this be re-opened? Or is it even not a signal issue or solved? 

Thanks, 
  Florian

edit: 
restarting the phone helps for a couple of days, then the issue is back. I also reinstalled the app, directly facing the issue again. 

<img width="336" height="728" alt="Image" src="https://github.com/user-attachments/assets/f6731cd7-cb64-4082-9bce-440554d0ca32" />

**Comment by sashaweiss-signal** [comment]
Hi @flodaho, thanks for reporting.

We've noticed an uptick in reports of this, which is weird as we haven't changed anything here recently. Please feel free to open a new Github Issue for this, although we are also tracking it internally.

Debug logs are always helpful, too. Thanks again for reporting, and as always for being a Signal user!
