### ISSUE TITLE
Messages' time shown incorrectly when communication with person in different timezone

### ISSUE THREAD

**Issue by mssksg** [signalapp/Signal-iOS#4446]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Communication with someone from a different time zone, their messages' time seems to be displayed as if they were in their timezone, but mine are in mine, but the overall order of messages is correct in the chat...
Not 100% sure if it is related to that, but its what I assume...

### Steps to reproduce (my assumption)
- send a message to someone residing in a different time zone
- receive reply
- write again
- see that it says "my message: Fr. 20:00; other: Fr. 17.05; my: Fr. 20.30; other: Fr. 17.35" (in this case the other is in a time zone behind me...

**Actual result:**
Times are displayed incorrectly.

**Expected result:**
Times should be displayed according to my time zone, so when the message arrived for me from my perspective...

### Screenshots

![IMG_D23DB3CFB04C-1](https://user-images.githubusercontent.com/42465320/80788958-e7dd2900-8b8a-11ea-923a-cbbb65b6368b.jpeg)

### Device info

**Device**: iPhone 7

**iOS version**: 13.4.1

**Signal version:** 3.6.1.4

### Link to debug log

Since there is no actualy crash happening, no crash log...

**Comment by johnnyw** [comment]
Looks like the text gets set from a call to `[DateUtil formatMessageTimestamp:]` where the argument is a Unix timestamp that comes straight from the backend. This might be a bug (or feature?) of the service itself rather than an iOS client bug. Have you checked timestamps for clients on other platforms?

**Comment by cacaosteve** [comment]
It seems like the timestamp is being generated from whichever device sends the message. So you'd have to ask your friends to all set their devices to the right time zone, not just set the time with the clock.

It seems like part of a larger issue that you can just set the date backwards on the sending device and have the messages be from last July at 11:11 AM if you wanted.

I'm not sure that's something that's enforceable since it's end to end encrypted.
