### ISSUE TITLE
Can't reply with sticker

### ISSUE THREAD

**Issue by benlevy0** [signalapp/Signal-iOS#4451]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When swiping to reply to a message and then sending a sticker, it sends the sticker normally--and not as a reply message.

### Steps to reproduce
- Swipe right on message to reply
- Click the sticker button
- Select a sticker and send it

**Actual result:**
The sticker sends as a normal message

**Expected result:**
The sticker should show as a reply to the swiped-on message

### Device info
**Device**: iPhone X

**iOS version**: 13.3.1

**Signal version:** 3.8.3

**Comment by u32i64** [comment]
It was an [intentional choice](https://community.signalusers.org/t/10643/11?u=u32i64) by the developers to disallow replying with a sticker. The feature request to allow that is tracked on the community forum [here](https://community.signalusers.org/t/send-stickers-as-a-reply-to-a-quoted-message/12919?u=u32i64).
