### ISSUE TITLE
Crash when taking photos.

### ISSUE THREAD

**Issue by seba31000** [signalapp/Signal-iOS#4479]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

I have actually never had the chance to test it before. Today I tried to send a picture to a contact via the camera icon. I see the landscape I want to take but when I click the picture button the app crashes. I tried to send a photo from the album and it works properly.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

1-open the app
2-click on a contact
3-click on the camera icon
4-take a picture
5-app crashes and closes

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

5-app crashes and closes. User is send back to Apple app mosaic.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

6-the app should suggest the picture and some options such as time it is available at receiver phone, blur or crop...

### Screenshots

I can’t send a screenshot as the app closes.

### Device info

**Device**: iDevice IphoneX

**iOS version**: 12.3.1

**Signal version:** 3.10.3.7

### Link to debug log

https://debuglogs.org/d77117a9c515154228b05ebf84497dd6e1bd255156d0a388302d34ecb3b25788.zip

**Comment by wark88** [comment]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In app camera crashes ios app

### Steps to reproduce
- open signal app
- go to any screen to take a pic (main screen,message sccreen...)
- tap take pic button
- app crashes and go back to phone home screen

**Actual result:** app crashes 

**Expected result:** app takes pic and then able to send it without accessing ios photos.. 

### Screenshots
Cant take a screenshot of a closed app.. 

Have been sending bug reports via in app reporting for last few months.. havent heard anything.... been plenty of updates since this first started.. nothing fixed.. 

### Device info

**Device:** apple a1661
**ios version:** 11.0.1
**Signal version:** 3.12.2.4 (7/2/2020) 

 
### Link to debug log


https://debuglogs.org/424a9f581ce0eeea037ebcf7b447fa75efbe9c6a3c73deed52fc599534b1736b.zip

**Comment by wark88** [comment]
No update on this?? Got to love the lack of customer service... hasnt worked for months.. still plenty of "updates" with no fixes.......

**Comment by seba31000** [comment]
No i haven’t seen any changes. I’m running the latest version and it’s still the same. I haven’t seen any particular changes in the last versions.

**Comment by seba31000** [comment]
Just updated to the latest iOS version. Still the same the app crashes when I take picture. When will this issue be solved ?

**Comment by IsaiahJTurner** [comment]
Still not fixed

**Comment by ShingZhanho** [comment]
The bug still exists even in 2021.

**Comment by savagekevin** [comment]
same for me, are we the only ones this is happening to?

**Comment by savagekevin** [comment]
isnt this same as old 4318?

**Comment by jennazhou** [comment]
Same for me with iPhone 7+. Really annoying. App crashes whenever I try sending a pic from the gallery or taking a pic.

**Comment by AchimH** [comment]
Solution:

Resetting the **location and privacy** settings under **iOS Settings, General Reset** worked for me. That won't erase anything, just every app will ask for their permissions again.


Source: https://www.reddit.com/r/signal/comments/idebne/issues_with_sharing_to_signal_on_ios/

**Comment by Dkendal** [comment]
> Solution:
> 
> Resetting the **location and privacy** settings under **iOS Settings, General Reset** worked for me. That won't erase anything, just every app will ask for their permissions again.
> 
> Source: https://www.reddit.com/r/signal/comments/idebne/issues_with_sharing_to_signal_on_ios/

I’ve been having this issue for about a year, this also fixed it so thank you very much. 

My theory is that I have it access to photos and then it started to crash after I added a good photos account.

**Comment by Dkendal** [comment]
I spoke too soon, it started to crash again after I resumed the app. I can still send photos by sharing them from photos first.
