### ISSUE TITLE
Very bad video call quality from iPhone 11

### ISSUE THREAD

**Issue by msavara** [signalapp/Signal-iOS#4484]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have two devices, iPhone 11 with latest OS and Signal version, and Xiaomi Pocophone F1 with Android 10, also latest Signal app version. Both devices have 12mpx back camera. Lenses are clean and i made this on local wifi.Configuration “Always relay calls” is disabled. Part in left side is video from iPhone and it’s showing in Pocophone F1, on the right side is iPhone and video is from phone from left side. And as you can see, it’s like bad blurry video quality from iPhone. Why that difference ? It doesn’t matter if i used front or back camera,if i’m on wifi or lte, everytime is video from Xiaomi pocophone F1 better. I’m a little bit disappointed. Meanwhile i tried it from other Android phones ( Samsung Galaxy S20,Xiaomi Note 10 ) and results are same.

### Screenshots
![f01c3e0cdeedb53d7d9215d579d4fa3407e53098](https://user-images.githubusercontent.com/34938369/84628646-567f0780-aee9-11ea-847c-f402c1b8074c.jpeg)

### Device info
**Device**: iPhone 11
**Second Device**: Xiaomi Pocophone F1

**iOS version**: 13.5.1
**Android version** : 10

**Signal version:** 3.10.5.3

**Comment by msavara** [comment]
Sorry but nothing ? Without any reaction or something ?

**Comment by iHarryme** [comment]
I can confirm the same. It’s there even now. I tried video calling between iPhone 11 and Samsung J7, both are with me side by side connected to the same wifi. Samsung’s phone video showing on iPhone is great (in fact it amazed me by the detail of the video) while the video from iPhone which is shown on Samsung phone is blurry. While taking pics inside Signal app, the pictures on iPhone 11 are crispier than that of Samsung J7 (behavior as expected). SO, that means the problem is with video calling and not the camera. Signal devs, look into it please.
Here is the debug log of J7 (signal Version 4.65.2):
https://debuglogs.org/569ec7f338a24b5bade5ac7f3697c1ad5ba4c3ed2661dd2f14bb3263a21a9003
Here is the debug log of iPhone 11 (signal version 3.12.1.3):
https://debuglogs.org/7da035721a338efd781704e3f816ebfff1956514251fd1a197f194e629805237.zip

**Comment by msavara** [comment]
Why the hell is this closed? It's still relevant!

**Comment by alexbhandari** [comment]
Agreed this seems to still be an issue. I am also having issues with video quality coming from iPhones in signal today. Quality in general I can see is worse than in whatsapp. Additionally I have observed that when there is motion in the video the frame rate is extremely slow and quality is very bad.

**Comment by msavara** [comment]
I hope this somehow attracts the attention of Signal creators. I also shared it on twitter.

**Comment by wtangofoxtrot** [comment]
This is still a major issue and the reason ive stopped using signal for calls, I cant even call people on the same local wifi without 2010 level video quality whereas facetime is crystal clear even when calling the other side of the world.

**Comment by marekop** [comment]
Absolutely agree, few minutes ago I compared 2 live videos on Samsung S22/S22 Ultra from signal app and whatsapp application and seem I'll drop Signal in favor to whatsapp :(

**Comment by msavara** [comment]
This bug is still relevant. Instead of solving 2-3 y old bugs you are making "Stories" feature... omg
