### ISSUE TITLE
Strange order of chats

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4502]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I don’t understand the logic behind the ordering of chat list. Some of them are empty, others have a message timer set in the past.

### Steps to reproduce
- have some empty chats and other with disappearing messages timer set

**Actual result:** order is unusual.

**Expected result:** chats should be ordered by a visible time stamp of the last interaction.

### Screenshots

![E65B1171-09FE-41DD-A6F7-1F92ADB2020C](https://user-images.githubusercontent.com/31325316/87221745-ae851e80-c36e-11ea-9e26-28d4e16b8272.png)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 13.5.1

**Signal version:** 3.13.0.13

**Comment by u32i64** [comment]
Made an interesting observation that I think is related:

Deleting the last message (including system messages/alerts) in a conversation places the conversation below all others (but above empty ones) in the conversations list. (In my case the expected behavior was for the conversation to stay at the top, because of other recent messages in it.)

**Device:** iPhone SE (1st gen)
**iOS version:** 14.0 (18A5342e)
**Signal version:** 3.15.0.12

**Comment by denver-s** [comment]
It seems that now this bug has been fixed.
