### ISSUE TITLE
iOS Disappearing Messages timer starts when message is sent, not seen

### ISSUE THREAD

**Issue by DonDu2** [signalapp/Signal-iOS#4521]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Timer for disappearing messages startes right after beingt sent, before the message has been seen.

### Steps to reproduce
- Enable disappearing messages
- Send message

**Actual result:** Message is sent, timer is ticking.

**Expected result:** Message was seen, timer starts ticking.

### Screenshots
![InkedScreenshot 2020-08-12 at 11 01 23_LI](https://user-images.githubusercontent.com/69577960/89996879-a7ae3c00-dc8b-11ea-82f9-47a19ea1bceb.jpg)

### Device info

**Device**: iPhone 11 Pro Max

**iOS version**: 13.6

**Signal version:** 3.13.3.10

**Comment by Imperiopolis-Signal** [comment]
You sent the message, so you have by definition seen it so we start the timer immediately.

**Comment by DonDu2** [comment]
Ok so that feature has become absolutely useless then. What sense does it make to start the time from the moment I, as the creator, saw the message? It obviously makes only sense to start the timer when 1+ recipient have seen the message.

**Comment by Imperiopolis-Signal** [comment]
I think you misunderstand how disappearing messages work. The message does not disappear at the exact same time on your device and the receivers device. An independent countdown starts for each participant after that participant reads the message. So if Alice has a 5s disappearing timer setup and sends a message to Bob, the message will disappear in exactly 5s on Alice’s device because she has seen it. But for Bob, the 5s countdown will not start until he reads the message.

**Comment by DonDu2** [comment]
Ah yes, I didn‘t understand that. I thought the timer was somehow synchronized.
Thank you very much for the explanation 🙏☺️

**Comment by Imperiopolis-Signal** [comment]
No problem!
