### ISSUE TITLE
Unknown Database version, please update (send protocol)

### ISSUE THREAD

**Issue by thierryzoller** [signalapp/Signal-iOS#4527]
After the recent update I get the following error when starting Signal
"Unknown Database version, please update (send protocol)"

**Comment by thierryzoller** [comment]
I am wondering what to do next?

**Comment by michelle-signal** [comment]
I'm not familiar with this error "send protocol". I don't even see this string anywhere in our project.

We do have a similar looking error message...
Title: Unknown Database Version.
Message: Please upgrade to the latest version of Signal.

Is this what you're seeing? You might see this error if you ever downgrade Signal. This could happen if you're running the version in TestFlight, then install the version in the App Store. The TestFlight version could have made changes to the database that the older version doesn't recognize.

To fix this, make sure you never downgrade Signal. If you install the latest version that you've ever run in the past, things should work normally. If that doesn't work, please take a screenshot of the error you're seeing and reply here.

**Comment by thierryzoller** [comment]
You closed this too early. I had to Google what Flight Test is. I am normal enduser. I updated Signal and as a result could no longer use it, this error message appeared. It might not have said "send logs" but something similar "Send diagnostics..".  

So how should users like myself react to this error message ? I have cleary not "downgraded" as I have no clue how to even do that.

**Comment by thierryzoller** [comment]
Users that have the same issue. Here is how I solved it. I uninstalled Signal and re-installed it. I asked me for credentials and populated old contacts againt.

**Comment by michelle-signal** [comment]
I apologize for assuming you were a TestFlight user. This error can be very easily hit by users that have run multiple different versions of Signal. But, if you've never run a Signal beta build, and have only run versions downloaded directly from the App Store, that's more concerning.

It sounds like you're hitting an issue with database migration. Debug logs are really helpful in tracking this sort of thing down. It sounds like you did collect logs, but currently the Github issue flow within Signal requires users to manually paste their logs into the issue draft. Without the log URL, we don't have very much actionable info here.

If you happen to have the log URL saved somewhere, it'd be really helpful in tracking this down. If you can reply back with it, we can re-open this issue and investigate what happened. If you don't, that's okay. It sounds like you're no longer hitting the issue. But if you run into this again, please provide debug logs so we can get more info on the root cause. Thanks!

**Comment by chulander** [comment]
i was using signal earlier today and 4 hours later, opened it to see the "unknown database error, please upgrade"

i'm using iOS and maybe there was some auto update? 

uninstalling and reinstalling the app works.

**Comment by TurbanSingh** [comment]
https://debuglogs.org/94de870b1bf34c7f8058b578b53b6f7ff1e967ca262b704cf2f27f1e6c304881.zip

**Comment by busucu** [comment]
Ran into this today. Is there any way I can fix this without losing the chat history and media?
