### ISSUE TITLE
"Transfer from iOS Device" does not survive interruptions

### ISSUE THREAD

**Issue by mstange** [signalapp/Signal-iOS#4529]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When transferring message history data to a new iPhone, it is easy to interrupt the transfer. This causes grief because restarting the transfer is expensive: the transfer takes a long time, and it requires an activation SMS on the new iPhone every time, and that SMS is rate limited.

For example, the following actions on the "source" iPhone irrevocably abort the transfer:

 - Switching apps
 - Locking the screen, including automatic screen lock after timeout
 - Device temperature warnings

It would be great if the transfer could continue after these actions.

### Device info

**Device**: iPhone 6S

**iOS version**: 13.5.1

**Signal version:** 3.14.2.2

**Comment by Joebortscheller** [comment]
Why

**Comment by michelle-signal** [comment]
Device transfer currently uses Apple's [Multipeer Connectivity framework](https://developer.apple.com/documentation/multipeerconnectivity?language=objc) to transfer data. A limitation with this framework is it only works correctly while the app is foreground:

> If the app moves into the background, the framework stops advertising and browsing and disconnects any open sessions.

Because of this restriction, device transfer currently requires that the app remains foreground until it completes.
