### ISSUE TITLE
iOS Call Intergration Issues

### ISSUE THREAD

**Issue by devagent42** [signalapp/Signal-iOS#4538]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Incoming calls don't ring or integrate with the iOS call integration "swipe to answer". Incoming calls also don't play a ringtone, just vibrate. 

### Steps to reproduce
- receive a Signal call on the latest iOS and Signal app.

**Actual result:** No iOS call integration ("swipe to answer"), no ringing, only vibrate

**Expected result:** A "swipe to answer" should be displayed when a Signal call is being received. A ringtone should be played.  

### Device info

**Device**: iPhone 11 Pro Max

**iOS version**: 13.6.1
**Signal version:** 3.15.0.23

**Comment by Imperiopolis-Signal** [comment]
Was this an incoming video call or audio call? Video calls do not integrate with the iOS ringer by design, because Apple does not provide good support for video calling. Regardless, if your phone is not silenced it should ring. Also, please attach logs if you want us to look at this farther – there's not much we can do without that

**Comment by devagent42** [comment]
> Was this an incoming video call or audio call? Video calls do not integrate with the iOS ringer by design, because Apple does not provide good support for video calling. Regardless, if your phone is not silenced it should ring. Also, please attach logs if you want us to look at this farther – there's not much we can do without that

This was a video call... Does this have something to do with the video call option now being separate from the audio call function? Video calls used to trigger the "signal audio" and swipe to answer, but I guess I was doing a "audio" call and then enabling video during the call... I'll try it with a audio call and see if it rings tomorrow. I'll report back.

**Comment by Imperiopolis-Signal** [comment]
> Does this have something to do with the video call option now being separate from the audio call function?

Yes. When you call someone with a video call, they receive a persistent notification of a video call that gives them the option to answer with video or audio only. Apple doesn't provide any way for third party apps to do this (even though facetime does) so you're stuck either posting a notification and playing sound / vibration (what we're doing), showing the audio "ringing" screen and turning on the camera automatically when you answer a video call (since the other person generally expects video to be in both directions, but this can also be surprising for the person answering), or ringing everything through as an audio call and leaving you to turn on video later (a lot of people don't notice it's even a video call in this scenario, because you have to open the app after answering). 

We chose to go with the notification option, because it feels like the least bad of a set of bad options. In an ideal world, Apple would open up the ability to ring an incoming video call and make it clear to the recipient that it's a video call.

**Comment by devagent42** [comment]
Thank you for the reply. I see what you mean, and receiving an audio call does the "swipe to answer" in my iPhone. I'll close this issue.
