### ISSUE TITLE
Links in forwarded messages not clickable

### ISSUE THREAD

**Issue by chris-gillatt** [signalapp/Signal-iOS#4549]
### Bug description
When you forward a message containing a URL link to the same chat when you try and click the link you are forwarded to the original message, it does not open the URL in a browser.

### Steps to reproduce
- Start a group chat
- Send a URL link in a message
- Send some other messages
- Forward the message containing the URL link to the same chat
- Tap the link in the forwarded message

**Actual result:** User is returned to the original message in the chat

**Expected result:** Tap opens the URL in the default browser

**Comment by michelle-signal** [comment]
Hi Chris, thanks for the info. I'm a little unclear what you're referring to. Are you talking about quoted messages or forwarded messages?

Quoted messages 
<img src="https://user-images.githubusercontent.com/66273351/92666970-8eff6900-f2bf-11ea-96e1-92f77fdeace0.PNG" width="200">
<img src="https://user-images.githubusercontent.com/66273351/92666980-91fa5980-f2bf-11ea-9424-619f656c6d6d.PNG" width="200">

Forwarding a message
<img src="https://user-images.githubusercontent.com/66273351/92667049-c3732500-f2bf-11ea-8f28-4131943445b3.PNG" width="200">

In either case, the behavior in each is expected behavior. 
- Quoted messages always take you to the original message when tapped. This is so you can see the context of the original message. Once scrolled to the original message, you should be able to tap on the original URL.
- When forwarding a message, the presented view is actually an editable text field. This gives the user the opportunity to edit the message before it's forwarded. We usually don't render URLs as tappable targets if they're in an editable text field. Once sent, it should become tappable.

For now, I'm going to close the issue. But if I was mistaken and you were talking about something else, please feel free to reply back and I'll reopen the issue.

If you disagree with the existing behavior, I'd suggest reaching out on the [community forums](https://community.signalusers.org/). That's generally the right place to discuss feature requests. Github issues are reserved for bugs.
