### ISSUE TITLE
Hard crash in iOS (latest version)

### ISSUE THREAD

**Issue by misterakko** [signalapp/Signal-iOS#4551]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when trying to read a discussion

### Steps to reproduce
- I open Signal because I see the red badge on the icon, telling me I have an unread message
- I tap on the conversation icon
- It crashes

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
I am back to the springboard

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Are we really doing this? I expect to see the message for me...

### Device info

**Device**: iPhone 11

**iOS version**: 13.7

**Signal version:** 3.16

### Link to debug log
https://debuglogs.org/55ff277605ba803cfc9b511eba28a9e033f97ccf051706c02bb4b99a1e2d1962.zip

**Comment by michelle-signal** [comment]
I'm sorry you're seeing this crash. Would you be able to grab the crash log for me?

This information can be found in iOS Settings > Privacy > Analytics > Analytics Data. There should be some entries there that start with "Signal". If you tap them, you can tap the share button in the top right to move them off your phone.

Once you have them, please paste them here. Thanks!

**Comment by misterakko** [comment]
Here you go

**Comment by michelle-signal** [comment]
Hmm, I don't think it attached. Could you try re-attaching directly in the Github UI?

**Comment by misterakko** [comment]
[Archivio.zip](https://github.com/signalapp/Signal-iOS/files/5216593/Archivio.zip)

**Comment by Judx** [comment]
I encountered similar issue today.

# Device info
Device: iPhone 11 Pro
iOS version: 13.6.1
Signal version: 3.16 and 3.17

# Link to debug log
No log is generated from the crash.
Can not submit logs via app either.

# Bug description
It seems like the iOS app suddenly can not sync. Opening the app crashes it after ~5 seconds. Desktop version works fine. No messages are synced. Can not change settings.

I am part of a group chat where every iOS user is having crashes and can not use the app. It happened after iOS group member was trying to send a message. Suddenly the app crashed. The user tried to fix and in the end reinstalled. The user is no longer having crashes. Ever since the reinstall no other iOS member of that group has been able to use the app. Android users have no problems.

It seems reinstalling the app fixes this and the crashes are no more. But unfortunately the chat history is lost.

# I have tried
- Updating the app from 3.16 to 3.17
- Restarting device
- Using with and without wifi
