### ISSUE TITLE
Vibration options in iOS 

### ISSUE THREAD

**Issue by tolgagoren** [signalapp/Signal-iOS#4574]
Vibration options are not exposed for iOS notifications. In other apps a vibration can be selected and even customized in the iOS notifications menu. I believe this is just a flag that has to be enabled. For signal it just shows “sound”.
I believe that the lack of notifications on Apple Watch (issues 4329, 4522) are related to this.
Would help some people get off iMessage!
Thanks!

**Comment by delreluca** [comment]
I might be wrong but I think only special apps (like iMessage, Calendar, etc.) get the vibration options in the system notification settings.

However, other messengers like Threema allow you to toggle sound and vibration separately in the app itself. I'd really appreciate such a setting in order to make Signal vibrate-only even when the ringer is on. I think right now that is only possible by choosing a custom ringtone that is silent.

**Comment by opensource21** [comment]
Still relevant. It is Theo First time im frustrated about Signal. I can pay but notification is really bad😢

**Comment by opensource21** [comment]
Still relevant. It is the first time im frustrated about Signal. Some chats are not so important to play a sound but important enough to create a vibration.

**Comment by delreluca** [comment]
still relevant

**Comment by delreluca** [comment]
Still relevant

**Comment by qnpnpmqppnp** [comment]
Still relevant indeed. It's really weird to have no on/off toggle for vibration.

**Comment by EvanHahn-Signal** [comment]
We're trying to use GitHub for bug reports and [the community forums](https://community.signalusers.org/c/feature-requests/17) for feature requests. Please open a thread there (or find an existing one).
