### ISSUE TITLE
Signal does not work without mobile data set to on

### ISSUE THREAD

**Issue by xectis** [signalapp/Signal-iOS#4600]
What's the point of using Signal when it requires mobile data to work with encrypted messages. Basically I cannot use it as a normal sms app so it's a major deal breaker.

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Genis-Sage** [comment]
hey @xectis 

could you please fill out the issue template, instead of simply adding some text above the template

my questions to better understand your problem:
1) are you using an iOS device or an Android device?
(we are in the iOS issue tracker, but as you did not state, what device you are using, it also can be the wrong issue tracker)
if you are using an android device, please close this issue here, and open an issue here: https://github.com/signalapp/Signal-Android/issues 

2) does Signal work when Wifi is connected?

3) If you are on iOS, it is not possioble to use any other app for SMS as the original iOS app, as Apple does offer APIs for receiving SMS
