### ISSUE TITLE
Failed to create directory

### ISSUE THREAD

**Issue by risakov** [signalapp/Signal-iOS#4619]
Hello, I have the trouble! Please help me someone.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to create directory: /transfer, error: Error Domain=NSCocoaErrorDomain Code=513 "ERR513.DFV" UserInfo={NSFilePath=/transfer, NSUnderlyingError=0x282339a70 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}'
terminating with uncaught exception of type NSException

Look at this picture please
![image](https://user-images.githubusercontent.com/45292536/98703662-c906ed00-238c-11eb-8032-0db17c6e13f6.png)

What should I do?

**Comment by Imperiopolis-Signal** [comment]
We don’t provide development support in github issues, you can ask a question on our [community forums](https://community.signalusers.org).

**Comment by nvkhiem2016** [comment]
On the Capabilities tab, turn off Push Notifications and Data Protection,
while keeping Background Modes on. The App Groups capability will need to
remain on in order to access the shared data storage. The App ID needs to
match the `applicationGroup` string set (both Production and Staging) in TSConstants.swift.
