### ISSUE TITLE
Full resolution image sending

### ISSUE THREAD

**Issue by mlindner** [signalapp/Signal-iOS#4639]
I've noticed that Signal completely ruins the quality of images and does not send them uncompressed. iMessage manages to send full resolution images so Signal should as well. Please fix this and allow full resolution sending of images.

**Comment by Genis-Sage** [comment]
Hey @mlindner 
As this is more of a feature request than a bug report, while github is reserved for issues, you should check the community forum at community.signalusers.org

But also:
You should try to add the picture you want to send as attachments instead of as picture
Then it is handled differently
