### ISSUE TITLE
GIFs from Android -> iOS do not appear

### ISSUE THREAD

**Issue by coreyb42** [signalapp/Signal-iOS#4641]
### Bug description
Custom GIFs sent from Android to iOS do not function. The same GIFs are visible on desktop and other Android devices. Can't be sure if it's an iOS or Android issue. GIFs sent from desktop -> iOS work, and GIFs sent from iOS via GIPHY seem to work. GIFs sent from Android but uploaded via GIPHY work.

### Steps to reproduce
- create or download a custom GIF (not GIPHY, which does work) to an Android device
- send the GIF to a Signal chat
- observe that the GIF does not work on iOS

**Actual result:** A gray placeholder appears where the GIF should be playing

**Expected result:** The GIF should appear and play

### Screenshots

![60B6D194-5022-4C5D-A466-AC317A321C21_1_105_c](https://user-images.githubusercontent.com/8770962/100744984-9f9a1980-33ac-11eb-9fce-8d8d76b44646.jpeg)
![B51AD675-C17D-47BB-BB81-FD39F7E9074F](https://user-images.githubusercontent.com/8770962/100744996-a2950a00-33ac-11eb-8b10-32ba5d69a6a0.png)

### Device info

**Device**: iPhone 12 Max Pro (and other iOS devices including an iPad Pro and another family member's older iOS device)

**iOS version**: 14.2.1

**Signal version:** 3.22.0.8

**Comment by Genis-Sage** [comment]
hey @coreyb42 
sorry if this question sounds rude or stupid:
are you sure, you are sending GIF files, and not animated webp or webm?

can you post one of the affected files here?

**Comment by coreyb42** [comment]
Hi @Genis-Sage - not a rude question at all (you wouldn't know from my Github, but I'm a professional developer). Apologies for the delay - the original gif was of a child and I didn't want to share that here.

Attached is a sample GIF (confirmed it behaves the same) and my debug log from when it was sent. The file does seem to be a GIF, judging by the extension and the fact that nothing complains about it. It was created on Android using the Google Photos app, where my friend "clicked + to create animation".

![signal-2020-12-10-120357](https://user-images.githubusercontent.com/8770962/101804773-f3f57580-3adf-11eb-9968-ad19f7c4cc1c.gif)

[a4fe219ed4c5a5e2b695b38e60a1ec971c3e0a78417a1904a0d7888dd9949e77.zip](https://github.com/signalapp/Signal-iOS/files/5674498/a4fe219ed4c5a5e2b695b38e60a1ec971c3e0a78417a1904a0d7888dd9949e77.zip)

**Comment by Genis-Sage** [comment]
hey @coreyb42 
you can believe me or not
I work in customer support

so what I am doing here in my freetime is the same as in my job


what happens, if you save the customer GIF on your desktop, and then send it again? does it then work on the iPhone
(or is this already what you meant, when you said GIFs sent from desktop work)

Can you send the custom GIFs via another messenger, email, etc?

Just to understand, if this is an issue of Signal or perhaps of the GIFs created by Google Photos?

**Comment by coreyb42** [comment]
@Genis-Sage - I believe you, and that's funny. Not surprising, with your kind approach.

I ran some tests:

* sent from my desktop, the same GIF is still gray in iOS Signal
* the GIF is visible in my Spark email client when I send it to myself
* the GIF is visible in the messages app when my friend sent it via regular text message

So it appears that it is iOS-Signal-specific with the GIF not displaying.

**Comment by fumiakiy** [comment]
Signal iOS does not display the gif above because the size of the data is larger than the number that the app sets limit to.

[The lines of the code that determines that the gif is not a "valid media"](https://github.com/signalapp/Signal-iOS/blob/master/SignalServiceKit/src/Util/NSData%2BImage.m#L169-L173) are checking if the animated image is within the size of 4x1024x1024 = 4194304 bytes and it is too large according to the code because the size of the gif is 1119*1492*4 = 6678192 bytes.

1119 x 1492 is not too large if it was a still image but [the app restricts the dimension of the *animated* pretty small in the code here](https://github.com/signalapp/Signal-iOS/blob/master/SignalServiceKit/src/Messages/Attachments/OWSMediaUtils.swift#L161), perhaps because the animated image could be significantly large in size.

A pull request can be easily made but we from outside of the dev team would not know exactly how much the app could allow here. I am pretty certain that the number can be relaxed given that Desktop and Android accept the exact gif without issues, but the question is how much.

**Comment by Jesus8000** [comment]
pls fix it

**Comment by shimamizu** [comment]
This appears to still be an issue.
