### ISSUE TITLE
Signal hangs on tapping a profile picture

### ISSUE THREAD

**Issue by harrouet** [signalapp/Signal-iOS#4680]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While tapping on a profile picture in a group conversation, the app hangs.

### Steps to reproduce
- open a group conversation 
- tap the profile picture of a contributor

NB : not tried with 1-to-1 conversations 

**Actual result:** the app hangs and has to be force-quit

**Expected result:** open profile view

### Device info

**Device**: iPhone SE 1st gen

**iOS version**: 14.2

**Signal version:** 5.0.3.0

### Link to debug log

https://debuglogs.org/6d7d279bf65470f6da214c1460e78a8be3ca1d85bc924c1fec2164fb4cf779a8.zip

**Comment by Lord-V15** [comment]
I've tried to reproduce these steps on my iPhone SE 2nd Gen, running iOS 14.3
It is working fine for me. The app **does not** hang.
I also tried asking my friends (running iPhone XR, iPhone 11 on the same iOS 14.3) and they couldn't see any issue there as well. Therefore, I suggest you the following :

1. See if your Signal app is updated to the latest version.
2. Make sure that iOS is the latest version because this may be an issue with iOS. (let us know if that if the case)
3. Try reinstalling the app as the last option.

**Comment by glenn-t** [comment]
I am having similar issue on iPhone SE (1st edition I think).
iOS version: 14.4
Signal version: 5.4.0.17

In addition, the bug only happens when I tap on a profile picture for a contact who is not in my phone contacts. The bug also happens for chat members not in my contacts when I tap on chat member in the chat settings view.

**Comment by harrouet** [comment]
> I am having similar issue on iPhone SE (1st edition I think).
> iOS version: 14.4
> Signal version: 5.4.0.17
> 
> In addition, the bug only happens when I tap on a profile picture for a contact who is not in my phone contacts. The bug also happens for chat members not in my contacts when I tap on chat member in the chat settings view.

I also have an iPhone SE 1st generation. Could it be linked to the handling of the screen size ?
