### ISSUE TITLE
Messages getting sent are slow

### ISSUE THREAD

**Issue by an4s911** [signalapp/Signal-iOS#4687]
As most people coming to this app are from WhatsApp and WhatsApp is really fast at receiving as well and sending messages, this app needs that too. I noticed it when I sent a message that it takes some time for the 2 ticks.

Thank You 😊✌🏻

**Comment by Lord-V15** [comment]
This is not the place to mention this @an4s911 
I'm sure you can understand Signal is facing this issue because of the immense traffic that's coming in.
I can guarantee you that the team knows this and is in work to significantly upgrade the servers. So, please sit tight and wait for upcoming updates 🙏 💪 
This is a place for reporting app bugs so kindly close this issue so the iOS team can actually work on fixing out bugs and broken features.
