### ISSUE TITLE
Continuously displaying profile name changes in group chats

### ISSUE THREAD

**Issue by MBurchard** [signalapp/Signal-iOS#4694]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In group chats on iOS Signal shows that persons have changed there profile names continuously for days now.  
This messages are followed by a small Button "Kontakt aktualisieren" (Update contact?).

### Steps to reproduce
- be in a group chat
- let somebody change it's profile name
- it might be that the parallel usage of the windows desktop client has an influence on that bug
- the desktop client shows that messages only ones...

**Actual result:** see bug description

**Expected result:** It should be shown only ones

### Screenshots
![grafik](https://user-images.githubusercontent.com/4256302/104133906-befe6c00-5386-11eb-8d66-94dfec8c75f4.png)

### Device info
**Device**: iPhone 8

**iOS version**: 14.3

**Signal version:** 5.0.3.0

### Link to debug log
https://debuglogs.org/f41f2a58b87f7283af3c018d7aad7eb3fa221df9700cd0f312a201545bbbcff0.zip

**Comment by johnmbergman** [comment]
I might have some additional context. I am in a group chat and removed my last name in the app. Others in at least one group chat have since noticed constant notifications of my name changed from first and last to just first, and vice-versa. I’m adding my last name back for now to see if that resolves the issue. I have an iPhone X and iPad Pro and frequently switch between the two on Signal.

**Comment by MBurchard** [comment]
The Bug is still there with version 5.1.0.31 of the app.

**Comment by JJS777** [comment]
Thank you !!!! I appreciate the Help 
I believe I am Hacked I trade stocks and I noticed that someone was recording screen shots of me using my phone in the cloud.. I knock him off and reset password but he gets back in .. I notice him in the Game app on my phone

**Comment by JJS777** [comment]
> The Bug is still there with version 5.1.0.31 of the app.

The guys name that is on my phone is on the link above us , all my internet and phone is unsecured

**Comment by MBurchard** [comment]
What?

**Comment by JJS777** [comment]
> What?

Yes !!! He is on the message board above us 
John Bergman

**Comment by MBurchard** [comment]
> Yes !!! He is on the message board above us
> John Bergman

Please take the time to explain in complete sentences what problem you are having with the Signal iOS app and how that relates to the bug I reported.

**Comment by JJS777** [comment]
> What?

He claims to have the exact equipment as me

**Comment by JJS777** [comment]
The Name that is Displayed on my devices is on my message board John Bergman .. I kick him off my devices and he always appears on it .. now he his on Github

**Comment by Imperiopolis-Signal** [comment]
Unfortunately, it’s hard for us to diagnose this issue without knowing the data that has been blanked out in your screenshots. We’re unable to reproduce here. 

Can you give us a little more context? For example, are the notifications always like:

old name changed to new name
new name changed to old name

(a back and forth)

or are they just:
old name changed to new name

over and over?

If you’re comfortable sending an unmasked screenshot to ios-beta@signal.org that is also an option.

**Comment by johnmbergman** [comment]
In my case, this is what other members in my group have been seeing. Note that I only changed my name once (only removing my last name). It is interesting to me that the first and last name appeared in the beginning portion of the sentence in all cases. This is a legacy group, in case that makes a difference.

![EC853070-B94B-48B3-8D0A-BA489866B12E](https://user-images.githubusercontent.com/5831825/104220880-fe63a180-53f4-11eb-941b-e48af7a1f4d0.png)

**Comment by Imperiopolis-Signal** [comment]
Thanks for the additional details. We will continue looking into this.

**Comment by JJS777** [comment]
> What?

I could send you screen Shots

**Comment by MBurchard** [comment]
> 
> 
> > What?
> 
> I could send you screen Shots

Please don't until you are able to describe what your problem has to do with this topic in complete and understandable sentences.

**Comment by JJS777** [comment]
> Unfortunately, it’s hard for us to diagnose this issue without knowing the data that has been blanked out in your screenshots. We’re unable to reproduce here. 
> 
> 
> 
> Can you give us a little more context? For example, are the notifications always like:
> 
> 
> 
> old name changed to new name
> 
> new name changed to old name
> 
> 
> 
> (a back and forth)
> 
> 
> 
> or are they just:
> 
> old name changed to new name
> 
> 
> 
> over and over?
> 
> 
> 
> If you’re comfortable sending an unmasked screenshot to ios-beta@signal.org that is also an option. 

I am comfortable sending screenshots! I know I've had problems for at least 6 months now

**Comment by firescry** [comment]
It looks like I'm affected by this problem too. I'm using Signal on Android, but my friend have it installed on iOS. At some point I received in-chat notification saying that "Your safety number with X has changed." (X being name of my friend). Since then I'm receiving similar notifications as @johnmbergman and @MBurchard - _"X changed their profile name from A to B"_ and _"X changed their profile name from B to A"_. They usually show up before and after my friend does any interaction on the chat (sends a message, gives a reaction, reads a new message) as in this example:
![chat view](https://user-images.githubusercontent.com/49809580/112730962-c6b8c000-8f34-11eb-8fc5-a501c0cefe7b.png)

These notifications show up both in the group chat (new type of group) and in 1-on-1 chat.

What's more I've noticed that messages I receive from that friend are marked with _Sealed Sender_ icon:
![incoming message details](https://user-images.githubusercontent.com/49809580/112731103-a2a9ae80-8f35-11eb-94d0-8b2408efa9a4.png)

but message I send to him doesn't have that icon (there is another friend on that chat and the same message send to him has _Sealed Sender_ icon):
![outgoing_message_details](https://user-images.githubusercontent.com/49809580/112731166-f5836600-8f35-11eb-86ed-e71181c49b92.png)

Here is the log I collected: https://debuglogs.org/11705d74e21f51be047226bb9367f0ebb029ec67bb9d266297e7d0e5100e61bf

I thought that this problem is related to #4917, but seems not as the other was solved recently with app update, while this one persists.

**Comment by firescry** [comment]
It looks like the problem is solved now (at least for me). When my friend sends messages (from Signal on iOS v5.9.0.49) to me (Signal on Android v5.8.10) those extra notifications (_X changed their profile name from A to B_) don't show up any more. Also messages I send to him show _Sealed Sender_ icon again.

**Comment by patrick-cpka** [comment]
This is still an ongoing issue.

**Comment by DamnDesert** [comment]
This is still an issue, I'm troubleshooting it for a friend I chat with who does group chat. Signal is automatically changing their profile name without the end-user doing anything of the kind; I see the result in my chat feed with them as well. My last text with them it shows _"[My friend] changed their profile name from Clove to clove."_ The one before that on Feb 24th shows "_[My friend] changed their profile name from turquesa to ."_ This is a real issue, people distrust texts from my friend and they can't help but wonder their phone or profile got hacked.
