### ISSUE TITLE
Unable to fully paste text+link content from clipboard

### ISSUE THREAD

**Issue by yur1xpp** [signalapp/Signal-iOS#4708]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal only partially paste content from clipboard that contains both text and link. It will only paste the text without the link.

### Steps to reproduce
- Download/use any news app like Bloomberg, open an article.
- Click share, then copy.
- Paste that into Signal app.

**Actual result: Only the text (title) of the article was pasted. There's no attached link to the article.

**Expected result: Text+Link of the article is pasted. This happens in other messaging app like Telegram.

### Screenshots

https://user-images.githubusercontent.com/34767893/104261894-713a4e80-54c1-11eb-9ed2-acf336607331.mov

### Device info

**Device**: iPhone X

**iOS version**: 13.5.0

**Signal version:** 5.1.0

### Link to debug log
None

**Comment by SUMUKHA-PK** [comment]
Can you have a video where you have telegram open too and it can paste the same there? That'd help

**Comment by yur1xpp** [comment]
It doesn't have to be on Telegram specifically, even if you paste it on Notes app, both content were paste.
![IMG_1730](https://user-images.githubusercontent.com/34767893/104810726-96b4b880-5831-11eb-94f9-e72c431f1234.jpeg)

**Comment by zjalexander** [comment]
I also have this issue, and it is driving me bonkers. I can copy a URL from e.g. an RSS reader app ([Newsblur](https://www.newsblur.com/ios), in my case) and it will paste fine in Messages showing Title + URL but not in Signal, showing only Title and no URL. 

My workaround is to open the page in Chrome which allows me to paste the URL, possibly because Chrome does not try to transmit Title. 


Device: iPhone 8

iOS version: 14.3

Signal version: 5.2.1.3

**Comment by Mikaz-fr** [comment]
I have the same issue and it force me to paste first the text, then copy the link separately and paste it again in Signal. 

Device: iPhone 12

iOS version: 14.2

Signal version: 5.5.0.18

**Comment by ralphstone1** [comment]
Was you able to recover your address book and how do you find it for my subscriptions. Please and thank you

**Comment by xtal-ball** [comment]
I have a similar issue with likely same root cause. When using share->copy from the NYTimes app, there is no article title placed on the clipboard, just a URL. When pasting this into a Signal message text entry, I see the iOS modal pop up at the top of the screen, “Signal pasted from NYTimes” but no text at all appears in the entry. Without reloading the clipboard, I can go to a different app (say the Safari url bar or Notes) and successfully paste the clipboard contents, then select it again in that app, copy from there, and successfully paste into Signal. This problem does not seem to occur with other clipboard sources, but the bad interaction with NYTimes has been occurring for a long time.

iOS 14.6, Signal 5.17.1

Another workaround: create a “copy 2” action in Shortcuts: copy shortcut input to clipboard. Use that as the sharing target from NYTimes and then it works into Signal (system pop up shows “Signal pasted from Shortcuts”).

**Comment by zjalexander** [comment]
Yes, it's still (!) relevant. What is blocking it is an investigation and code fix.

**Comment by zjalexander** [comment]
Repro'd just now
Device: Iphone 13 Pro Max
ios: 15.2.1
signal: 5.26.10

**Comment by xtal-ball** [comment]
Repro’d just now from NYTimes app as I commented previously, except now in iOS 15 the paste notification is gone. Confirmed my Copy2 workaround still works. iOS 15.2.1, Signal 5.26.10

**Comment by xtal-ball** [comment]
Yes, stalebot, it’s still relevant. My jan 24 comment Is still exactly true, now with iOS 15.3.1 and Signal 5.33.1.

**Comment by zjalexander** [comment]
Yes, it's still relevant. Nothing blocking it except dev attention.

**Comment by yur1xpp** [comment]
Bad bot

**Comment by yur1xpp** [comment]
Please remove auto closing bot, it's disrespectful to the users taking time file a report, only to know you don't care about it and close it automatically. Leave it open if you don't intend to fix it.

**Comment by yur1xpp** [comment]
Not it's not fixed yet.

**Comment by mknudsen** [comment]
We have the same issue with our e-commerce app. The app is exclusive to Germany. https://apps.apple.com/at/app/otto-shopping-mode-living/id1273131115 

When you share a product and copy the data to clipboard, other apps paste the text as well as the link (as expected). Signal however only inputs the text, not the link itself.

**Comment by guidobouman** [comment]
This problem is also happening with me. Seems like some permission problem. While it initially did work for me.

Signal on iOS, manual copy + paste not working, links get stripped from the pasted content. While direct share from another app to Signal is working, although it keeps only the link, and not the text. But that's more useful than the other way around...

**Comment by CyberstormXIII** [comment]
Still fully relevant and unfixed. You cannot copy-paste text and links from the clipboard on neither ipadOS nor Windows 11.

https://www.reddit.com/r/amiga/comments/1gk4u2q/comment/lvsotmn/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

This page with amiga stores around the world copy-pastes fine in both notes and gmail, where text AND links are preserved (on  iPadOS), and similarly on windows, but when pasted from the clipboard signal misinterprets the data and does NOT correctly process the entire dataset stored in the clipboard as most other programs that can handle HTML and XML. It seems it casts it all into text and all data pertaining to hyperlinks are wiped. Only if you paste 1 link only with no text will it understand it as a link.
