### ISSUE TITLE
Share Intent to recent contacts from share sub-screen

### ISSUE THREAD

**Issue by UtkarshBhatthere** [signalapp/Signal-iOS#4709]
I don't know what the iOS equivalent is to intents but when I try to share a picture or link I do not get my recents on  the share sub-screen directly rather I have to click signal app then click the contact I wish to share to. This is certainly a feature request but I guess a 'decent' one, if possible I'd like to help (programmatic) in the development of this feature.

**Comment by balintmaci** [comment]
I would like this as well, but it may have to do something with security, since normally you have unlock the app to see your contacts and the like. I think it would be great, but maybe it could be optional.

Also, the in-app sharing experience would be a lot better if the contacts were sorted by recent messages instead of alphabetical.

**Comment by Kiatra** [comment]
I believe you mean what apple calls Suggestions in  Share Extension see: [Supporting Suggestions in Your App’s Share Extension](https://developer.apple.com/documentation/foundation/app_extension_support/supporting_suggestions_in_your_app_s_share_extension)

**Comment by jrkager** [comment]
+ 1 for integrating Suggestions in the Share Extension!

**Comment by UtkarshBhatthere** [comment]
This is integrated in the latest update to signal app on iOS. When trying to share anything recent signal contacts appear in the suggestions. I would thank the development team for taking this suggestion up and working this hard for signal iOS app.
