### ISSUE TITLE
Video calls not ringing

### ISSUE THREAD

**Issue by SpeedyR0B0T** [signalapp/Signal-iOS#4721]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
- receiving video call doesn’t ring
- have some video call you
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Doesn’t ring after call get notification of missed call
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
It should ring

### Device info

**Device**: iPad Pro (10.5-inch)

**iOS version**: 14.3

**Signal version:** 5.1.0.31

### Link to debug log

https://debuglogs.org/510f7bd6e37965eb54345d6e26b25f94ffcb7b70a1c701fc72bd13c547a91f9a.zip

**Comment by Imperiopolis-Signal** [comment]
Hi, thanks for your feedback. This is intended behavior – iOS doesn't have support for ringing video calls like normal calls, while still giving you the option to choose whether to turn your camera on or not while answering. We recognize this isn't a perfect solution, and we'll keep thinking about ways we can make this better. If it's important for your call to ring, you may start it with the "audio" button, and then turn on video once the call is in progress.

**Comment by SpeedyR0B0T** [comment]
Thanks for the explanation and keep up the good work!!!

**Comment by mklilley** [comment]
Thanks for your explanation @Imperiopolis-Signal . What you describe makes sense from a privacy perspective. I think it could be worth adding this to your troubleshooting section https://support.signal.org/hc/en-us/articles/360007060672-Troubleshooting-Calling . Currently it says:

```
On iOS when the screen is locked, video calls display a notification not a ringtone. Display notifications for your lock screen from settingsapp.png iPhone Settings > Signal > Notifications > under the Alerts section select Lock Screen. 
```

When I first saw this I thought .... "well that doesn't make sense... how are people supposed to know if someone is calling...they would have to be right next to their phone with it unlocked...an unlikely occurrence". Now that I understand this is done to protect privacy it does makes more sense.

I wonder whether it is also worth letting people know about this when they are about to make their first video call. Although I understand the privacy concern, a video call that doesn't actually call is not what the average user would expect. I myself have been puzzled for weeks as to why my friends haven't been picking up my video calls and it took me several hours of digging around to find your post....most users would probably give up before then thinking that the app is broken.

From a technical point of view I would like to add that when I tried this with a friend of mine, I called them and their iPhone did receive a notification but only visual and with vibration, no sound. It was only when I hung up (without them answering) that a ping sound came through on their phone.  Is this the expected behaviour?

Thanks for all your hard work on Signal - other than this video call thing I'm absolutely loving it!

**Comment by Imperiopolis-Signal** [comment]
If their phone is unmuted, it will play a ringing sound while the notification is present. If the mute switch is on it will just vibrate.

**Comment by mklilley** [comment]
Hi @Imperiopolis-Signal, thanks for your reply. The technical point I was describing above is not as you described it. My friend's phone was indeed unmuted but only vibration happened. It was only when I hung up (without them answering) that they got an audible "ping". This doesn't seem consistent with what you just wrote. Could there be a bug?

**Comment by Imperiopolis-Signal** [comment]
That does sound like a bug. Can you ask them to gather debug logs and share them here, or via email to our support team? Instructions on how to do this can be found here https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by mklilley** [comment]
Hi @Imperiopolis-Signal . Here is the log file you requested 

https://debuglogs.org/2bf568c84c8d84e3daeb91b0bcb9cf222b50ac718292a11f6b53a5d528519163.zip

Just before my friend generated the log, I first did an audio call (which rang) and then hung up before he answered, then I did a video call (which only produced a vibrating notification on their phone) and then I hung up (at which time my friends phone make a ping sound).

Let me know if you have any other questions.

Thanks again.

**Comment by jc-clown** [comment]
Second that this is likely a bug. I also having this issue and is demonstrated when calling both of parents or my wife. As the original bug report, when trying to place a video call, it doesn't ring on their side. The workaround has been for me to place an audio call and when they answer we switch on the video. Once additional point, when doing the workaround we also pretty consistently have to switch the video on and off a couple of time to make the switch over happen.

**Comment by imgos** [comment]
It is worth reconsidering the decision to favor privacy so heavily when the choice is between:

1. allowing answering a video call with video disabled + video calls not ringing
2. forcing video on when answering a video call + video calls ringing

The call ringing in a manner that is consistent with other phone functions is very important.

It would at least be good to add an option to ring and enable video instead of the current behavior.  I suggest that rollout of a feature like this should also present the option to users when the open the new app version so it is easy to switch to letting video calls ring.

Users with less understanding of why this is happening tend to be the ones who really want their calls to ring (like most of my family and friends).  I, personally, can deal with this behavior, but recognize that it is antithetic to most people's expectations when receiving a video call.

**Comment by codemac** [comment]
How is "not ringing" to support a random feature (keeping video off after answering) so critical, but when I pick up a ringing audio call, it automatically connects to my mic (which I may also wanted to keep private)? this is a very arbitrary line to drawthat most users don't expect.

I've had to explain this to my whole family every video call "you need to turn on the camera" "ok I'm ready" <no ring> "did you call? Sorry I didn't hear it" etc etc etc etc.
