### ISSUE TITLE
Search Chat 

### ISSUE THREAD

**Issue by samxsum** [signalapp/Signal-iOS#4794]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Search chat it’s not included website information , only show up chat detail 

### Steps to reproduce
- For example I search Gucci in group 
- Group Name -> Search -> Gucci
- Showed 1 of 3 result

**Actual result:** 1 of 3

**Expected result:** Expected 1 of 4 result included the website link information 

### Screenshots

![7801939B-249F-4BBC-B0B1-EFE9CE04C4AC](https://user-images.githubusercontent.com/77597620/104866030-865b2580-5978-11eb-8ee2-1f889534d423.png)
![F78B97E8-403D-4266-B526-4F56344B030E](https://user-images.githubusercontent.com/77597620/104866037-8bb87000-5978-11eb-8174-4db391251471.png)

### Device info

**Device**: iPhone 12 Pro Max

**iOS version**: 14.3

**Signal version:** 5.1.0.31

**Comment by sbilling** [comment]
This is actually linked to a larger issue with the search functionality. You can only search by the beginning letters of any word in a message. For example "The quick brown fox" can only be queried with "the", "quick", "brown", or "fox" (or any combination of those words). You CANNOT search "rown" and expect the search logic to recognize it is a substring of "brown." Same applies to links, in your case if you search "https" you will see the link because that is beginning of the string representing the link.

**Comment by sbilling** [comment]
FWIW, this is how iMessage works. I imagine it is more performant than querying substrings but I cant speak to it here as I didn't implement search in the Signal app.
