### ISSUE TITLE
Unable to download or play received videos on iPhone

### ISSUE THREAD

**Issue by rb81** [signalapp/Signal-iOS#4835]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Larger sized videos received from contacts don't download or play.

### Steps to reproduce
- Receive a video from a contact
- Open chat window
- Attempt to download

**Actual result:**
The video appears as a thumbnail with a reload icon. When clicking, the rotating circle icon appears momentarily, then reverts to the reload icon. Video can't be downloaded or played.

**Expected result:**
The video should download and play.

### Device info

**Device**: iPhone SE (2nd Gen)
**iOS version**: 14.2
**Signal version:** 5.3.0.16

**Comment by rb81** [comment]
This seems to be somehow related to the censorship circumvention feature. When turned off, I'm able to download videos.

**Comment by rb81** [comment]
Playing around with Censorship Circumvention doesn't guarantee a fix. Def seems like an issue with certain media.

I've also noticed mpeg files don't download or play at all on iOS.

**Comment by rb81** [comment]
This issue seems to still exist in the latest update, but now when trying to send larger files, the loading icon seems to go on an endless loop. Very frustrating that Signal can't manage media that well!

**Comment by schmiggedi** [comment]
Hey @rb81,

do you have also problems with sending media (photos/videos/voicemails) or just receiving/downloading media files?

Best Regards!

**Comment by rb81** [comment]
> Hey @rb81,
> 
> do you have also problems with sending media (photos/videos/voicemails) or just receiving/downloading media files?
> 
> Best Regards!

Here's what I've noticed so far:

* Problem sending large videos from Photos app on iOS
* Problem receiving MPEG videos on iOS coming from Android users (video downloads but simply opens black screen)

**Comment by clocksmith** [comment]
I have found that older `.MOV` files will end up with the extension `.mpeg` after being sent through the signal app on android. These mpeg files play fine on Android devices, but iOS and MacOS are unable to play them.

Simply renaming the `.mpeg` file to have extension `.mp4` allows it to be played on MacOS.

The ffprobe data before and after going through signal is _identical_, except for the filename. Ideally, the Android client would prefer the `.mp4` extension over `.mpeg` during compression, so that iOS and MacOS can play the video. Alternatively, the iOS client can replace the file extension from `.mpeg` to `.mp4` upon receiving the video.

```
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers	
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)	
  configuration: --prefix=/Users/<me>/homebrew/Cellar/ffmpeg/4.4-with-options_1 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages	
  libavutil      56. 70.100 / 56. 70.100	
  libavcodec     58.134.100 / 58.134.100	
  libavformat    58. 76.100 / 58. 76.100	
  libavdevice    58. 13.100 / 58. 13.100	
  libavfilter     7.110.100 /  7.110.100	
  libswscale      5.  9.100 /  5.  9.100	
  libswresample   3.  9.100 /  3.  9.100	
  libpostproc    55.  9.100 / 55.  9.100	
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/<me>/Desktop/video_from_iphone_2011.MOV':	
  Metadata:	
    major_brand     : 3gp6	
    minor_version   : 256	
    compatible_brands: isomiso2avc13gp6	
    creation_time   : 1970-01-01T00:00:00.000000Z	
  Duration: 00:00:25.13, start: 0.000000, bitrate: 751 kb/s	
  Stream #0:0(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 480x360, 716 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc (default)	
    Metadata:	
      creation_time   : 1970-01-01T00:00:00.000000Z	
      handler_name    : VideoHandler	
      vendor_id       : [0][0][0][0]	
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 29 kb/s (default)	
    Metadata:	
      creation_time   : 1970-01-01T00:00:00.000000Z	
      handler_name    : SoundHandler	
      vendor_id       : [0][0][0][0]
```
      
```
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/Users/<me>/homebrew/Cellar/ffmpeg/4.4-with-options_1 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/<,e>/Desktop/video_from_iphone_2011_originally_MOV_converted_to_mpeg_by_android_signal.mpeg':
  Metadata:
    major_brand     : 3gp6
    minor_version   : 256
    compatible_brands: isomiso2avc13gp6
    creation_time   : 1970-01-01T00:00:00.000000Z
  Duration: 00:00:25.13, start: 0.000000, bitrate: 751 kb/s
  Stream #0:0(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 480x360, 716 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 29 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
```

I believe this is independent of the 100mb issue.

**Comment by eAnonyme** [comment]
@rb81 @clocksmith 

Hello,

a friend (iPhone 11 iOS 14.6 Signal 5.16.0.45) wasn't able to play a video I (Android 9 Signal 5.17.3) sent to her. Black thumbnail on her side and when she clicks on it it just displays a black screen for 1 second. No issue with other videos from the same source (so with the same container, codec and definition). 

This video was 101 Mo (96 MiB) in FullHD. After I trimmed/cut it, the video was only 87 Mo (82.7 MiB) still in FullHD. I sent the trimmed/cut version and this time my friend was able to watch it. 

So I decided to proceed with further testing, which lead to the following results (I used a SD video, that I trimmed/cut to obtained smaller video sizes):

### Results

:+1:  105 MB / 100.3 MiB : can't be sent ("An item was removed because it exceeded the size limit")
:negative_squared_cross_mark:  102 MB / 96.8 MiB : can be sent but can't be played
:negative_squared_cross_mark:  98.3 MB / 93.8 MiB : can be sent but can't be played
:+1:  91.6 MB / 87.6 MiB : can be sent and can be played

The Signal client only allows videos below 100 MiB (and not MB), which is why a 102 MB video can still be sent. 
Each video is a .mp4, codec H.264 - MPEG-4 AVC (part 10).

### Conclusion

Issue occurs when the size of a video is large (let's say somewhere between 93 MB and 103 MB). 

No matter what, each video can be played on a desktop client, so the file isn't corrupted by the server since the video went through the server to be delivered to the desktop client. Must be specific to the iOS client (unless I missed something).

**Comment by jboycha** [comment]
I am still having this problem since last one year, many updates later and even an IOS has not fixed this issue. Can not download or play video sent from a user in Android (few,who have been lazy, still to move back to WhatsApp after Signal is working ok on Android, almost all IOS friends switched back, because of this problem)
![image](https://user-images.githubusercontent.com/78777509/135701561-15cd50af-a553-4930-857f-168d51b41be1.jpeg)

Signal Version: 5.21.2.4
IOS Version: 15.0 (19A346)

**Comment by PeterHagen** [comment]
This is still an issue for me. What @jboycha describes is the exact issue for me. I can't watch the videos, and not even download the videos

**Comment by rabauke80** [comment]
Issue still exists in the current iOS version for me - video downloads, black thumbnail with the „This video can’t be played“ icon/text. If downloaded manually via the chat media to a local folder and opened with VLC as an alternative player, the video is just fine.

Is there a reason for the wontfix label?

**Comment by pierrekotarski** [comment]
> Is there a reason for the wontfix label?

Same question 🙋🏻‍♂️

**Comment by agentdr8** [comment]
Had this issue sending a 1.7MB video file to my daughter on iOS from my Android device. I renamed the file from .mpeg to .mp4 and then she was able to view it.

**Comment by Miguel-Signal** [comment]
Hi @agentdr8 

If possible, could you try to recreate this issue again then email support@signal.org with a link to your debug logs as well as a debug log link from your daughters device and reference this Github issue in the email? 

To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.

**Comment by agentdr8** [comment]
> Hi @agentdr8
> 
> If possible, could you try to recreate this issue again then email [support@signal.org](mailto:support@signal.org) with a link to your debug logs as well as a debug log link from your daughters device and reference this Github issue in the email?
> 
> To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.

Email with debug logs & link sent.

**Comment by blackbit42** [comment]
Why was this issue closed?
The problem still persists.

**Comment by luddhelm** [comment]
I have this issue as well. Android and desktop can view my uploaded video, but iOS users can't. 

> Issue occurs when the size of a video is large (let's say somewhere between 93 MB and 103 MB).

This is what I'm experiencing as well. I haven't pinpointed the exact limit, but a 91,9 MB (96 400 507 bytes) video couldn't be played by iOS users. Same video (but with a lower quality setting / lower file size) worked just fine.
