### ISSUE TITLE
Unable to upload profile picture on iPhone

### ISSUE THREAD

**Issue by Angelluc** [signalapp/Signal-iOS#4840]
Hello,

I try to upload a profile picture on my iPhone but when I choose a photo from my photo library (tried .png and .jpg) it just returns to the settings page without any change. 
Rebooted my phone but that didn't change anything.  On my Mac there is no possibility to change the profile image so no wsy to put one. Signal version 5.3.0.16

https://debuglogs.org/4a847e78656bee1a1acb85c13303cb68040d6b8b5246b2addd22c9650d7cc10b.zip

**Comment by EshtonMartin** [comment]
I seem some behavior like this in multiple apps after the last few iOS updates. Are you sure you've given Signal photo access permission? 

It's a setting in iOS itself. You can find it here: Settings>Privacy>Photos>Signal 

They added a "selected photos" option, but I've had some strange results trying to use it. Try switching to "all photos" then restart the app and try setting your photo. 

If this works but you prefer not to give the app (or any app) free photo access, you can switch back to "none" after updating your profile since it will keep its own copy.

Hope this works for you!

**Comment by Angelluc** [comment]
Thank you for your response EshtonMartin,

I had this privacy setting for Photos already set to allow read and write for Signal so that is not the cause or solution in this case.
