### ISSUE TITLE
Share from somewhere else only works on second try

### ISSUE THREAD

**Issue by aebiator** [signalapp/Signal-iOS#4864]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to share some thing to signal (from another app for example) the first time it doesn’t take and then the second time it will pull up the menu of users to share with and it works successfully

### Steps to 
-click share
- menu pops up to share via list of apps
- select signal

**Actual result:** 
-something fails, fails to proceed to menu to select a user or a group
-must repeat above steps, works on second try 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

-should allow me to select a user the first time

### Device info

**Device**: iDevice X

**iOS version**: 14.3

**Signal version:** 5.2.1.3

**Comment by rrdolaner** [comment]
I had the same problem. In the last version, this problem and other problems in sharing more than one file from the file have been solved. 
As a solution, you can follow:

1.  Get the full [ShareViewController](https://github.com/signalapp/Signal-iOS/blob/a411ecbb7370e460d1ddbc0ad3e24107d0d39f62/SignalShareExtension/ShareViewController.swift) in the latest version.
2. There will be places blushing in your code. Since you're using an older version, you don't have these places, so just make the blushes "Discard Change" from "Code Review".
3.  You also need to make small changes in two different places. Find two lines of code and replace them with another
      - `lazy var loadViewController = SAELoadViewController(delegate: self)` --> `var loadViewController: SAELoadViewController?`
      - `shareViewNavigationController.setViewControllers([viewController], animated: true)` -->  `shareViewNavigationController.setViewControllers([viewController], animated: false)`
