### ISSUE TITLE
Signal IOS App Not Working After Update.

### ISSUE THREAD

**Issue by Zahirpocho** [signalapp/Signal-iOS#4874]
Signal App stops working has an internal issue with its database 
I update the app today as it asked me to and won’t let me use the app until
The update is installed so did update the app took me to the AppStore At Feb 09 2021 @ 10:58am CST from there I just hit update and wait then a few min later this happens 

![369BC66B-DFF6-440B-92BB-47DB27B129CA](https://user-images.githubusercontent.com/38845516/107406314-ec495180-6acd-11eb-9c09-f506875950b5.png)

This is because of an issue with its database 
Did eliminate the app
Did re download again
Still no go 

debug log paste here:

https://debuglogs.org/0245bb1493169737ddde0d1c336f14896d3b819551ab703c96c2d4202845da12.zip

any help or fix will be fine ASAP
Need to use the app to send some messages

**Comment by guest-tech** [comment]
This is because you have still 5.3 version installed. You need to update to 5.4 version. Try again in the App Store to load and install 5.4 version. Were you on Beta 5.4? If yes you have minimum 2 times to download and install from the App Store when switching back to prod version. 

From your logs:
AppVersion startupLogging]]: currentAppVersion: 5.3.2 (5_3_2_1)
2021/02/09 17:54:03:107  💛 [AppVersion.m:111 -[AppVersion startupLogging]]: lastCompletedLaunchAppVersion: 5.4.0
