### ISSUE TITLE
When I post a text message to one of my groups it keeps spinning

### ISSUE THREAD

**Issue by saminash** [signalapp/Signal-iOS#4897]
Just one group! The rest are working just fine. And it’s happening just to me. Works got the rest of the members. I used to be Admin but now I made someone else Admin, left and rejoined.. no luck.,
Please help!

**Comment by ah07** [comment]
I get the same issue ... again. From iPhone to specific android users only. Keeps spinning just for me and won’t send. But can send fine to other users. This has happened at least 6-8 times over the last few months. The only way to fix it is reinstall the app. And lose all the conversations, and reverification needed. So frustrating. Would love to see a fix for this please

**Comment by slindberg** [comment]
I have the same issue as @ah07 describes with a single user on Android. Messages sent from my iPhone app get the spinning circle forever, but I am able to receive messages from them just fine. I can also send messages to them from other devices just fine. Resetting the secure session from either side (my laptop app, since iOS does not support this) does not resolve the issue. The issue started right after a disappearing messages session interval was changed from 1 minute to 5 minutes.

**Comment by ah07** [comment]
And it’s happening again, same issue to same android user, app has just updated to be 5.15.1.3

**Comment by ah07** [comment]
Hi, experiencing same issue again sending to just one android user. Receiving fine from them, and send/receive to all other users just fine. I updated to iOS v5.18.2.4 three days ago, User in question is on v5.15.6, android 4.4.2
Bug report attached
https://debuglogs.org/c032171d25376e080fdb13edb9360b115a8e86940fc0f05a43c7693db9efaf53.zip
