### ISSUE TITLE
Other group members receive excessively many messages that I updated group

### ISSUE THREAD

**Issue by joostop** [signalapp/Signal-iOS#4917]
Some (but not all) group members in all groups in which I am present receive many “x updated the group” messages, x being my name. Today more than 10 in an afternoon, but already for a longer time (weeks) in smaller numbers. I myself do not see anything inside the app, and did not do anything.

I currently have the newest version of Signal, 5.7 on a recent phone (2020) with current iOS. 

https://debuglogs.org/056200a7e68793d6604e2b85517d4e38451a43e6e5f566c4accb3b750cdaebbd.zip

**Comment by BB-TR** [comment]
I am also experiencing the same problem. I also got the 5.7.0.19 build  and the newest iOs (iOs 14.4.1). But the problem does not occur in every group i am in.

**Comment by firescry** [comment]
This problem is visible to me as well.

I use Signal on Android while my peer is using Signal on iOS. Every time they send me a message I see extra information being printed in the chat (_"X updated the group"_, _"X changed their profile name from A to B"_ and _"X changed their profile name from B to A"_). Those extra messages are printed several times before and after the actual message. It happens on a group chat (new group type) where are three contacts in total (including me), but the problem is visible only when I receive messages from that one person. Group info may be updated only by admin but those messages were coming even I temporally revoked admin rights to that group for that contact.
I've noticed also that messages I sent on that group are not marked with _Sealed Sender_ icon for the contact for which I see those extra notifications (messages to third contact in that group do have that icon).

Here is the debug log I collected shortly after receiving a message with those extra notifications (message was delivered on 21 March 2021, 18:34:08 CET) - https://debuglogs.org/4e9156d56e5925ddcc72292ad45a49f98249a579379ae6eb73893a7aac6844d5

**Comment by firescry** [comment]
Latest Signal update on Android (version 5.5.5) solved the problem for _"X updated the group"_ messages and they are not showing up any more in group conversations for me. The other notifications (_"X changed their profile name from A to B"_ and _"X changed their profile name from B to A"_) are still visible but I guess it a different problem.

**Comment by joostop** [comment]
People last received excessive messages of me updating the group on 18 March. The issues seems to have been solved by a recent update. I consider my question as closed.
