### ISSUE TITLE
Multiple simultaneous “contact added you to the group” notifications

### ISSUE THREAD

**Issue by i7u** [signalapp/Signal-iOS#4990]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I get 10+ notifications at the exact same time that one of my contacts has added me to many groups. After I ask my contact whether they did anything with Signal, they have no knowledge of this activity. The groups seem to be all groups I ever shared with this contact.

### Steps to reproduce
Unknown. I was not using my phone at the time. My contact did not do anything either (eg add me to a group, refresh our session, reinstall Signal, or install a new instance of Signal on a linked device). 

**Actual result:**

I get spammed with so many notifications at the same time that my phone is unable to render all the notification sounds correctly. It sounded like 10+ notifications trying to fire simultaneously and stepping over each other. 

**Expected result:**

This should not happen. 

### Screenshots

![image](https://user-images.githubusercontent.com/2001138/117371661-2dc87d80-aec0-11eb-9c8d-8d1e2393fed3.png)

### Device info

**Device**: iPhone 8

**iOS version**: 14.5

**Signal version:** 5.11.0.26

### Link to debug log

https://debuglogs.org/5d798799d3031477480e441bcfc6dcc78e40d97c5701da8d4905952028349ef0.zip

**Comment by 6ffm70** [comment]
I'm hearing from friends with iOS, that they have the same issue - with me being named to have added them. Some have dozens of groups popping up that are up to five years old. At the same time, my groups (in my phone) are unchanged and I did not get any notification. When I open one of these groups it says 'This group _has been_ updated' - different to the message on the receiving end, which says _I_ had updated the group.

Just yesterday I've updated Signal to 5.9.6 on my Android phone, but I didn't touch the old groups.

My assumption:
- the update converts old type groups to new type groups automatically,
- and notifies (some?) members
- which mostly don't have these groups on their phone
- because the changed their hardware when there was no migration feature available

To boil it down, the issue is not the update of the group, but the notification that (some?) receive and a name given who clearly did not update the group.
