### ISSUE TITLE
Accelerated voice memo playback feature

### ISSUE THREAD

**Issue by dmuensterer** [signalapp/Signal-iOS#5037]
A very neat feature for the mobile Signal Application would be something similar to the accelerated voice playback feature that WhatsApp recently introduced.
I.e. the possibility to playback voice memos at 1.5x, 2x  or 3x of the speed it was originally recorded in.
This could also simply be a button that appears next to the voice memo once play was hit.

**Comment by nzedler** [comment]
Would be really useful!

**Comment by matthiaskiller** [comment]
would be amazing - WhatsApp has already implemented it - would be to nice to have it Signal too!:)

**Comment by chriskalos** [comment]
[Signal Android has had this feature for a while](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-16-release/34756) and it would be very cool if Signal iOS could get it too. I will be switching to iOS soon and I will miss this feature so much. It will legitimately stop me from sending or playing voice messages.

**Comment by Crust33f** [comment]
I'd love to have this feature as well. It has already been implemented in the Android Version. It would be fantastic to have feature parity.

**Comment by nstrelow** [comment]
Has anyone with an iPhone the capacity of implementing this?
My gf is annoyed by my long voice messages 😂

**Comment by pzumk** [comment]
I habe only recently learned about Android having the feature to speed up voice messages. Why does Signal for iOS still doesn’t support it?

**Comment by Cerberus0** [comment]
Hello everyone,

This issue tracker is no longer used for feature requests, as stated in the project's [contribution guidelines](https://github.com/signalapp/Signal-iOS/blob/main/CONTRIBUTING.md):

>The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests/17). The purpose of this issue tracker is to track bugs in the iOS client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

Please continue this discussion on the community forum:

https://community.signalusers.org/t/speeding-up-voice-memo-clips/2616

If the stale bot comes asking whether this is still relevant, please ignore it. That bot does not know the difference between bugs and feature requests because this is no longer the right place to submit or discuss feature requests. Thanks!

**Comment by EvanHahn-Signal** [comment]
This feature is now available on iOS, so I'm going to close.

Please move any additional feature requests to [the community forums](https://community.signalusers.org/c/feature-requests/17).
