### ISSUE TITLE
Transferring accounts between IOS Devices doesnt work if your camera is broken and there is no manual way to transfer an account

### ISSUE THREAD

**Issue by MeerBiene** [signalapp/Signal-iOS#5059]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I've got a new phone because the camera on the old phone started working poorer everyday. I wanted to transfer my signal account but oh wait, the camera on my old phone is so broken, I can't scan any QR Codes (if needed I can attach an image of how the QR Code looks through said camera)

### Steps to reproduce
- use an old Iphone SE with broken camera
- use any other newer phone
- try to transfer the signal account from the old Iphone SE to the newer phone

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

There should be a manual way to transfer an account. Not everyone out there is on the newest version of their phone and its kinda not safe to assume everyone has a working camera... 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Account transferral works by entering a 64 digit token or something like that, if your camera is not working properly.

### Screenshots

*No Screenshots needed*

### Device info

**Device**: iPhoneSE

**iOS version**: 14.6

**Signal version:** 5.16.0.45

### Link to debug log

*No debug log needed.*

**Comment by Dr-Big-Man** [comment]
BTW: I had the same problem, as the optical image stabilizer (OIS) was broken and camera picture was always shaking, so that QR code could not be read. In this specific case it was possible to block the OIS by placing a small magnet on the topright corner on the front of the iPhone, so that the mechanics of the OIS get blocked. 

One more thing: with some other apps, the problem with the broken OIS could be prevented when trying to read QR code, by changing the camera zoom a little. This will probably also not be possible with every model of iPhone - however, it worked for me on an iPhone 11 Pro Max and will most likely also work with similar devices.

However, for this workaround to be possible, the respective app does need to expose the full camera controls when offering dialogue for scanning of QR code. Unfortunately signal is exactly *NOT* doing this - so it might be worthwhile to consider respective enhancement for Signal app. HTH.

**Comment by Dr-Big-Man** [comment]
Nevertheless, a procedure for transferring Signal to a new phone when the camera of the old one is *completely* broken is IMHO indispensable, no doubt about it. HTH.

**Comment by NiklasBr** [comment]
It is also impossible to transfer data if the phone is broken by e.g. water damage or significant screen damage. This could be resolved by using a proper backup functionality like the Android and Desktop clients already use.

**Comment by NiklasBr** [comment]
Still relevant.

**Comment by NiklasBr** [comment]
Still relevant, please stop spamming this question.

**Comment by b-col** [comment]
Why was this closed?

**Comment by Dr-Big-Man** [comment]
This issue will remain relevant as long as scanning of QR code displayed by old phone is the only possibility to transfer a signal account between IOS devices. Therefore this issue needs to be reopened.
