### ISSUE TITLE
Signal crashes with network connection (after sending voice message from Signal Desktop)

### ISSUE THREAD

**Issue by jkuchar** [signalapp/Signal-iOS#5105]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I open Signal with network connection active few seconds later it crashes. <del>It looks like there is a [same bug in Android version](https://github.com/signalapp/Signal-Android/issues/11459).</del> (@greyson-signal says, [they are not the same](https://github.com/signalapp/Signal-Android/issues/11459#issuecomment-903726577))

### Steps to reproduce
- Open Signal while you are on netowork
- wait 5 seconds
- it crashes

### Device info
**Device**: iPhone SE2

**iOS version**: 14.7.1

**Signal version:** 5.17.1 (5_17_1_2) + tried beta from Test Flight with the same result

### Link to debug log
[Signal debug log](https://debuglogs.org/5cffb5a99c41477ca37465fc24b1cdb8c73e1762291563d77314eaa541299639.zip)

I will add crash logs into separate comment, when they are available to me.

**Comment by jkuchar** [comment]
From the same moment there is the same problem also on linked iPad. Signal Desktop app works without an issue.

**Comment by jkuchar** [comment]
Here goes the iOS crash log:
[Signal-2021-08-23-113310.ips.beta.txt](https://github.com/signalapp/Signal-iOS/files/7030869/Signal-2021-08-23-113310.ips.beta.txt)

**Comment by JirmoK** [comment]
I can report the same behavior on an iPhone X.
After I installed the beta and left it overnight, the crashes were even more frequent. I always got the popup asking me whether I want to add further information, which made the iPhone unusable.

I sent 2 log files to matthew@signal.org, let me know whether I should add them here as well.
The exception was the same as here (KERN_INVALID_ADDRESS).

Might be of relevance:

- Yesterday, before this started, I linked my Signal app on my MacBook to my account again (was linked in the past but I reset the iOS app). At that point, everything was still fine and I did not update the apps since.
- Additionally, I send an unusually large amount of pictures / videos to a contact yesterday. That contact is still at the top of the list in the app on the iPhone, but not on the MacBook since I chatted there with other contacts since. So this might be related as well.

Please let me know if I can further support.

**Comment by tomxpcvx** [comment]
Hey folks,
same problem here 🙋🏼‍♂️

After sending 2 voicemails with Signal Desktop on my Mac, the iOS app crashes permanently.

If I block internet access in my router configuration for my iPhone, I can transfer the entire chat to an older iPhone. After the successful transfer, this Signal app also crashes. 

Since I installed Signal in February, I have now lost my chats 2 times. The first time because Signal doesn't save a cloud backup and now the second time. I'm really annoyed because privacy is very important to me and I got all contacts in my private environment to Signal. But also the Android app has so many bugs that the satisfaction is slowly tipping over and I'm really pissed because people had trust but then are disappointed because the quality control for the app is apparently not sufficient. 
Also that essential features like a cloud backup are not available after all this time is just disappointing.

Best regards
Tom

**Comment by MayNiklas** [comment]
I can confirm this issue.
When I put my iPhone into flight mode, it won't crash.
When it has any internet connection: it crashes a few seconds after launch.
I've sent a voice memo on my desktop yesterday.  In the past, that never was a problem.

I don't want to loose my history, so I'm going to wait a few weeks.
Signal won't sync very old messages -> maybe it's going to solve itself?

Still: very annoying! I'm primary using Signal for communication, so not being able to use it on my phone is a big problem.

**Comment by JirmoK** [comment]
Now it was mentioned in the other posts I noticed that I also sent a voice memo from the Mac OS app before this issue occurred. And it seems that this voice message is the first message that is *not* appearing in the smartphone app.

So I guess it is likely that this issue is related to voice messages sent from the Desktop app (Mac only?)

@jkuchar did you also sent a voice message from the desktop app?

**Comment by MayNiklas** [comment]
> Now it was mentioned in the other posts I noticed that I also sent a voice memo from the Mac OS app before this issue occurred. And it seems that this voice message is the first message that is _not_ appearing in the smartphone app.
> 
> So I guess it is likely that this issue is related to voice messages sent from the Desktop app (Mac only?)

I've sent my voice message from a windows computer.
What I've noticed: I had this "there is a update available message"

I've updated after I've sent the voice memo.
-> my computer did not have the latest Signal version when I've sent the voice message.

The voice message never synced to my iPhone

**Comment by MrAnno** [comment]
I'm having the exact same problem with both the current beta and the latest (v5.18.3) Signal versions.
The crash report looks identical, a sigsegv is coming from the storage writer thread 5 seconds after enabling network access.

**Comment by MrAnno** [comment]
The most problematic part of this issue is that even if I can not use the app, something in the background appears to be crashing continuously, and it is draining the battery extremely fast (I disabled "background app refresh", but it does not help).

**Comment by jkuchar** [comment]
Battery drain and crashing in background appears also in my case. I cannot confirm that it happened after sending voice message from signal desktop (maybe someone else sent one).

**Comment by MathijsV** [comment]
I'm experiencing the same issue where the signal app keeps crashing on my iPhone SE 1 (iOs 14.7.1, app v5.18.3.0). Crashes started happening after I sent two audio files to someone else using Signal Desktop (for mac, 5.15.0). The first audio file synced to my phone, the second never did. Disabling network keeps Signal from crashing until I enable network again.

**Comment by nicktheg33k** [comment]
I can confirm this issue as well. It manifested after voice messages from Mac desktop were sent. All linked iOS devices crash when network is present. Chats do not update. Clearing all chat history on iOS devices doesn’t work. 

I’ve submitted crash logs to support@signal.org.

**Comment by jkuchar** [comment]
Could you please prepare test scenario how to get into this state so it is easier reproducible by Signal developers?

**Comment by crisscross-applesauce** [comment]
Test scenario as follows:
iPhone with Signal. 5.18.3.0
Linked Mac with Signal Desktop 5.15.0

From the Mac send a series of voice messages to an existing chat. 

iPhone will not receive these and will reliably crash on open when network is present.

**Comment by MayNiklas** [comment]
Test scenario:
devices: iPhone 11 Pro Max & iPad Pro 2020
Signal iOS version: 5.18.3.0
Linked with Signal Desktop on Windows

From my computer, I was sending a voice message to "Note to Self".
I wasn't using the newest Signal version on my computer (I remember a "update now" popup). Maybe the version was 1/2 - 1 weeks old?
After I've sent the voice message, Signal on IOS started to crash when network is present.
It never received the voice message, but all the messages before that.

When I put my phone into flight mode, I'm able to use Signal. As soon as I have a connection again - it crashes.
I guess it crashes when downloading the voice message?

According to some old posts I found, Signal won't save unlimited messages on their servers, before deleting the old ones. I've tried to spam myself with a lot of short messages. It didn't help.

**Comment by HeinrichApfelmus** [comment]
I can confirm this issue. I had also send an audio message from the Desktop app, but it was an .mp3 file, not a voice message. Switching the phone into flight mode prevents the crash (but prevents receiving and sending messages, of course).

Signal iOS: 5.18.3

**Comment by pinpox** [comment]
Same issue here, can confirm. Full reset is not really an option as I need to keep my history

Signal iOS version: 5.18.3.0

**Comment by kiyockumo** [comment]
Having the same issue: sent bunch of voice chats to an existing chat on a pre-linked Mac, and can't use on iOS ever since.
The iOS app is usable when not linked to internet, but will crashes immediately after turning internet back on. It will generate a lag on the phone if closing the app when I use it in airplane mode.
macOS app is usable when the Mac is connected to the internet, and even when phone is not connected to internet.
Noticed the increasing battery draining issue on the phone also. Occupies 34% of the battery usage with only background activity.
Can't generate debug log since it rapidly crashed in 1-5 secs (when connected to internet). 
I have tried offload and reinstall the app but that is no use to the issue.

Scenario: 
iPhone 8 Plus with iOS 14.3, 
Signal iOS app v5.18.3, 
Macbook Air 2020 with with macOS 11.5.1,
Signal macOS v5.15.0

**Comment by MrAnno** [comment]
I was told by Signal Support that this will be fixed in v5.19.0.

**Comment by MrAnno** [comment]
The new beta (v5.19.0) fixed the issue on my end.

**Comment by MayNiklas** [comment]
> The new beta (v5.19.0) fixed the issue on my end.

Can confirm!
My iPad does not crash anymore.
Right now, I'm receiving the messages I received over the last week.
Seems like nothing got lost.
It also downloaded the voice memo I've sent a week ago!

**Comment by JirmoK** [comment]
On my iPhone X, the latest beta (5.19.0 5037) still crashes.
But the behavior is a bit different now:
- I see that new messages are downloaded again
- The app now crashes with **and without** network connectivity

After installing the previous beta, I installed the App Store version again. Other than that, I have no idea what could be the reason my app still crashes.

Here is the log file, the exception type is now "EXC_BREAKPOINT". 
[Signal-2021-09-03-080127.ips.beta.txt](https://github.com/signalapp/Signal-iOS/files/7103671/Signal-2021-09-03-080127.ips.beta.txt)

**Comment by jkuchar** [comment]
I can confirm that 5.19.0 fixes this issue for me! Please 👍 if you are ok to close this issue.

**Comment by jkuchar** [comment]
@JirmoK It looks like you are experiencing another issue. Could you please open new one for your issue and link it from here?

**Comment by JirmoK** [comment]
@jkuchar thanks for the proposal. I know that this would be the right thing to do. However, I have no idea what might be the cause for this issue or under which conditions it's caused. So I don't see, what I could write in an issue description.

I think I will have to let the devs judge this issue and if they think it's solved, I will just have to reset my app...

**Comment by MayNiklas** [comment]
> @jkuchar thanks for the proposal. I know that this would be the right thing to do. However, I have no idea what might be the cause for this issue or under which conditions it's caused. So I don't see, what I could write in an issue description.
> 
> I think I will have to let the devs judge this issue and if they think it's solved, I will just have to reset my app...

As stupid as it sounds: did you try to restart your phone?
I also had problems with my Signal application after upgrading to the newest Beta:
1. First, everything worked
2. After a few hours, I still received new messages / saw my ones; but my phone wasn't able to sent new ones!
3. Signal regularly crashed in the background

I was able to solve the issues described in no. 2 by rebooting my phone.
Still: the app crashes every few hours which is annoying.

**Comment by morriswinkler** [comment]
Any idea when 5.19.0 will be in the app store?

**Comment by michaelpeterlee** [comment]
Q. Do we need to offer a bounty to get this fixed?

**Comment by MayNiklas** [comment]
> Q. Do we need to offer a bounty to get this fixed?

The 5.19.0 got released 2 days ago?
It’s already on the App Store!

**Comment by michaelpeterlee** [comment]
We don't see it in the app store. Perhaps you are subscribed to the BETA.

**Comment by MrAnno** [comment]
I can confirm that v5.19.0 is available as a standard release in App Store (at least for iOS 14.7.1).

**Comment by michaelpeterlee** [comment]
Thanks for confirming, I had to app store search and wait 30 seconds before it showed as an update. Updates usually feature in the app list, but not on this occasion.

Fixes my issue, thanks to all who contributed.

**Comment by morriswinkler** [comment]
I can confirm after update to v5.19.1 it works again

**Comment by HeinrichApfelmus** [comment]
I can confirm that the crash no longer occurs as of version 5.19.0.

Unfortunately, I have now have another issue, #5104, where I can no longer send messages (Signal v5.20.1, iOS 14.8) and Signal is either slow to show a conversation or freezes entirely. The Desktop version is not affected, but both iPad and iPhone versions are affected.

**Comment by jkuchar** [comment]
I'm closing this issue, as it looks it has been solved.

**Comment by Gaaarz** [comment]
It seems this bug returned with the new update on my app. I already sent the logs via email.
