### ISSUE TITLE
Screen shuts off while an audio file is being played and top sensors are covered

### ISSUE THREAD

**Issue by iambradleyk** [signalapp/Signal-iOS#5117]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Open Signal
- Open a conversation
- Play an audio file in the conversation
- Put your hand over the iPhone

**Actual result:** the screen shuts off while the brightness sensors are covered and an audio file is being played

**Expected result:**  the screen shouldn't be shutting off 

### Screenshots
no screenshots

### Device info

**Device**: iPhone 12

**iOS version**: 14.7.1

**Signal version:** 5.18.3.0

**Comment by michelle-signal** [comment]
This is expected behavior. While an audio message is playing, we use the proximity sensor to determine if the user is holding the phone to their ear. If so, the screen turns off and the audio playback is routed through the phone headset.

If you uncover the prox sensor/bring the phone down from your ear, the display should turn back on and audio should continue playing out of the device's primary speaker.
