### ISSUE TITLE
Uknown version of Signal database

### ISSUE THREAD

**Issue by AntonioALEA1996** [signalapp/Signal-iOS#5119]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After I remove latest beta version of Signal and install offical from App store it showing error: Unknown Signal database version.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone 11 Pro Max

**iOS version**: 14.7.1

**Signal version:** 5.18.3

**Comment by michelle-signal** [comment]
This is expected behavior. We don't support downgrading of versions. The beta version of the app performed a one-way database migration that the production version doesn't understand.

Your options are:
- Reinstall the most recent beta and continue to update to Testflight betas as they come out.
- Reinstall the most recent beta, but stop updating the app. Wait until the version on the app store passes your currently installed version. Then, install the app store version. This will work since even though you had originally installed a beta version of the app, you're upgrading to a newer version.
- Delete and reinstall the app store version. You will lose your data doing this.
