### ISSUE TITLE
Microphone or speaker doesn’t work when signal call is connected. 

### ISSUE THREAD

**Issue by 211217613** [signalapp/Signal-iOS#5222]
- [ ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am experiencing an issue where with one contact, once the call has connected I can’t hear the other person and the other person cannot hear me. I tried toggling the speaker button and toggling muting my microphone. Only after hanging up and calling several times does the call work as expected. 

### Steps to reproduce
- start a signal call 
- Once the call is connected try speaking
- You can’t hear the other person and the other person cannot hear you. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone 13 mini

**iOS version**: 15.2

**Signal version:** 5.26.7.2

### Link to debug log

https://debuglogs.org/5d6aa1888009298a95657e35b3f3670805af1e3a0645cc8285f77e80cc4aa2da.zip

**Comment by 211217613** [comment]
Yes it's still relevant

**Comment by Bizzet** [comment]
**I also came here to describe this issue! Extremely annoying! Happens basically every call!**

##### I would like to add a little more info tho:

On iOS, if you are answering a Signal call using the iOS popup (and not the Signal popup), it will not allow you to hear the other person unless you click the button that says 'Signal' which then opens the application and allows you to talk _sometimes._

This is an issue because if you are calling someone else, most people don't know this trick and instead we end up calling each other 2-5 times until we both can hear each other properly (even though there is almost always a lag between our voices)
