### ISSUE TITLE
[FeatureRequest]Native Signal to macOS

### ISSUE THREAD

**Issue by singhalrishi27** [signalapp/Signal-iOS#5228]
Please bring iOS version of signal to macOS using mac Catalyst election app has so many bugs and it is inefficient when compared to native iOS App

**Comment by Genis-Sage** [comment]
hey @singhalrishi27 
Signal devs prefer to reserve the github repo for bug reports...
this is stated in the [Github new issue template](https://github.com/signalapp/Signal-iOS/issues/new/choose)
for feature requests, the preferred way is the community forum:
[Apple’s Project Catalyst: Add support for using the iPad app on macOS](https://community.signalusers.org/t/apples-project-catalyst-add-support-for-using-the-ipad-app-on-macos/7995)

(be aware, I am no Signal dev, just a user trying to help)

**Comment by PalmTamino** [comment]
Hey, i suggest sideloading the Signal iOS App to your Silicon Mac using [Playcover](https://github.com/iVoider/PlayCover)
It's a sideloading utility for Sideloading iOS Apps to your mac, they even have a [Discord Server](https://discord.gg/q7TysgDD), where they share decrypted ipa files (Of course only non paid apps due to piracy).

**Comment by singhalrishi27** [comment]
Hi @PalmTamino I'm on Intel based mac.
It's weird why they are using crap(electron) for macOS
Native app will bring - 
All time notifications even if the app is not running.
It will give better performance and better battery life
Less crashes to the app
App will open instantly
And a sharing extension where you can share a image or file without opening the app.
Native store listing.(with no extra work required)
Much smaller update.

Also it is not hard to bring signal-ios to macOS few code changes will be required but will totally be worth it.

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx

**Comment by Rastafabisch** [comment]
It would be great if this would stay open, to advertise there is still a desire among users.

@singhalrishi27 summet it up perfectly. I also repeatedly run into issues where dropped or pasted images only result in their path being pasted (especially when its a temporary file like a screenshot or when copied on an iOS device using shared clipboard), rather than the image itself. 

> Hi @PalmTamino I'm on Intel based mac. It's weird why they are using crap(electron) for macOS Native app will bring - All time notifications even if the app is not running. It will give better performance and better battery life Less crashes to the app App will open instantly And a sharing extension where you can share a image or file without opening the app. Native store listing.(with no extra work required) Much smaller update.
> 
> Also it is not hard to bring signal-ios to macOS few code changes will be required but will totally be worth it.

I don't think necessarily that a Catalyst build should replace the current desktop version (though I still would welcome this) but, even releasing a signed build on GitHub every now and then would be great for those users who'd like to use it.

Sadly most people cannot build a working version themself, because the project requires extended permissions (Push-up notifications, …) so a free apple developer account doesn't suffice.
