### ISSUE TITLE
"cancel" button too close to "send" button

### ISSUE THREAD

**Issue by schrotie** [signalapp/Signal-iOS#5239]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

On small screen iPhones the button to cancel a "voicemail" in locked recording mode is immediately next to the button for sending it. This minor styling issue regularly leads to unintentional data loss on behalf of the user and thus constitutes a serious issue for those affected.

The attached screenshot shows the situation on a small screen iPhone. Note that the screenshot contains an embedded screenshot of the same situation on a larger Android device. Note how the "cancel" (i.e. "Abbrechen" in this German localized UI) button is significantly further away from the send button in this case.

It is extremely frustrating for a user when unintentionally loosing recordings of several minutes. This happens rarely but regularly even though the user is ware of the issue. Note that the affected user is motorically and technically adept and experiences this issue regularly (like weekly).

Note that this is fix-wise likely a very minor styling issue, where the author just wasn't aware of the narrow iPhones out there. It is also possible that the "cancel" button has a larger (invisible) capture area.

### Steps to reproduce
- on small screen iPhone
- start sending a voice recording and lock the recording mode be dragging up the mic-button
- note how close the "cancel" button is to the "send" arrow button
- It is not entirely clear whether an unintentional _minuscule_ dragging motion is responsible for unintentional aborting or if it is just the closeness of the buttons

**Actual result:**

Voice recording is discarded.

**Expected result:**

Voice recording is sent.

### Screenshots

![signal-2022-01-11-000303](https://user-images.githubusercontent.com/11699114/148945764-d659a051-440a-41a7-afda-60c687a77f0d.jpeg)

### Device info
Since I am opening this report on behalf of another user, I do not have this information at hand. I'll try to put this in later if required.

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by schrotie** [comment]
Yes, it is still relevant, the problem still occurs.

**Comment by NiklasBr** [comment]
This is still relevant.

**Comment by NiklasBr** [comment]
Why won't the bot remove the label?

**Comment by schrotie** [comment]
Yes, still relevant.

**Comment by mehmetb** [comment]
https://debuglogs.org/ios/5.37.2/53a621b59e41071d11776cfbddbbee018630484aa18d80bb5428eb7d83188f2e.zip

I'm facing this issue very often. When I try to send the voice message the recording gets discarded and then a tooltip shows indicating "Press and hold to record". It frustrates me so much.

I have an iPhone SE (2nd Gen). My iOS version is 15.5. My Signal version is 5.37.2.0

**Comment by max-signal** [comment]
We’ve shifted the cancel button a bit further to the left (d4f290954ede389a0c598f2e6114fc1020f4a83f) in the most recent update (5.42), which is available on the App Store now. Can you try it out (& ask the other affected user from the original report to try it as well) and let me know if it results in fewer accidental cancellations?

---

@mehmetb Based on your description, it sounds like you might be running into a slightly different issue. Are you seeing the cancel button appear before the recording stops and the tooltip appears?

**Comment by schrotie** [comment]
I don't have an iPhone, so I can't tell. There were no involuntary cancellation recently for the user for whom I reported this.

**Comment by schrotie** [comment]
@tomasApo The iPhone for which this was reported is one of those really small ones (some "mini" I guess). Since the issue is about closeness of UI controls, it makes sense that this cannot be reproduced on "Max" models. I guess the origin of the issue is indeed, that the respective button layout was not tested on "mini" models. I cannot really tell, though, because I don't have an iPhone. The issue was reported to me by a person with whom I regularly confer.

**Comment by tomasApo** [comment]
@schrotie understood
So to move forward on this issue we need feedback from users with iPhones like:

- [ ] iPhone 12 Mini 
- [ ] iPhone 13 Mini 
- [ ] iPhone SE 
- [ ] iPhone 8

**Comment by schrotie** [comment]
@tomasApo I reconfirmed with the person for whom I reported this. She has a 12 Mini, and reports the usability is much improved with regards to this. The problem hasn't occurred for her for some time, but I don't know, when she received the update.

**Comment by mehmetb** [comment]
I have a 2nd gen iPhone SE. I was regularly facing this issue but in the recent updates Cancel button was moved a bit further to the left and I haven't faced the issue since then.

**Comment by cincodenada** [comment]
Hello, I found my way here because a friend has been occasionally losing their voice notes, and suspects it is because of inadvertently hitting the cancel button. Said friend is using Signal 5.55.0.14, which does appear to have the adjusted margin, on an iPhone 13 Pro (see screenshots below). It does take a decent mis-tap to reach the "cancel", moreso now, but I believe part of the problem is that if the phone is not in your hand, but rather sitting on a table or what have you - more likely if you're, say, recording a multi-minute voice note - your tapping is going to be much less accurate.

In any case, despite having the updated positioning, my friend has managed to do it fairly regularly even on an iPhone 13 Pro. Or at least, that's our best guess - from their perspective Signal just throws away their messages instead of sending them for some reason.

To address @tomasApo's question: the issue (for my friend, at least) is not with that recording mode at all - it is instead with the "slide up" locked-recording mode, where the user is recording without touching the screen at all. After the above commit, that UI looks like this:
![ioscancelbar](https://user-images.githubusercontent.com/479715/194740424-398b0c4d-1671-4699-b210-011f5ff72a58.jpg)
Compare this with the Android version of the same UI, where the cancel button is significantly further left than even the adjusted version, almost centered in the space available:
![recording_android](https://user-images.githubusercontent.com/479715/194740463-b90b939a-4e14-4d14-971f-f3a3efbcc932.png)
I think the Android placement is much better - nudging it a little left helps, but given that the cancel button is irrevocable, why put it anywhere near the send button to begin with? My friend and I often exchange voice notes that are minutes long, and it's exceedingly frustrating to converse for 10 minutes and then have that message simply disappear because you missed by what is still just a fraction of an inch.

I'm not an expert at PureLayout, but from reading the code, it looks like the cancel button is centered by default, and we're currently overriding it to pin it right - is there a reason for doing so? Can we just make it centered instead? I imagine there might be some sort of UI guidelines about buttons in text boxes or some such, but if so hopefully the guidelines are flexible enough to allow for putting a more meaningful amount of space between the "send my 10-minute recording" and "irrevocably discard my 10-minute recording" buttons.

Stepping back a bit, I think a more robust improvement would be making the cancel button _not_ irrevocable - I've posted a feature request about this over on the Signal community (which is still pending), since it's a separate issue.
