### ISSUE TITLE
Registration Error - This phone number format is not supported, please contact support

### ISSUE THREAD

**Issue by bigdave914** [signalapp/Signal-iOS#5261]
New iPhone 13 Pro Max, iOS15.  Can't re-register for signal.  Phone number works fine on older iPhone 7 using iOS 14.  I've tried, reinstalling the app, removing SIM.  I've also tried to reach out to support multiple times with no response. 

[Twitter Thread with screen shot](https://twitter.com/bigdave914/status/1451727531720286209?s=20&t=Xx91Mb48BOH_ZsAzUIa3DA)

Others having the same issue:
[Reddit 1](https://www.reddit.com/r/signal/comments/q1pjlk/registration_error_and_ios_15_number_format_not/)
[Reddit 2](https://www.reddit.com/r/signal/comments/ov1ksm/registration_error_number_format_not_supported/)

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx

**Comment by faisquall** [comment]
I have the same issue with my new iPhone 13 mini.
Is that a problem targeting iphone 13 series?
Anyone has overcome it? please advise.
Signal support never reply my ticket

**Comment by bigdave914** [comment]
Nope, Feel free to open multiple support tickets.  It really only seems to affect iPhone13's and iOS15 but such a fringe group support doesn't care to reply.  Try your luck and let us know how it goes.

**Comment by johngolden91** [comment]
We’re you ever able to solve this issue? I too am having the same issue, and signal support has been 0 help so far.

**Comment by faisquall** [comment]
I turned off "background app refresh" in Setting and tried to register again, it works!
You guys can have a try.

**Comment by bigdave914** [comment]
@faisquall  just tried this, same error.  Thanks for the suggestion tho...

**Comment by EvanHahn-Signal** [comment]
@johngolden91 @bigdave914 Sorry you're running into this. I took a look at the iOS code and it looks like the server is returning an error code for these numbers, and I'm not sure why.

What do these phone numbers look like? Also, if you have a Zendesk ticket ID, I can take a look there to try to get more info.

**Comment by bigdave914** [comment]
@EvanHahn-Signal  - I've had multiple tickets opened. I see no ticket IDs -- My ticket was opened on Jan 31 2022 and I linked the reddit posts above in the ticket so if that helps.  Mine is a regular US number #-###-###-####.   Number is in the ticket if you find it.

**Comment by johngolden91** [comment]
@EvanHahn-Signal i have two tickets, I’m assuming this is the ticket number: O03WYM-7EWQ3 and XML5LG-Z666O. I have the same, a regular US number +1 ### ###-####. All I know is it came about when I changed to an ESIM. I opened the signal app and I was still signed in when I did, and it immediately signed me out and then I haven’t been able to sign in since.

I’ve tried to register using a different SIM card and number as well (currently traveling) and it gives the same error.

**Comment by EvanHahn-Signal** [comment]
We've seen various issues where devices have connection issues that cause registration to fail. For example, some users have had problems because of an AppleCare support app on their phones. Others have had issues with corporate WiFi networks, VPNs, or cell carrier restrictions.

If there's anything strange going on with your device's network, try to fix that and let us know if it doesn't work.

**Comment by bigdave914** [comment]
@EvanHahn-Signal 

I have tried it off my local wifi and on t-mobile.  I have an old iPhone 7 where it registers fine (on my wifi) with the same number so I don't think it's the network.  I have removed the Apple Support app as well, same results.  Everyone reporting this issue seems to be on a new iPhone 13 and seems to be specific to it.

**Comment by nkln** [comment]
I am experiencing the same problems mentioned above but on an iPhone 11 Pro. 

Opened a support ticket over a year ago, received an answer (most likely the ticket ID 899R30-PL3K) asking if I could provide the logs, provided them and got no answer.
The problem appeared after resetting my iPhone to factory settings and installing signal again. 

Tried registering on a wireless network, cellular connection, connected to a VPN etc.

**Comment by johngolden91** [comment]
Yea I have an iPhone 12 Pro Max. Like I mentioned, I changed my SIM to an ESIM with T-Mobile, and that at least for me started the issue. The app worked fine before that.

**Comment by EvanHahn-Signal** [comment]
We're looking into this but aren't sure what's causing the problem. There doesn't seem to be a pattern across these reports.

One theory we have: the server is rejecting requests because the iOS has a subtle bug in the way it sends supported languages to the server. Are any of you doing anything unusual with the languages on your device? For example, are you using a language that's not commonly spoken, or using many different keyboards, or something like that? (I don't know if the iOS app actually has a bug here, but it's our current best theory.)

**Comment by bigdave914** [comment]
Just English.  At least you guys are aware of the issue now, that was the
hardest part.  Sucks not being able to use Signal but I've been dealing
with it for months now.  Are there any other builds I can test with?  Debug
build? TestFlight?

Thanks,
Dave

**Comment by johngolden91** [comment]
@EvanHahn-Signal i found the fix, for me at least. Spurred by your comment I checked my Languages on my phone and I had two random languages added in there in addition to English, "Workshopx" and "com". Not sure why or how they got added but I deleted them, deleted and redownloaded Signal, and I was able to finally get through and log in. Hopefully it's that simple for other people.

**Comment by bigdave914** [comment]
Holy shit, nice find @johngolden91!! I had "Workshopx" and Japanese for some reason.  Removed them, and now it works.

**Comment by nkln** [comment]
@EvanHahn-Signal Sadly that didn’t do the trick for me. I am using only the German and emoji keyboard. System language is english. Had no luck with removing the emoji keyboard and switching German to English (UK) and / or removing the Emoji one and switching to German with German system language.

**Comment by nkln** [comment]
@johngolden91 dude, removing „Workshopx“ from my system language list in iOS did. the trick. Thank you so much!

**Comment by EvanHahn-Signal** [comment]
Great!

In the short term, remove any strange system languages from iOS to avoid this problem.

In the long term, we'll fix this so these languages don't cause registration bugs.

**Comment by EvanHahn-Signal** [comment]
We believe this bug has been fixed (bf8fd72fbab76ef6f3cf9c12091361bb4107f326) on new versions of the iOS app. Please update and open a new issue if you're still experiencing this problem.

Thanks for reporting!
