### ISSUE TITLE
Audio/video call issues

### ISSUE THREAD

**Issue by alasiax** [signalapp/Signal-iOS#5342]
Over the past week or so, my friend and I have had a lot of difficulties making calls, to the point we often have to give up altogether. 

I’ve tried switching from mobile to wifi and vice versa, resetting phone and router etc, and tonight even setting to always relay without joy. 

From my perspective, I can tell my friend is calling because the options to initiate a call grey out, but the call never actually rings for me to answer. 

I have also experienced this over the weekend with another friend, and was not able to connect either in group chat or in a private call. 

Earlier tonight I was able to successfully initiate a group call in signal with 3 others.

log links from myself and my friend are below. 
https://debuglogs.org/ios/5.37.1/54f937ceec2ff283fd71cf9106b0bf7c169de7fa2294b0b53fa695515645085f.zip

https://debuglogs.org/android/5.37.1/920813b1b73c334030b42a6e12cb8550e22663e897594ffc628503bf78c92bd4

**Comment by alasiax** [comment]
Two more debug logs, both iOS:

https://debuglogs.org/ios/5.37.1/3ee1bbd1426748f9c84a1d1ed73ba28e309efabc73bfc5d7988c2d1434316918.zip

https://debuglogs.org/ios/5.36.1/a6881973531b01ee262cc48b6d0bc9dd9be730a2767e53ef6a2c169be5c9f1c8.zip

no connection, didn’t ring, but missed call notification received.

**Comment by Spyre757** [comment]
https://debuglogs.org/ios/5.37.1/0662af7e0563dc12c58a575b426d2b7c151c4adffe1aa14c23a96c9e2c3bf927.zip

Same issue here. Couldn’t make or receive video and audio calls.

**Comment by alasiax** [comment]
This call has connected, first time. I’m the receiver and the call is ongoing. 

https://debuglogs.org/ios/5.37.1/218d40271744a0538e4d134887f4bd2854285e251224edfa69a8312955574ca6.zip

**Comment by Chris8top8he8r** [comment]
Glad I found this.  Forgot I could post here.  Similar issues.  I have a customer who decided to become a new Signal user yesterday.  She can call me from her iPhone and it's fabulous, but I cannot call her from my Android 11 (LineageOS 18.1 with kernel 4.4 - Android 8).  She gets notice of a red text "Missed Call" and knows to call me because I tried to call her.  Then she calls me.  We can always text easily I believe, but it's only been one day.  This seems to be something we can replicate any time.  I tried to submit debug log, but have not been able to get the URL from Signal app for months.  I will try to insert a link below to show a screen grab of the submit debug failure.  I emailed support@signal.org about this and wonder if they get the email.  I bet they must have a tremendously long todo list.  Since I couldn't access the debug log URL in Signal, I connected to computer and took a logcat during my attempt to call the customer.  I will try to attach it here.

By the way, am I supposed to be able to view all the debug logs above?  All the links above load a page that simply says "internal server error" so not sure.  Do the debug log links work above for everyone else?




Here is the link to my logcat capture at my Office 365 OneDrive space for my handyman business wigglemylegs.com.  During this capture I called her, the call wouldn't connect, she got the "Missed Call" notice, Called me, and we spoke less than a minute.  Using Preveiw tab for this post, I tried these links below and they don't work for some reason.  They take me to a Git URL that says No Results Matched Your Search.  I don't know how to use this.  In the Preveiw mode of this post, if I right click my link and say Copy Link, it still copies a link to Git.  But if I drag the cursor to select the entire URL that you see, and insert it into a browser tab, it works.  Hmm.  Advice?

[https://wigglemylegscom-my.sharepoint.com/:t:/g/personal/chris_wigglemylegs_com/EY7V0_PvPyBMiDJVRmW8W94B8MEGEtQjm27L_4UNkMyRvQ?e=2pEQ1Q](url)




Here below is the link to the screen grab from my phone showing the debug log "Submit" failure.

[https://wigglemylegscom-my.sharepoint.com/:i:/g/personal/chris_wigglemylegs_com/EVuLGZH-LBlNqGs2rJhk_2IBwcMjuGNH9ypCXbuBgUZrqQ?e=ype614](url)

**Comment by Chris8top8he8r** [comment]
I guess I should complain more often.  I submitted post above and somehow this morning things are working somewhat better.  After months of LineageOS updates OTA and many reboots and Debug Submit button never working, which disallows opening a ticket with Signal, Debug Submit button just worked for me.

[Click here for fresh, new, haven't-had-one-in-a-long-time, Debug log link.](https://debuglogs.org/android/5.40.4/3f9245fac636e53abb8632803b8d1012897d2e8b50c122d199a619185abbf7cf)

Looking at the opening data in Debug log makes me scratch my head about the memory and metered connection.  I pay about $92 per month to AT&T for UNLIMITED voice, data, and texting.  Constantly feel throttled.  Can anyone confirm what the debug log is telling me here about a metered connection?  Where is Signal getting that data?  Also, can I read somewhere about constraints?  And if I'm reading it correctly, Signal is saying I've got 2.7 GB total memory, and less than 1 GB is available, but lowmem is false.  Do I need another cup of coffee?

Again, from my Microsoft Office 365 OneDrive for wigglemylegs.com, here is the screen grab of the opening of the Debug log with highlights for areas I don't understand, followed by grabs of other perspectives of memory for my A/B Android phone.  Does this data make sense?

[Debug Screengrab with marked highlights.](https://wigglemylegscom-my.sharepoint.com/:i:/g/personal/chris_wigglemylegs_com/EXIAz7eDL-JDiMevcc9k_P8Bt6wJPx3lK76m88hgjZs0PQ?e=Mf4ZOx)


[Looking at Android Settings under Storage - Top of Scroll.](https://wigglemylegscom-my.sharepoint.com/:i:/g/personal/chris_wigglemylegs_com/ESQtxpyh7VlLnbmtheOnq8MBwGZU4A0nYFAUJtKBb926rA?e=4nyNcU)


[Looking at Android Settings under Storage - Bottom of Scroll.](https://wigglemylegscom-my.sharepoint.com/:i:/g/personal/chris_wigglemylegs_com/EXb1b53xA0FBqGR2FOroMz0BZDer_G5NYXujbhOd4qKWyQ?e=fb4flt)


[Looking at Android Properties from Windows File Explorer](https://wigglemylegscom-my.sharepoint.com/:i:/g/personal/chris_wigglemylegs_com/EaxGt9d-UPpDsdE27M9B6U0BN-EIEj4d1bqMhnqQ9GRelQ?e=1KbQAz)
