### ISSUE TITLE
iOS Unable to send message

### ISSUE THREAD

**Issue by stevenwcy** [signalapp/Signal-iOS#5393]
After I linked a iPad as the new device, my phone then unable to send any message and receive messages with minutes delay.

I tried to unlink all devices but the application freezed after clicking the remove button.

Is there any method I can try to recover the status without erasing my chat history?

https://debuglogs.org/ios/5.42.0/fafe86cb41a583283b9f125f7e7f174da004d31d87658b265a774c379513d6fa.zip

**Comment by EvanHahn-Signal** [comment]
That's very strange. Sorry you're running into that!

What exactly happens when you try to send a message? Does a message appear, or does nothing happen? Is there a spinner? (If there _is_ a spinner, I'd like to know the message ID of one of the bad messages. You can get this by tapping and holding on a message, clicking Info, and then holding on the sent time. It will copy it to the clipboard.)

**Comment by EvanHahn-Signal** [comment]
Strange. It sounds like your issue is solved so I'm going to close this issue, but we'll keep it in mind in case we see similar reports.
