### ISSUE TITLE
Chats are still `stored in server` in disappearing message `after timeout`

### ISSUE THREAD

**Issue by tanishq-singh-2407** [signalapp/Signal-iOS#5460]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### **Bug description**
1. Imagine you just had a chat with your mate in `signal-desktop`, and `disappearing message` timeout was set for like `10mins`.
2. After like 1 day you opened `signal-ios` and what you see that all the messages are loading and getting deleted at the same time as timeout was set for `15mins`.
3. But my question why are they even loading??? It means they have been stored in the server somewhere and not got deleted after `15mins`???

### **What could be done?**
It' s oblivious, delete those message from server after timeout.

**Comment by tanishq-singh-2301** [comment]
Privacy was my only reason I joined signal!!
with this anyone could take my laptop or phone start a screen recording and record all the chats.

I think we could add a button which if the other user also want can create a peer to peer connection for chatting and stuff, no server needed.

**Comment by Sgn-32** [comment]
The disappearing time is encrypted in the message. The server does not know what kind of message it is.
Each device (main device and linked devices) has its own message queue.
When loaded from server to signal-desktop and you have read the message, signal-desktop sends a read receipts to all linked devices. So in the message queue of signal-ios there are now the disappearing message (with encrypted disappearing time) and your read receipts from signal-deskop.
signal-ios loads both messages and detects that you have read the message and deletes it.

But it seems that you have another issue, since loading the messages should be immediately (in background with internet connection) and not on opening the app.

**Comment by tanishq-singh-2301** [comment]
yeah this could be done.
**Do all the research in the backend server before sending anything to user.**

Do you know after what time my disappearing messages get deleted from the `server-queue`?

**Comment by dlis** [comment]
I always use a setting to delete messages after an hour on my iPhone. But I've just open my Mac where I was logged in some months ago, and it was so funny to see how a waterfall of "deleted messages" covering last months with all the media were downloading to my Mac and hiding in some seconds. There were "deleted messages" for all the period of non-using my Mac (some months)
