### ISSUE TITLE
App language broken

### ISSUE THREAD

**Issue by lang1s** [signalapp/Signal-iOS#5539]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
- Signal-Android 6.10.9 - no bug
- Signal-Desktop 6.4.1 - no bug
- Signal-iOS 6.11.0.11 - this bug

### Steps to reproduce
- iOS Settings > General > Language & Region
- set preferred language > Estonian
- launch Signal

**Actual result:**
- Signal-iOS does not show almost any of the UI text in Estonian.
- Only a fraction of the Donate to Signal process is recognizable.

**Expected result:**
- UI works again like it did, and like it does on Android & Desktop.

### Device info
**Device**: iDevice X

**iOS version**: 16.3

**Signal version:** 6.11

**Comment by lang1s** [comment]
Signal-Android 6.13.6 - ok
Signal-Desktop 6.9.0 - ok
Signal-iOS 6.12.0.7 - buggy

**Comment by lang1s** [comment]
Signal-Android 6.13.7 - ok
Signal-Desktop 6.10.1 - ok
Signal-iOS 6.16.0.7 - buggy

**Comment by lang1s** [comment]
Signal-Android 6.14.5 - ok
Signal-Desktop 6.11.0 - ok
Signal-iOS 6.17.0.10 - broken

**Comment by lang1s** [comment]
Signal-Android 6.15.3 - ok
Signal-Desktop 6.13.0 - ok
Signal-iOS 6.19.0.16 - broken

**Comment by lang1s** [comment]
Signal-Android 6.17.3 - ok
Signal-Desktop 6.14.0 - ok
Signal-iOS 6.20.0.14 - broken

**Comment by Miguel-Signal** [comment]
Hello @lang1s 

Apologies for the delay in getting back to you regarding this. The lack of Estonian support for iOS is expected, as we decided to showcase only Android and Desktop for several languages, one of these being Estonian (due to usage metrics). Thank you for the cultural and historical context that you provided - we will consider this when reassessing supported languages per platform.
