### ISSUE TITLE
When tapping on the "Audio" view on a reply the relevant Audio doesnt flash to indicate which one they replied to. It does on macOS

### ISSUE THREAD

**Issue by marcosrdz** [signalapp/Signal-iOS#5547]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by d108** [comment]
![highlight_recipient](https://user-images.githubusercontent.com/3375306/222574032-bc17740b-ece8-4bf8-b47a-6ebb8b6d0762.gif)

@marcosrdz Does the animated gif in this reply describe the behavior you seek on iOS?

**Comment by marcosrdz** [comment]
That is correct

**Comment by d108** [comment]
Looking into this more, we can break the problem into two parts.

1. The highlight idiom from the desktop platform does not appear on iOS. 
2. Navigation to the original message from the quoted reply preview above the input area is not implemented in iOS as on the desktop version.

Regarding what we can call a bug, fixing the missing navigation in (2) might have a better chance of getting approved because it matches existing behavior when selecting a reply in the chat list.  

On the other hand, the desktop version implemented for Windows, Linux, and macOS through Electron represents a different platform. Our arguing for interface idioms to be applied equally across platforms might fall outside the scope of a bug fix.

Therefore, we can propose enabling navigation from a quoted reply preview as one step toward fixing the problem you found. 
The benefit we can gain is the ability to quickly navigate back to the original message context of our active reply. 

Please review the animated image demonstrating a possible fix for (1) and share your thoughts on re-focusing this issue. The GIF shows the following interaction flow:

- Reply to a message beyond the visible range of the last one.
- Scroll to the end.
- Select the quoted reply preview to scroll back.
- Enter a test message.
- Select the reply quote to again scroll back to its original context.

![quoted reply select to go back to original message context](https://user-images.githubusercontent.com/3375306/222933417-06f7f92d-786a-472a-8c3d-3345bea96457.gif)

**Comment by marcosrdz** [comment]
It becomes confusing when youre responding to a voice message. If the person sent like 3 voice messages theres no way to tell which the reply is for.

**Comment by d108** [comment]
@marcosrdz Your explanation makes things clearer. If we can highlight the messages, it will reduce ambiguity when the quoted replies have a non-distinguishable appearance, such as with audio.

Please review the animation shared below. Then, we can discuss the changes as proof of concept. How do you find they will address the problem?

It demonstrates the following features:

- Navigating to the original message from a reply.
- Highlighting of the original message.

We have two separate cases for scrolling:

1. The original message is out of view and requires scrolling to show it.
2. The original message is wholly or partially in view. Some scrolling may occur.

There exist some additional items to resolve before a PR is possible, including: 

- The tap on the reply doesn't always register the first time, shown at the end of the recording.
- Solving why no background animation appears for image attachments most of the time, but not shown.
- Handling background animations for gradients.

![proof of concept highlighting](https://user-images.githubusercontent.com/3375306/223175855-1f7c85ac-e539-4c8c-9dd7-b3162f326431.gif)

**Comment by toubul** [comment]
The issue is still relevant on the current iOS version. 

https://github.com/user-attachments/assets/21f66e39-31ed-4d22-9047-84829d93bce1
