### ISSUE TITLE
all my user data is inacessbile because Signal app is bricked, stuck in "Transfer Account & Messages" function

### ISSUE THREAD

**Issue by UX-GURU** [signalapp/Signal-iOS#5551]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I open the Signal app, I am unable to access any of my data, including messages I have sent, and messages I have received.

### Steps to reproduce
- don't update the Signal app for several months
- at some point the Signal App will tell you that you need to update Signal.  So you install a new version of Signal from the App Store, and then the next time you open Signal, you get a message telling you that you've been logged out of your Signal account
- close the Signal App
- open the Signal App

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
-Signal app is bricked, stuck in "Transfer Account & Messages" function

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
-Signal app should not be bricked, should let you read your ....... messages, your user data, etc., without needing to re-activate your account, which you CAN NOT DO by the way, because even though you still have your same phone number, Signal verification won't work for that phone number anymore because apparently Signal developers aren't getting paid enough millions of dollars?  I dunno how to explain this level of fail.  Try to activate on a different phone number and that will ONLY WORK IF YOU AGREE TO DELETE ALL YOUR MESSAGES.

### Screenshots
why bother with screenshots, no one's going to fix this anyway.

### Device info

**Device**: iPad Air

**iOS version**: 12.5.7

**Signal version:** Signal is self-bricked, so I can't get the version number.

**Comment by UX-GURU** [comment]
![bricked signal-2023-02-28-094505](https://user-images.githubusercontent.com/126533007/221904638-d729ed02-1218-451f-bc61-d07f3660e73e.jpeg)

**Comment by Good-Sig-Dev** [comment]
Hello UX-Guru,
I am one of the Developers here on the Signal project.  Please rest assured that we care about user experience, and we definitely do not want to randomly and arbitrarily lock users out of accessing their data.  I apologize that this has happened to hundreds of thousands of users including yourself.

Please rest assured that we're working on making Signal better, and you should again have access to your Signal messages with our next major update to be released in a few weeks time around end of March or early April, most likely on 4/1.

To check if the latest release of Signal will allow you to regain access to your database of sent and received messages, please force-quite the Signal App and then update the app via your device's App Store interface.  Please keep trying, because I'm sure that eventually we will let you get your messages back.

In the meantime, until we decide to let you regain access to your messages, you can always try importing and reverse-engineering your local Signal database with your favorite SQL tools.  Unless we've encrypted it.  

Good Luck!

**Comment by UX-GURU** [comment]
> Please rest assured that we care about user experience, and we definitely do not want to randomly and arbitrarily lock users out of accessing their data.

Well, umm thanks I guess.  But if you don't want to lock users out of accessing their messages, then why is this "transfer account & messages" activation screen programmed to do specifically that?  There's no option to bypass this screen and go to the regular user interface.  It's patently absurd... The application arbitrarily decides the user needs to re-activate, and so it bricks all functionality until the user obeys.  And meanwhile, the damn activation functionality is broken, so the user is screwed.  All the user's messages - gone!  Who in their right mind would use Signal or recommend it to their friends knowing that the entire application can self-brick at any random time?  More importantly, who in their right mind would program an app to behave this way?  What kind of psychopathic anti-social mentality does this?  And how can this same psychopathic mentality be trusted not to provide backdoor access to the NSA?  At least if it was ransomware, I could pay the ransom to get my app back.  Is there some Signal Dev I could pay off to let me back into the app?  This is beyond insane.
