### ISSUE TITLE
Tall images are obscured by iOS notch

### ISSUE THREAD

**Issue by sdgluck** [signalapp/Signal-iOS#5635]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Tall images viewed within Signal are obscured by the notch.

### Steps to reproduce
- send an image whose height is equal or larger than the iOS device viewport
- view the image

**Actual result:** the top of the image is obscured by the notch

**Expected result:** images are displayed within the safe area of the iOS device (https://developer.apple.com/design/human-interface-guidelines/layout#)

### Screenshots

Screenshots taken on an iPhone with a notch do not display the notch, so it is not possible to provide a screenshot of this behaviour.

### Device info

**Device**: iPhone 12

**iOS version**: 16.5.1

**Signal version:** 6.33.0.9

### Link to debug log

n/a

**Comment by Miguel-Signal** [comment]
Hi @sdgluck,

Can you please update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) (v6.35) and see if this resolves the issue? Then, if the issue is still happening, could you send in new logs from this new version as well as the dimensions of the photo?

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link, then open this email, long-press and choose paste to paste the link.

To get the dimensions of a photo, open it in the Photos app and tap the information icon.

**Comment by sdgluck** [comment]
I updated to version 6.35.0.9 and the issue is still present.

The problem can be reproduced using the image below:

https://github.com/signalapp/Signal-iOS/assets/3265173/57d183ed-5e54-449d-bf7e-fb6d32aba865

Image dimensions: 756x1600

Debug logs:

https://debuglogs.org/ios/6.35.0/faf49676d8955ce9beb3782830c8abd2e5380fd214852d727ae4d43bafe0ea27.zip

**Comment by Miguel-Signal** [comment]
We are not able to recreate this issue on the latest Signal version (v6.40). Viewing [your image](https://github.com/signalapp/Signal-iOS/assets/3265173/57d183ed-5e54-449d-bf7e-fb6d32aba865) renders correctly within the safe area of the screen. Can you update to the latest Signal version and let me know if it resolves the issue for you?

**Comment by sdgluck** [comment]
Having just updated to v6.40 as recommended, the issue is no longer present. Tall images now display within the safe area. Thank you. I will close this issue now.
