### ISSUE TITLE
I can screenshot the pictures that I should only look at 1 time

### ISSUE THREAD

**Issue by Gamius00** [signalapp/Signal-iOS#5650]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by FleetAdmiralJakob** [comment]
> Hi @Gamius00 
> 
> Thanks for the feature request for a screenshot alert. It's kind of a losing effort. Someone can always take a picture of the screen with another phone, camera, or device.
> 
> We would encourage you to provide feature requests on the community forum also, which can be found here: https://community.signalusers.org/

Hi, but every other app with one time photos has this feature. And I think there is a built-in API from the platforms to allow this. Only because there are ways around it this shouldn't be a reason to not care about it at all. 

Sure, if someone really wants to screenshot something he can still do it someway but I think this would eliminate 99% of these cases.

I think this issue should be reopened.

https://developer.android.com/security/fraud-prevention/activities

https://developer.android.com/about/versions/14/features/screenshot-detection
