### ISSUE TITLE
No way to recover from "Could Not Load Database"

### ISSUE THREAD

**Issue by jsonfry** [signalapp/Signal-iOS#5658]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When I open the app the app I get the error "Could Not Load Database" "Signal can't launch. Please send a debug log to...".

The problem is that I have no way to recover this, no option to start again, clear the database etc. Even with uninstalling the app fully (not just removing from homescreen) and reinstalling from the app store, the problem still persists. (Signal must be keeping some data around between installs). 

Had this problem for many months, have emailed support a while ago but never heard back.

### Steps to reproduce
For me,
- Open the app

**Actual result:**
I see the error described above

**Expected result:** 
Ideally not corrupt the database 😅 but when you do, be given the option somehow to clear the database and start again, even if it means losing all messages.

### Screenshots
![IMG_44724D402CAD-1](https://github.com/signalapp/Signal-iOS/assets/368400/0ae85c8b-1bde-4631-844b-06911bdb8efb)

### Device info
**Device**: iPad Pro 12.9-inch 3rd Generation (A1876)

**iOS version**: 16.6 (20G75)

**Signal version:** 6.39

### Link to debug log
https://debuglogs.org/ios/6.39.0/55f9af4b82e8c95383053a7fcf21a0bd2d2391cb094958b7339e898a4305576f.zip

**Comment by sashaweiss-signal** [comment]
@jsonfry, if you're open to helping us debug this issue, would you mind reaching out to Signal support (https://support.signal.org/hc/en-us/requests/new) to connect with us?

**Comment by jsonfry** [comment]
I have filled out the form, I look forward to hearing back from you!

**Comment by jsonfry** [comment]
Just wanted to check the support request had made it to you?

**Comment by Miguel-Signal** [comment]
@jsonfry Yes we received it! thank you.

**Comment by gonultasbu** [comment]
I think this issue is related with this as well:

https://github.com/signalapp/Signal-iOS/issues/5395

I am also having a slightly different issue with corrupted database, essentially bricking the app for me without any way to recover since 2023 May on iPhone. 

Through personal research, I have come to the conclusion that Signal uses the local keychain on iOS devices, which is persistent and app removal does not remove the app data. If your Signal database is somewhat large, you can verify this by uninstalling the app and checking the storage statistics and see that data usage does not change. Local keychain cannot be modified and tampered by the end user, therefore removing the Signal database is not possible without going through a full factory reset, which is extremely frustrating because that does not even let me accept the data loss and go about using Signal again.

@sashaweiss-signal I would be willing to help you debug this problem, if needed. I have sent a debug log and further details to Signal support in May but have not heard a more detailed response since.

**Comment by jsonfry** [comment]
Yes that is exactly my experience too. Signal on my iOS device is unusable.

I’m not too bothered about losing the messages, so even a “wipe database” button (after pressing several warnings) would solve this for me.

**Comment by gonultasbu** [comment]
still active

**Comment by TarikBerk** [comment]
Having this issue right now and wonder if there’s a fix.

**Comment by robertsmd** [comment]
@Miguel-Signal @sashaweiss-signal @TarikBerk @jsonfry 

I'm also having the issue. Would appreciate help.

**Comment by baknu** [comment]
Unfortunately, I am also running into this nasty issue since last week. It *seems* after an iOS update the Signal database got corrupt and the Signal app is unable to repair/recover it. Help would definitely be appreciated.

**Comment by mihaelacr** [comment]
+1, hitting this too, more info [here](https://github.com/signalapp/Signal-iOS/issues/5811#issuecomment-2480544366).

**Comment by erica-bishop** [comment]
I'm also having this issue - submitted the debug log to support@signal.org. I've tried uninstalling and reinstalling multiple times with no avail

**Comment by sashaweiss-signal** [comment]
> I'm also having this issue - submitted the debug log to [support@signal.org](mailto:support@signal.org). I've tried uninstalling and reinstalling multiple times with no avail

Hi @erica-bishop. The fact that a full uninstall and reinstall doesn't solve this is very concerning and points to an iOS issue, as on uninstall all our app data is supposed to be wiped. Could you please follow up in your email to support with a link to this Github issue, as we'd love to follow up and learn more (and potentially report an issue to Apple).

**Comment by sashaweiss-signal** [comment]
Hi @erica-bishop. Thanks again very much for your help – we've submitted a bug to Apple about our app data not being cleared properly on uninstall.

In the meantime, we've merged changes into version 7.77 (currently available in beta: see [here](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-7-77-release/71585/9) for more details) that will let you manually wipe the corrupted app data and hopefully get you back to using Signal.

Very sorry again that this happened, and thanks again for your help and as always for being a Signal user.

**Comment by nclm** [comment]
Hi, a friend had the same issue and we couldn’t communicate the last few days until she realised she wasn’t getting my messages because of this. I feel like there are two issues:

- Recovering from "Could Not Load Database", which is discussed here.
- "Could Not Load Database" itself! How come Signal can get corrupted like this on iOS?
