### ISSUE TITLE
When submitting bug report via mobile app signal looks for the "Mail" app

### ISSUE THREAD

**Issue by 211217613** [signalapp/Signal-iOS#5668]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can't submit a bug report from the iOS mobile app because I don't have the default iOS Mail app installed

### Steps to reproduce
- Uninstall the default iOS mail app with another mail app you use.
- try to submit a bug report
- error message "Failed to open mail app"

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- The expected behaviour should be that Signal would use the default mail app you have setup in settings. I use spark and want to submit a bug report via spark.

### Device info

**Device**: iPhone 13 mini

**iOS version**: 17.0.1

**Signal version:** 6.42.0.18

**Comment by ddxor** [comment]
@211217613 can you provide a screenshot of the screen specifically that you're referring to? - Aware this probably affects many parts of the app, but would be good to start looking where you're at.

**Comment by 211217613** [comment]
![IMG_2413](https://github.com/signalapp/Signal-iOS/assets/7006850/11c30497-74c8-4c55-abec-004e70de989a)
![IMG_2414](https://github.com/signalapp/Signal-iOS/assets/7006850/366aa6fc-5959-47a6-a7d0-dfc3d8c791c6)

**Comment by ddxor** [comment]
@211217613  thank you. Can you also confirm the email client you use and confirm whether it's set as the default mail app? (Settings > your mail app > Default mail app.

**Comment by ddxor** [comment]
This is an interesting one. Looking at `ComposeSupportEmailOperation:176` the app is using the UIKit handler to open a `mailto:` link. Since this appears to be basic UIKit behaviour, I would expect any e-mail app registered as a `mailto:` handler to work fine.

@211217613 can you confirm if other `mailto:` links are working for you? For example, the e-mail link embedded on a public website's contact page.

I can't easily debug with spark specifically because I don't have the ability to get their e-mail client into iOS Simulator. I'll need to try and source some test hardware to debug further.

**Comment by 211217613** [comment]
I can't find a website that calls the iOS installed email app. Most of them have input fields on the website itself.


I'll keep looking.

**Comment by 211217613** [comment]
still an issue.
