### ISSUE TITLE
Fail to transfer from old iPhone 8 (iOS 16.7) to new iPhone 15 (17.0.2)

### ISSUE THREAD

**Issue by M00nBase** [signalapp/Signal-iOS#5670]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I tried to transfer my data from an old iPhone (iPhone 8) to a new iPhone (iPhone 15), however, it does not work as excepted. I followed the offical guide and I tried all the suggestions on the internet such as removing the case, touching the phones from different position for more than 50 times. It ends up getting "The transfer couldn't complete, please ensure your devices are near each other and try again.".

Wifi, Bluetooth and local network are all on. Multiple Wifi AP changed (I don't think is it relevant as it uses Wi-Fi direct?). 

I know there are some issues already posted, but the issue didn't have a solution before it was closed: https://github.com/signalapp/Signal-iOS/issues/5450

From the logs, there is a exception: 
iPhone 15: [DeviceTransferService+Manifest.swift:162 handleReceivedManifest(at:fromPeer:)]: Unexpectedly received a very large manifest 
iPhone 8: [DeviceTransferService.swift:244 failTransfer(_:_:)]: Failed transfer Lost connection to new device

I already submitted a request but not getting any respone. The data from my old phone is about 6.55 GB. Please let me know if there is any more infromation I could provide to fix it. Thanks you.

### Steps to reproduce
- Open Signal on new iPhone 
- Open Signal on the old iPhone
- Enter the PIN on the new iPhone, Click "Transfer from iOS Device"
- Check "Next" on the old iPhone from the "Transfer Account"
- Scan the QR code on the old iPhone 

**Actual result:** The old iPhone displays "Connecting..." for a while and eventually shown "The transfer couldn't complete, please ensure your devices are near each other and try again.".

**Expected result:** The transfer process should be started. 

### Screenshots

![IMG_2572](https://github.com/signalapp/Signal-iOS/assets/117377756/bf94f1fc-5aa4-4191-accf-a9139821a571)

### Device info

**Device**: iPhone 8 and iPhone 15

**iOS version**: iOS 16.7 and iOS 17.0.2

**Signal version:** 6.42.0.18

### Link to debug log

[iPhone 8.zip](https://github.com/signalapp/Signal-iOS/files/12747028/iPhone.8.zip)
[iPhone 15.zip](https://github.com/signalapp/Signal-iOS/files/12747029/iPhone.15.zip)

**Comment by youjackal** [comment]
Same Here, with iPhone 12 Pro Max > iPhone 15 Pro Max

**Comment by youjackal** [comment]
I'm encountering the same problem. My Signal data on my phone is around 20GB, and I'm wondering if this could be the reason why the new phone isn't accepting it. My family member had a similar experience, but they only had 11GB of data, and the transfer went smoothly. Interestingly, many of my friends who have over 20GB of data have also faced this "Failed transfer" issue.

I really hope the developers can address this problem. Since the app doesn't offer any backup or export function, it's concerning to think that all our data could be lost when we switch to a new phone.


[iPhone15ProMax.zip](https://github.com/signalapp/Signal-iOS/files/12776479/iPhone15ProMax.zip)
[iPhone12ProMax.zip](https://github.com/signalapp/Signal-iOS/files/12776480/iPhone12ProMax.zip)

**Comment by M00nBase** [comment]
I tried to delete media files from my old phone, it still got the "Unexpectedly received a very large manifest" expection. Therefore, I don't think the data size is the case. But why is my old phone created such larger manifest file while others don't, and therefore it hit the safe garud for only accpecting manifest files less than size of 1024 * 1024 * 10.

**Comment by chrisskiiii** [comment]
SAME.
The old iPhone displays "Connecting..." for a while and eventually shown "The transfer couldn't complete, please ensure your devices are near each other and try again.".

**Comment by rsik** [comment]
Classic, every year, same issue.

Power off both phones, turn on, do not open anything but Signal on each phone - then start transfer on new phone. This silly voodoo dance works for me the same way each year 😭

Do I agree with it? Hell no. We need better transfer options! (like via cable, or export)

**Comment by chrisskiiii** [comment]
HELP!!!

**Comment by harry-signal** [comment]
Hi folks! Thanks for reporting these issues. So, the good news:
1. I've made some general improvements to device transfer in recent releases; if you're having issues try updating and that may help!
2. The specific "very large manifest" issue experienced by OP will be fixed in the next release (beta this week, and AppStore ~next week.) Sorry about this one, but please hold tight and you should be able to transfer soon!

The bad news: device transfer stands somewhat on shaky ground in general, and despite recent surface improvements, it can still often fail. Your best bet is to restart signal on both devices, make sure wifi/bluetooth are on and you have a stable network, and keep them close together as they do the transfer. And, well, be patient with it. :)

Long term, hopefully we can make some more fundamental improvements!

**Comment by youjackal** [comment]
Hi Harry,

Thanks for bringing in the good news. Since I'm still using Signal on my cell, I'm hopeful that the upcoming update will finally fix the issue for good. On the flip side, this issue has been around for a very long time. I really hope Signal can find a more stable way to transfer data without failures.

Nevertheless, it's truly a relief to see your reply. Thank you so much!

**Comment by M00nBase** [comment]
After updating to 6.45, the transfer works without error although it took me a second try. I suggest restarting both phones before doing the transfer.

Thanks for the support from Signal's team and Harry.

**Comment by bjornte** [comment]
Still having this issue. No remedies work for me. (Have restarted multiple times, switched Wi-Fi networks, putting the phones together in many orientations, lying them next to the router, max brightness, deleted content)

**Comment by strawbale** [comment]
Same issue.
Old phone: 7+
New phone: SE (2022)

**Comment by arndjan** [comment]
Same issue. Transferring from an iPhone 8 Plus to an iPhone 13 Pro. The old iPhone freezes as soon as it scans the QR code.

All settings are as they should be. Same WiFi network.

**Comment by max-signal** [comment]
@bjornte, @strawbale, and @arndjan this issue was about a manifest limit that was too low, and we believe that issue has been resolved. If you are still having issues with device transfer, they are likely a separate root cause.
