### ISSUE TITLE
Selected skin tone isn’t remembered for emojis

### ISSUE THREAD

**Issue by BergenLarsen** [signalapp/Signal-iOS#5678]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After selecting an emoji of a specific skin tone when reacting to a message in a thread, the skin tone isn’t remembered.

### Steps to reproduce
- go into a chat
- long press on a chat bubble
- select the more emojis option
- choose a reaction emoji, eg thumbs up, with a skin tone that’s not yellow (default)
- long press on next chat bubble, skin tone is not remembered for the quick reaction emojis

**Actual result:** 

skin tone is *not* remembered for the quick reaction emojis when you long press on a chat bubble. 

**Expected result:**

skin tone *is* remembered for the quick reaction emojis when you long press on a chat bubble. 

### Device info
**Device**: iPhone 14 pro

**iOS version**: 17

**Signal version:** 6.44.0.10

**Comment by hoseiocean** [comment]
Curently on a train to the office, but from my first analysis, it seems that Signal doesn't retain nor even use skin tone preferences for emojis in quick reactions. This is likely due to how the emoji bar is initialized, not incorporating user's skin tone choices for emojis. The `InteractionReactionState` class, responsible for managing reactions, doesn't seem to account for skin tone preferences. Adjusting this, specifically ensuring `localUserEmoji` stores emojis with the user's preferred skin tone, could address the issue. I'll work on a more detailed solution to this bug later and share my findings with you.
