### ISSUE TITLE
Disappear setting deleted the messages by not the user name

### ISSUE THREAD

**Issue by SenthilManickavel** [signalapp/Signal-iOS#5683]
### Bug description
     In Android if I set the disappear message as 1hr, after 1hr both message and the contact name is deleted in chat list.

     But in iPhone, chat is getting cleared and not the contact name in chat list. This should be improved to increase the privacy. Please let me know when this will be fixed.

### Steps to reproduce
- Set disappear chat as 1hr for a person
- have a chat and notice after 1 hr
- messages are cleaned, but user name still seen

**Actual result:** chat deleted but not the user name

**Expected result:** user name should be deleted

### Screenshots
NA

### Device info

**Device**: iPhone 14

**iOS version**: 17.0.3

**Signal version:** 6.45

**Comment by FU3X** [comment]
no that's a horrible idea, that's not a bug, and that's supposed to be how signal works. i don't see how it boosts privacy. you are supposed to hard save contacts on your phone anyway

**Comment by Miguel-Signal** [comment]
@SenthilManickavel Does the iOS user still have previous messages in the same chat? In this scenario, the chat thread in it's entirety would not disappear from the chat list if previous messages still exist in the chat thread.

This is the same on both Android and iOS.

**Comment by SenthilManickavel** [comment]
> @SenthilManickavel Does the iOS user still have previous messages in the same chat? In this scenario, the chat thread in it's entirety would not disappear from the chat list if previous messages still exist in the chat thread.
> 
> This is the same on both Android and iOS.

As I said chat messages are getting deleted, but the chat thread is seen.

**Comment by Miguel-Signal** [comment]
@SenthilManickavel Do you have previous messages in this chat thread and does the iOS user have previous messages in this chat thread? 

It would be helpful to know if the iOS user still has previous messages in the same chat thread. Because if so, this would be the expected behavior. Messages sent/received **before** the disappearing timer was set are not supposed to disappear. 

Please instruct the iOS user to provide their debug logs (and a a screen recording of this issue, if possible) to support@signal.org so we can look into it further.To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.
