### ISSUE TITLE
Updating story recipients gets overridden

### ISSUE THREAD

**Issue by mthld** [signalapp/Signal-iOS#5691]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Updating the "Only Share With..." recipients list for "Who Can View This Story" works but gets overridden back to its previous state after some time.

### Steps to reproduce
1. Open Signal application
2. Go to the Stories tab
3. Tap "My Stories"
4. Tap "Privacy" on the top right corner
5. Select "My Story"
6. Modify the list of recipients in "Only Share With..."
7. Remove a few of them
8. Tap "Save" on the top right

**Actual result:** The story recipient list looks like it has been updated, the number of viewers matches. However, after some time (in my case, a few hours?) the number and the actual recipients are rolled back in their previous state.

**Expected result:** The recipients should be properly updated and shouldn't roll back to their previous state. It's a serious trust issue!

### Screenshots
![IMG_3F1A3CB5BF93-1](https://github.com/signalapp/Signal-iOS/assets/41020854/97e5844c-7c30-4cca-ab93-cf70a836bbc2)

### Device info

**Device**: iPhone SE 2nd generation

**iOS version**: 17.0.3

**Signal version:** 6.46.1.0

### Link to debug log

Not relevant as I don't know how to trigger the bug itself.

**Comment by harry-signal** [comment]
Hi! Sorry for the delayed response. Do you have any other linked devices besides the desktop? (e.g. do you have a linked iPad?)

**Comment by sashaweiss-signal** [comment]
That's helpful, thanks! The next useful step would be to collect debug logs from both the iPhone and Desktop if you notice this happen again – without those, there's not a ton we can tell.

**Comment by sashaweiss-signal** [comment]
To collect debug logs for both iOS and Desktop you can check out [these steps](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports).

We only keep a certain amount of debug logs – they age out after a set time period or if the log file grows too large. They're generally sufficient for us to investigate issues assuming the report is relatively timely!

As a next step, I recommend enabling debug logs on both devices and leaving them enabled. Then, since this isn't an issue we can intentionally reproduce, collect the logs using the steps in the article above as soon as you notice the issue again.

Thanks in advance!

**Comment by cityrolr** [comment]
I have the exact same problem since I changed the story privacy settings once. My setup is similar with an iOS and MacOS client. 
My guess is that it has something to do with the desktop client not being able to toggle between the different settings because "All Signal connections" is not clickable. I recorded a video where you can see the problem, maybe that helps to debug.

https://github.com/signalapp/Signal-iOS/assets/13933169/631c478e-bc78-4cc1-91f8-2cf821453aba

**Comment by vnj0x61** [comment]
@mthld i tried to reproduce the error but was not able. I think because i had set it over the Desktop. Can you try it in this direction? Do you have the same problem? 

Other note:
After all tests i thought to deactivate the Stories in Desktop Client and reactivate might help. Now the stories are gone in the Desktop Client. I am not able to reactivate, other bug BUT maybe it is a workaround. 
1. Deactivate Stories in Desktop Client
2. Activate Stories in iOS App

**Comment by cityrolr** [comment]
> Other note:
> After all tests i thought to deactivate the Stories in Desktop Client and reactivate might help. Now the stories are gone in the Desktop Client. I am not able to reactivate, other bug BUT maybe it is a workaround.
> 
> Deactivate Stories in Desktop Client
> Activate Stories in iOS App

Tried this as a workaround, the desktop client doesn't reactivate stories as you said but also the iOS client sets itself to one of the options where some people are excluded.

**Comment by harry-signal** [comment]
> @harry-signal, @sashaweiss-signal, anything useful in those logs I shared?
> 
> The issue is still happening and it's quite worrying to not know what content I might be sending to whom. 😕

@mthld  Really sorry this is happening! This is quite a tricky issue as there's lots of different things that could be going wrong. Sorry to have to enlist your help to debug, but it would be very helpful if you could try some stuff out! We are unable to reproduce the issue on our own accounts.

Could you try:
1. Reset the recipients to All Signal Connections on your phone
2. Launch signal on desktop and verify my story settings are set to All Signal Connections
3. On your phone, change it to "Only share with..."
4. Relaunch (quit + reopen) signal desktop, and see if it updates (giving it a second or two to catch up)
5. On desktop, change it to a _different_ setting, "All Except..." (pick whoever)
6. Relaunch (force quit + reopen) signal on your phone and see if it updates (again giving it a second or two)

If you can, let me know what happens on steps 4 and 6! It would be helpful to know if the update is being lost on its way from the phone to desktop, or on its way from desktop back to the phone!

**Comment by harry-signal** [comment]
Update (and sorry if you were midway through the debugging steps I asked you to do above!): we've found the root cause!

Thanks for reporting this and helping us uncover the root problem! There should hopefully be a fix going out in a nearby Desktop client release. (May be slightly delayed by American holidays this week)
