### ISSUE TITLE
Message History on iPhone gone after reset, still available on relinked Desktop, does not sync to iPhone

### ISSUE THREAD

**Issue by BlkPingu** [signalapp/Signal-iOS#5696]
### Bug description

After resetting iPhone with Signal, history was gone. After relinking to MacOS again, it shows that Desktop still has full history. The history however does not sync to iPhone, but new messages do.
 
### Steps to reproduce
- send messages to anyone
- link to desktop
- display messages on both devices
- reset iPhone
- install Signal on fresh iPhone
- relink desktop to fresh Signal
- history on Desktop goes back to start of conversation, empty chat on iPhone
- send message to contact
- view messages getting displayed across all linked devices

**Actual result:** iPhone missing history, but Desktop does not

**Expected result:** The history should sync back to iPhone after it was reset since its available on at least one device

### Device info

**iOS version**: 17.1
**Signal version:** 6.48.0.14

**macOS version**: 13.4.1
**Signal version:** 6.37.0

**Comment by Miguel-Signal** [comment]
Hi @BlkPingu 

When you reset your iPhone you are deleting your message history from that device. After a reset you can register your phone to your existing account using the same phone number and previously created PIN. Your account information and Signal contacts should then be loaded, but as previously mentioned the chat history will not be there. You can then re-link your other devices.

Signal is designed to keep your data in your hands rather than ours. Signal uses end-to-end encryption so that we never have access to the contents of the messages you send. This means Signal does not keep a copy of your message history and your messages are only on your devices. An iTunes or iCloud backup does not contain any of your Signal message history.

An account and chat history transfer only takes place between the primary device (old phone) and its replacement (new phone) using the in-app transfer flow. To see an example of the transfer process,[ please watch this animation](https://support.signal.org/hc/article_attachments/360075954831/ios-transfer-animation-small.gif). Cross-platform chat history transfer (specifically any combination between Desktop <-> iPad <-> iPhone <-> Android) is not currently supported. However, we know it's an often suggested feature, so I'll make sure to bring this request to our Product Team's attention.

**Comment by NiklasBr** [comment]
> Signal is designed to keep your data in your hands 

This rings of hollow words, since you have explicitly denied us the possibility to back it up? Which would have prevented unwanted data loss like this.

**Comment by MalEbenSo** [comment]
+1 The lack of backup options opens many ways to lose data.

This is not about "keeping in the hands of users". 

I should be able to export my data from my device onto my device. All private.

**Comment by stanelie** [comment]
Better : data could be kept in encrypted form on the Signal servers to be synched whenever a user wishes it, it this user has the means to decrypt it. This solves everything.

**Comment by MalEbenSo** [comment]
> Better : data could be kept in encrypted form on the Signal servers to be synched whenever a user wishes it, it this user has the means to decrypt it. This solves everything.

This would be ideal. It protects against many (not all) causes of data loss, allows multiple devices to be in sync and includes the sync of chat history.

There's the issue of cloud storage costs. I would prefer to store data on a cloud service of my choice, whether that is my own NAS-based cloud service or another provider.

**Comment by eric-beyeler** [comment]
> I have since researched how this is handled on Android, and it turns out you allow backups on Android. I also read that the Team that implemented the file based backup is not very happy with it and also very burned out. Please make backups and history transfer a priority for the vast amount of iOS signal users, that keep losing their data because of the lack of platform support.
> 
> I keep seeing features and minor improvements added to Signal, like Stories. While I'm sure somebody loves and uses this feature, none of my many contacts do. To be frank: Features like stories are meaningless to me. While I don't expect feature parity between Android and iOS any time soon, even if desirable, from a users perspective, something as essential as a lack of a backup solution let alone cross device history transfer made me want to warn people about this aspect of iOS Signal.
> 
> People change, lose or break their devices all the time and chat histories are a deeply personal thing. It's more than just data. It's the the history and the life of a person. Memories to look back to. Sometimes even into what once has been and who once lived. I'ts worth finding a solution to preserve it.

10000% this ^^^^^
And give me the option to store it to the (obvious) iCloud ... or Signal's own servers ... let the user decide where they want it. It's encrypted, so it doesn't matter where it lives.
