### ISSUE TITLE
Push Notifications don't work on iPhone12 Pro

### ISSUE THREAD

**Issue by Karmox** [signalapp/Signal-iOS#5699]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Steps to reproduce
- Give the app notification permissions on the iPhone
- Give app permissions to run in background on the iPhone
- Turn off Battery-Save-Mode on the iPhone
- Send a message from another phone to the iPhone

**Actual result:** The iPhone doesn't get a push notification. On the sender phone also only one checkmark appears under the message. When opening the Signal App on the iPhone the push notification is appearing. 
When pressing the Renew-Push-Registration in the Signal App and having it open in the Background everything works as expected some minutes and then after doing other stuff it doesn't.

**Expected result:** A push notification on the iPhone should appear without opening the app first

### Device info
**Device**: iPhone 12 Pro

**iOS version**: 16.6.1

**Signal version:** 6.49.0.8

### Link to debug log
https://debuglogs.org/ios/6.49.0/737941eb5f92018ff87a7779b6315ff545c82ede2f65695071cac4c668cc251d.zip

**Comment by Miguel-Signal** [comment]
Hi @Karmox, could you please email us at spport@signal.org and reference this Github ticket? 

Thanks!

**Comment by 0xBADEAFFE** [comment]
I have the same problem with an iPhone 13 Pro.

**Comment by vnj0x61** [comment]
> I have the same problem with an iPhone 13 Pro.

Can you please provide more info? :) 

Device info
Device: iPhone 13 Pro

iOS version: 

Signal version:

**Comment by NinjaCheetah** [comment]
Having the same problem!

**Device:** iPhone 15 Pro

**iOS Version:** 17.2db3

**Signal Version:** 6.49.0.8

I do get some push notifications but they're very inconsistent. Throughout today I got 2 push notifications and missed somewhere in the area of 10 until the app was opened.

**Comment by 0xBADEAFFE** [comment]
> > I have the same problem with an iPhone 13 Pro.
> 
> Can you please provide more info? :)
> 
> Device info Device: iPhone 13 Pro
> 
> iOS version:
> 
> Signal version:
Of course, here are the requested informations.

Device info
- Device: iPhone 13 Pro
- iOS version: 17.1.1
- Signal version: 6.49.0.8

**Comment by random-zsh** [comment]
Having a similar issue on iPhone 14 Pro and Apple Watch, yet for me it's more intermittent. Typically, notifications show up on the iPhone, but they seldom do on the Apple Watch. I've attempted toggling all notification settings off and on, but without success. I have the same notification setting for other messaging apps, and the notifications appear both on the iPhone and the watch. I'm hesitant to reinstall the app since it seems I could lose the chat history in the process.

The notification is visible when I check the notification history, but the "beep" sound and vibration is not triggered when the notification arrives. I have the exact same notification settings for WhatsApp and Messenger and they work fine.

Device info:

- Device: iPhone 14 Pro
- iOS version: 17.1.1
- Signal version: 6.50.0.13

- Device: Apple Watch Ultra (2022)(A2684)
- watchOS version: 10.1.1

**Comment by pjolt** [comment]
Also not receiving any notifications on 13 Pro. I see that messages sent to it only get one checkmark until Signal is opened and only then does it change to two. Hopefully me adding mine here is ok, if not let me know and i´ll open a new issue. 

Device: iPhone 13 Pro
iOS version: 17.1.1 (21B91)
Signal version: 6.50.0.13

https://debuglogs.org/ios/6.50.0/96bc54daffef76514dc29362d89ba68e6b7b98215ef8182e942b7c8b812c4a65.zip

Device used in testing: 6S
iOS version: 15.8 (19H370)
Signal version: 6.50.0.13

https://debuglogs.org/ios/6.50.0/4422f993aff1780eea314d8ce3663c3b57bbd7c45af4ea76e6baa532d85a2c9f.zip

**Comment by carlmes** [comment]
Same issue on my iPhone, I don't get any notifications until I open the Signal app. Re-registering for push notifications didn't fix the issue. 

Device: iPhone 14 Pro
iOS Version: 17.1.1
Signal Version: 6.50.1.0 (latest from App store)

**Comment by emilyliu7321** [comment]
I'm also experiencing the same issue! Notifications work fine on my laptop, but not on my iPhone. I've also followed the steps outlined in [Signal's support article](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications#ios_notifications_troubleshooting) and it hasn't fixed the issue.

Device: iPhone 13 Pro
iOS Version: 17.1.1
Signal Version: 6.50.1.0

**Comment by pjolt** [comment]
Still an issue with 6.51.0.17.

**Comment by random-zsh** [comment]
Hey all, I've finally identified the issue and the solution. It turns out that I had the message sound set to "None" in the Signal settings. Strangely, when "None" is chosen, notifications don't seem to reach the Apple Watch.

Once I changed the Message Sound to "Note," notifications started working perfectly on both the iPhone and the Apple Watch. I can still, of course, silence them using the system-wide silence switch on the side of the iPhone.

So, the issue is resolved for me.

I'm not sure if it makes sense to have an option to disable the sound in the app itself, to be honest. Facebook Messenger doesn't have such an option at all, so maybe it disrupts the iPhone/Apple Watch notification system? 🤷‍♂️ I don't know, but the issue is fixed for me.

**Comment by patjolata** [comment]
Since the update yesterday, I seem to hit the same problem: Notifications are sometimes missing. Re-newing push or re-starting the device just helps for a short time. I opened a new issue for it this morning, but closed it again (https://github.com/signalapp/Signal-iOS/issues/5723). Here are my device and app informations and a debug log:

Hardware: iPhone
HID: 14,5
iOS-Version: 17.2 (21C62)
Signal-Version: 6.53.0.7
Diagnoseprotokoll-URL: https://debuglogs.org/ios/6.53.0/439a5b9be509ff2a73bf95730570cc8bf847e4e33a6df139049734ddcdf57c1d.zip
Region: de_DE

**Comment by 0xBADEAFFE** [comment]
> Hey all, I've finally identified the issue and the solution. It turns out that I had the message sound set to "None" in the Signal settings. Strangely, when "None" is chosen, notifications don't seem to reach the Apple Watch.
> 
> Once I changed the Message Sound to "Note," notifications started working perfectly on both the iPhone and the Apple Watch. I can still, of course, silence them using the system-wide silence switch on the side of the iPhone.
> 
> So, the issue is resolved for me.
> 
> I'm not sure if it makes sense to have an option to disable the sound in the app itself, to be honest. Facebook Messenger doesn't have such an option at all, so maybe it disrupts the iPhone/Apple Watch notification system? 🤷‍♂️ I don't know, but the issue is fixed for me.

The notification tone was not deactivated for me. The problem still exists.

**Comment by 0xBADEAFFE** [comment]
> Would anyone experiencing this issue **and** using an Apple Watch test something for us by removing Signal from the list of apps getting notifications to the watch and see if notifications on your phone improve?
> 
> Please also note that the Apple Watch is not officially supported, and we cannot guarantee its functionality.

Yes, I will deactivate the notification on the Apple Watch for testing and give feedback on whether there is an improvement. A few updates ago, the notifications also worked in combination with the Watch without any problems. Is official support planned for the Watch?

**Comment by mftcodes** [comment]
My partner's iPhone 15 Pro is having this problem as well. Have tried the notification permissions without change. It did stop for a couple weeks and now it's back again. She has no idea how to do any sort of problem solving, and doesn't like me playing on her phone... I break things in iOS... 

She had a iPhone 13, and upgraded to 15 Pro, and had the app transfer the data, which I think may be the problem. I can't convince her to do a back up and restore... also, this should just work.

**Comment by lukasvrenner** [comment]
My friend is encountering this issue as well, and does not have an Apple Watch. I'm not sure what her notification settings are, but I have sound set to "None" and everything works just fine, even with an Apple Watch

**Comment by 0xBADEAFFE** [comment]
@Miguel-Signal Unfortunately, deactivating the Apple Watch notifications did not solve the problem. The messages are still only displayed after opening Signal.

**Comment by NinjaCheetah** [comment]
Personally I had this issue resolve itself entirely without me needing to do anything, so I'm not going to be able to provide any more details, but I can say that I am an Apple Watch user and notifications are going to watch without any issues.

**Comment by Miguel-Signal** [comment]
We've had some reports of this issue resolving after a device restart. It would be helpful to know if this is the case!

**Comment by juliebugmtl** [comment]
A friend of mine is having the same issue and I can confirm her device is not receiving the messages until she opens the app.

iPhone 12 mini
iOS: 17.3.1
Signal version: 6.61.2.0
Debug logs: https://debuglogs.org/ios/6.61.2/3e2e67fbba127816b8bdc044a805efe465d1332b83543ac9f83fa5aa85ee5dde.zip

Of note, restarting her phone doesn't work, nor does re-registering push notifications. This happened with WhatsApp as well, but WhatsApp has now resolved and Signal has not. This has been going on since February 19th, 2024.
