### ISSUE TITLE
Long press on message should hide keyboard (or move context menu above/in front of it)

### ISSUE THREAD

**Issue by danispringer** [signalapp/Signal-iOS#5750]
**Signal iOS version 6.59**

As of now keyboard does not automatically hide when long pressing on a message, causing several options of said menu not to be visible/accessible at all:

![IMG_1335](https://github.com/signalapp/Signal-iOS/assets/19246409/ed43316e-917b-499e-a8b7-c1151842587c)

Here is how it SHOULD look, which is only how it looks as of now after MANUALLY hiding keyboard BEFORE long pressing on message:

![Screenshot 2024-02-08 at 6 20 21 PM](https://github.com/signalapp/Signal-iOS/assets/19246409/64562b5a-561e-4deb-8dd8-315eed8f2236)

**Comment by lukasvrenner** [comment]
I am experiencing this bug as well.  

## Steps to reproduce:
- Go to a conversation, click on the text box to open the keyboard. 
- Long press on a message, but release before the popup opens - this only happens if you release early. The cursor will no longer be in the text box, but the keyboard is still visible. 
- Now that the cursor is not in the text box, long press on another message or open an image. The keyboard will remain visible, obscuring part of the screen. 

iOS version: 17.2.1
Signal version: 6.60.0.10

Debug logs: https://debuglogs.org/ios/6.60.0/4209e7c985eb7fd4b8f5d2fe6611bd8a5d2e6e3b2af0007ef7f76ce4e2676c3f.zip

**Comment by danispringer** [comment]
Signal doesn't deserve me - or anyone.
