### ISSUE TITLE
Messages only being delivered to 1 of 2 linked devices

### ISSUE THREAD

**Issue by stijlist** [signalapp/Signal-iOS#5763]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've noticed four separate times (two inbound, two outbound) in the last two days where a message is only sent to one of my two linked devices. The problem happens in both desktop and iOS - the message was received on Signal Desktop but not on iOS and vice versa. I've been using Signal as my main messenger for 6 years and this is the first time I've noticed the issue. I had to re-link my Signal Desktop client recently and I don't remember why - maybe related to an OS version update.

### Steps to reproduce
- Send or receive a message with two linked devices (in my case, one running Signal iOS and one running Signal Desktop on macOS).

**Actual result:** The message might show up on one but not the other.

**Expected result:** All messages are delivered to all devices.

### Screenshots
Desktop:
<img width="1033" alt="Screenshot 2024-02-19 at 2 40 18 PM" src="https://github.com/signalapp/Signal-iOS/assets/1486165/d47a03f8-807e-45d1-8ef8-540b0d85b7f4">
iOS:
![IMG_8134](https://github.com/signalapp/Signal-iOS/assets/1486165/ae124ee8-3e89-44a3-aa62-e37f0eacf9be)

### Device info

**Device**: iPhone 13 mini

**iOS version**: 16.1.1

**Signal iOS version:** 6.59.0.23

**Device**: Macbook Pro 13" M1 (2020)

**macOS version**: Ventura 13.6.4

**Signal Desktop version:** 6.47.1 production (Apple silicon)

### Link to debug log

iOS: https://debuglogs.org/ios/6.59.0/eb8b5f5e3bd86822b924b305858d90f16578863499a527407a6c8401ecc0faa9.zip

desktop: https://debuglogs.org/desktop/6.47.1/ddb95d1fbbb1e8f6395ea9eb9a71a92818a533535dcbc5a258a2375bad159b21.gz

**Comment by Miguel-Signal** [comment]
Hi @stijlist 

Could you please clarify your setup? Phones are not supported as linked devices, only iPads and Desktops are. You should have registered Signal on one iPhone, with linked devices being only a desktop or an iPad. Not a second iPhone.

Can you please update the iPhone you intend to use as your primary device to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) Then, if the issue is still happening, could you send in new logs from this new version?

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link.

**Comment by stijlist** [comment]
My setup is one desktop and one iPhone, so two "linked devices."
I will update and resubmit if the issue is still happening.

**Comment by lobrau** [comment]
I'm also experiencing this bug. Laptop is getting some group notifications and I'm able to respond. Phone doesn't get anything at all for those groups but does for a few others and 1 to 1 messages are all fine.
