### ISSUE TITLE
App Crashes / Won't Start

### ISSUE THREAD

**Issue by duke7901** [signalapp/Signal-iOS#5796]
Hello,

after transferring Signal data from iPhone 15 Pro (iOS 17.4.1 and Signal 7.8) to iPhone 12 Mini (iOS 17.4.1 and Signal 7.8) -
due to switching phones, Signal won't open up anymore on iPhone 12 Mini.
No errors occured, transfer took about 1min (just few data).

Same behaviour like:
https://github.com/signalapp/Signal-iOS/issues/5333
https://github.com/signalapp/Signal-iOS/issues/5795

Because Signal does not offer a good and practical way to backup chats, that is very annoing for me -
I MUST NOT lose some of my chats!
Having a simple PDF or plaintext export could have saved me!

Also tried restarting phone, app, etc.

Help appreciated.
Thank you.

Regards.

**Comment by JMaxPayet** [comment]
Same problem after transferring from iPhone 11 Pro to 15 Pro Max (same iOS 17.4.1) : if I tap on Signal it open and quit immediately.
The transfer happened without any problem.
If anyone has a solution 🙏🏻

**Comment by felixfiskare** [comment]
Same here.
Transferred from Iphone 12 Pro to Iphone 15 Pro. Transferring worked like a charm. Shortly after transferring Signal won't open anymore. If I Tap the Icon I see the Signal Icon fullscreen for a very short time (<1 Second) and then I'm on the app drawer screen where I have been before.
No notification and nothing is being shown.

**Comment by duke7901** [comment]
Same s*** on 7.10
Still crashing. No response, neither here nor support@ … 2,5 weeks w/o Signal app on my business phone … 2,5 weeks no access to sensitive data for doing my business!
No fix, but Emojis when calling. 
Great Job 👏🏼

**Comment by maats** [comment]
Having same issue after migration from iPhone 12 Pro to 15 Pro. App no longer opens on 15 Pro.

**Comment by JMaxPayet** [comment]
Hello,

Here are all the 29 logs I have on my iPhone about Signal (supposedly crash logs).

Context : 
I followed step by step the process to transfer my account from my (almost dead) iPhone 11 pro to my (new) iPhone 15 pro max.
The transfert was OK, until the end. Until the message on the iPhone 11 pro to delete the app data... since everything was transferred.
The PROBLEM : as soon as I tried to open Signal on the iPhone 15 pro max : it crashed immediately.
Since then, I've never been able to open Signal : it seems to launch but crash immediately.

Help !

After some research I found this GitHub post of someone with the same problem... and here I am today, begging for help in order to retrieve my data.

NB : I still have access to Signal on my iPad (linked account... but it's just a sort of mirror, not the main account)

Hope you will be able to find a solution.

Best regards

--
Jean-Max Payet
***@***.***




￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼

**Comment by SirPanOfTheCake** [comment]
Having the same issue after transferring signal from two IOS devices.  I have already sent crash logs to signal. 

@cloudgreen Has the Signal team given you any update?

**Comment by JMaxPayet** [comment]
It seems that the support is working on the problem.
Hope it will be solved soon 🙏🏻


Their message:
____________
Hi, thanks for writing in to Signal support.
 
We are aware of the problem and we are currently looking for a solution. Although our engineers are working on a fix, unfortunately I can't give a specific schedule for resolution. You might see a fix in the release notes for future versions of Signal.
 
Thanks again for your help in reporting this.
------------

**Comment by williamshowalter** [comment]
I received, verbatim, the same reply a week ago. Gave up and uninstalled, loosing all my conversations, as the outlook from these 3-4 week old tickets wasn't promising.

**Comment by JMaxPayet** [comment]
Updated the app today... It works !
🥳👍🏻
Hope it will work for all of you too.

**Comment by maats** [comment]
Works for me too, many thanks!

**Comment by Miguel-Signal** [comment]
Could those experiencing this issue please update to Signal version 7.11 and write into support@signal.org if the issue still persists?

**Comment by 99syl** [comment]
Fixed for me too, thank you !

**Comment by duke7901** [comment]
Thank you!
App starts as expected.
So, a backup like on Android would be nice now!
