### ISSUE TITLE
Signal doesn't show up as an option to share web pages

### ISSUE THREAD

**Issue by BBKrWw** [signalapp/Signal-iOS#650]
I'm not an iOS developer, but I believe using app extensions would allow Signal to show up as an option to share websites when viewed in Safari (and other browsers?).

![image](https://cloud.githubusercontent.com/assets/217057/21506623/d5bfd35c-cc71-11e6-8308-bbbb4b86775e.png)

**Comment by thenktor** [comment]
This also should be possible for photos and contacts ;)

**Comment by FredericJacobs** [comment]
This requires some extra UI (a contact picker). Planning for 2.0.3 if time allows or 2.1

**Comment by thenktor** [comment]
I think this feature is most important for sharing viewed photos.

**Comment by marvinthepa** [comment]
This is an important usability feature (for me), copy and pasting links on mobile phones is really cumbersome.

**Comment by platypus5021** [comment]
Has there been any traction on this issue? It makes it difficult to share media and other items to Signal in its current state when it doesn't show up as a shareable application.

**Comment by derlinzer** [comment]
That's why neither Signal nor Threema will get broad acceptance and it's a pity. When each and every other messaging app supports extensions by now, it's hard to really recommend a switch. Most people won't trade comfort and by now well known features against enhanced privacy and the loss of these features.

**Comment by platypus5021** [comment]
@derlinzer Does your post imply that this feature will NEVER be added to the IOS version of Signal? Any clarification @FredericJacobs?

I am appreciative of the fact that some comfort has to be sacrificed for privacy's sake (i.e. having to use a non-iMessage app for chat), but you are right in the sense that the lack of very basic features (IMHO) are a major deterrent to people switching over en masse.

My wife has raised the following three features which is why she has twice now tried to use Signal, and twice deleted it:

1. This issue (650). The lack of ability to share hyperlinks, images, and any other forms of media directly into Signal via the iPhone's shared applications list. A function that is present on the Android fork.

2. Issue #793 -  The lack of ability to copy and paste images directly into Signal. This issue would be lessened with a fix for #650, but both would be ideal. 

3. The option to quick reply in Signal if using another app at the time. e.g. If one is browsing the web and a Signal message arrives, it should be possible to swipe down to reply without taking the other app out of the foreground. (Not sure if this ticket has been submitted yet)

**Comment by derlinzer** [comment]
@platypus5021 i imply nothing ;-)

ad 1) possible since iOS 8 - which was released September 17, 2014
ad 2) never tried and never won't since i *expect* 1) to work
ad 3) possible since iOS 9 - which was released September 16, 2015

I am patient about 3) since it's a small developer team. But i have simply no understanding that 2) is still not implemented. In my opinion it's the same as with GPG: Yes, it is secure, but it's a pain in the ass to use and not available on mobile devices.

**Comment by platypus5021** [comment]
Glad to see a poster for new developers. Hopefully someone can help @FredericJacobs with the backlog. Hoping to see this issue get fixed soon.

**Comment by aayushranaut** [comment]
I can work on adding this feature.

**Comment by FredericJacobs** [comment]
@aayushranaut Let me know if you have any questions!

**Comment by platypus5021** [comment]
Hooray! Thanks @aayushranaut.

**Comment by aayushranaut** [comment]
I'm having trouble with installing OpenSSL via CocoaPod.
https://openssl.org/source/openssl-1.0.2d.tar.gz seems to return 404. The version used in Podfile is 1.0.204.1 which does not exist on OpenSSL site anymore. Can I change the OpenSSL version to the latest version(1.0.205)?

**Comment by FredericJacobs** [comment]
@aayushranaut : Of course, I fixed it on a branch locally, it's not a problem.

**Comment by jooize** [comment]
Please prioritise a Share extension. As other people have said, it's by now a standard usability feature.

I can't imagine any significant negative consequence from implementing this, and can only assume there has been a lack of time, money, or developer interest in it. There's no extra UI elements required inside the app. Security isn't impacted, unless iOS unexpectedly leaks contact information through Share extensions. Extra code and maintenance for something this essential is warranted. Additional app size should be negligible.

The Share extension can (and should) allow sharing text (incl. links), pictures, and videos directly to a Signal recipient. Arbitrary file support would be cool, but not expected at this point.

**Comment by mufler** [comment]
Any news/updates on share extension implementation?

**Comment by alexw1982** [comment]
any progress on this issue - it is a really big issue for my peers in switching to signal...

**Comment by TCB13** [comment]
+1 on this, it's a simple request.

**Comment by kroney** [comment]
+1

**Comment by anselmh** [comment]
Regarding the implementation i think you could get some inspiration from Slack. They do the “choose team, channel or person” workflow very well in their share extension.

**Comment by charlesmchen** [comment]
Thank you @anselmh , we'll check it out.

**Comment by derlinzer** [comment]
@charlesmchen that Signal doesn’t support a basic feature that every other messaging app supports in 2017 is inexcusable and laughable.

Take any inspiration from other apps that you need, but get those basics right. Or at least be transparent what the problem is and what priority this basic feature has.

**Comment by big-r81** [comment]
@derlinzer 
If it is so inexcusable and laughable where is your code commit to fix this?

**Comment by TCB13** [comment]
@charlesmchen @big-r81 ok guys lets chill down. @derlinzer this can be annoying, it's true, however to make this "laughable" "basic feature" it is necessary to rewrite some core components of the App.

If you have complains about how the share sheet integration works you may direct them at Apple because at the end of the day they are the ones forcing developers to create a separate App - and having to deal with all kinds of data issues - just to have a share button.

**Comment by michaelkirk** [comment]
Thanks guys, I think we have all the information we need. As TCB13 alluded, it's a surprisingly non-trivial to implement feature.

But we agree it's a critical and basic feature expectation of our users. It is on our roadmap and we're working towards it.

**Comment by michaelkirk** [comment]
Share extension is out as of 2.20. Share and be merry.
