### ISSUE TITLE
User uninstalling App breaks Group

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [signalapp/Signal-iOS#700]
Hi there,
one Member of our Groupchat uninstalled the Signal App without leaving the Group first. He is still listed.
Now for every message the leftover members send to the Group, we get the notification that the message could not be delivered.

So I guess this should be recognized and handled by the app in some way.

**Comment by TheStash** [comment]
I wanted to refer to a somehow related issue but it happened just once, in which when a member left the group, there was no way to re-add him to the group, whenever you add him he is removed again (without taking action from his side).

**Comment by likyng** [comment]
@TheStash for me simply adding the contact to the group again fixed the issue. In case the contact has a new fingerprint, you first have to accept the new fingerprint in a 1to1 chat or similar.

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by huettenhain** [comment]
I am experiencing the same issue where a Group contains a number that is no longer registered:
![image](https://user-images.githubusercontent.com/11869704/48615350-f92f7700-e990-11e8-8589-f69669782339.png)
I am aware that this is pretty close to #1621 and #2979, but would it be reasonable to have a mechanism that automatically removes _unregistered_ numbers from Signal groups?

**Comment by michaelkirk-signal** [comment]
@huettenhain - can you explain a little more explicitly what you are experiencing- What steps are you taking, what do you see, what do you expect to see?

That screenshot looks like a Signal-Desktop screenshot. Is this problem occurring on your iOS device or your desktop installation? If it’s desktop please instead file any details in an issue at github.com/signalapp/Signal-Desktop

**Comment by huettenhain** [comment]
Dear @michaelkirk-signal,

I have not investigated the issue very deeply, but here is what I know: In a Signal group that I am part of, one of the group "members" is a certain number which formerly belonged to a participant of the group. This number has since been abandoned and the former owner of the number is not able to remove it from the group because she is no longer in possession of it. I was definitely _expecting_ there to be some way to remove this number from the group: The only other solution would be to create a new group, which would be very undesirable because we do not want the chat history to be lost. However, it seems that the developers currently have no intention to implement such a feature, or at least that was my takeaway from #1621 and #2979. Also, when sending messages to the group from my Android device, usually no error message is displayed, it is just a general concern to have this unknown number remain a member of the group.

The above screen shot is indeed from a Signal desktop instance and I posted it mainly because it seemed to imply that the Signal server was aware, to a certain degree, that the number no longer constituted a valid Signal account. This made me wonder whether it might be in the realm of possibility to purge such accounts from groups, which seems like a weaker request than any of the two issues mentioned above.

**Comment by michaelkirk-signal** [comment]
@huettenhain - just to clarif, you're posting in the Signal-iOS issue repository. 

If you'd like the ability to remove members from a group, no client currently supports that. This is a feature request and would be better suited for our community forum over at: https://community.signalusers.org. We reserve GitHub for bug reports with existing functionality.

On the other hand, if you are unable to send messages to a group which has a no-longer-registered member (and at least one still registered member), that **is** a bug. But based on your comment, you aren't using Signal-iOS. It sounds like that could be either https://github.com/signalapp/Signal-Android or https://github.com/signalapp/Signal-Desktop. Could you search for your issue over there? Or post a new one if it doesn't exist?

**Comment by michaelkirk-signal** [comment]
Closing as this issue as Signal-iOS will skip over group members who have unregistered.
