### ISSUE TITLE
Indicate whether I have previously verified a contact's fingerprint

### ISSUE THREAD

**Issue by runasand** [signalapp/Signal-iOS#739]
I cannot seem to find any indication that I have verified a contact's fingerprint. If I long-press on the name, I get the option to either scan his fingerprint or display mine. It would be great if this page also listed whether I have previously verified his fingerprint.

**Comment by maxbrandes** [comment]
#298 "We're not going to do that, TextSecure doesn't either."

**Comment by runasand** [comment]
Both @corbett and @moxie0 have said they will not be exposing this in the UI. Why?

**Comment by hubert3** [comment]
@runasand I'm not sure why they don't want to do it, but I can come up with a possible reason - If I were able to access the Signal database on your device, I could easily tamper the 'verified' flag for one of your contacts, causing you to not actually verify the fingerprint so I could then get away with MITM'ing.

Not having a permanent indicator encourages you to verify more frequently, which arguably enhances security. It would also introduce additional complexity as you then have to handle legitimate key changes somehow (due to Signal re-installation, etc).

It's easier and more reliable to force you to verify again.

**Comment by 2-4601** [comment]
Quoting TextSecure's [Development Ideology](https://github.com/WhisperSystems/TextSecure/blob/master/contributing.md#development-ideology):
> 1. **The answer is not more options.** If you feel compelled to add a preference that's exposed to the user, it's very possible you've made a wrong turn somewhere.
> 2. **The user doesn't know what a key is.**  We need to minimize the points at which a user is exposed to this sort of terminology as extremely as possible.
> 3. **There are no power users.** The idea that some users "understand" concepts better than others has proven to be, for the most part, false. If anything, "power users" are more dangerous than the rest, and we should avoid exposing dangerous functionality to them.

Thus it would be against the guidelines to show the fingerprint verification status directly in the contact list.

However in the screens where you compare/scan fingerprints (or perhaps in the long-press contact view as suggested by @runasand) it would make sense to add the status because in those views the user is already exposed to a load of crypto-babble and a discreet verification status would not make it worse. In fact it would be just saying: "You have already done this."

**Comment by rusvnc** [comment]
@2-4601

I fully agree. This is a case where I find Moxie's dogmas utterly incomprehensible and illogical, and his resistance to all argument baffling. A confirmation mark in the UI only needs to be exposed for users who have gone through the confirmation process. Other users need not see it. Since, as you say, they are already looking at key material in the UI, it is hardly more unfriendly - arguably less unfriendly - to store this confirmation and serve it graphically.

As to the argument that someone with access to the DB could tamper with this confirmation record, surely this applies equally to the TOFU model currently relied on by the app - it saves a key associated with a contact and flags any changes.

**Comment by michaelkirk-signal** [comment]
Signal has since added the ability to mark a contact as verified.
