### ISSUE TITLE
Enhanced UX when phone offline

### ISSUE THREAD

**Issue by FredericJacobs** [signalapp/Signal-iOS#772]
- [ ] Lock the send button: a lot of applications do this to avoid having the user to send.
- [ ] We made a decision previously to have a loading bar: this is confusing and non-intuitive for the users because there is no way. I suggest going back to a network status indication bar similar to the one present in the Facebook messenger app where a dropdown appears while connecting and when the device is offline. This is way clearer to the user about what he should expect from the app given the network status.
- [ ] When the device is getting back online, automatically retry sending messages who were queued up in the sending queue without requiring user interaction.

**Comment by abcdev** [comment]
I don't know how the facebook messenger app dropdown looks like but what about changing the already implemented connection indicator to the behavior:

Not connected
![image missing](http://i.imgur.com/GrJXnX9.png "Not connected")

Connecting
![image missing](http://i.imgur.com/B8Gt4uV.jpg "Connecting")

Connected
![image missing](http://i.imgur.com/BRp87gK.png "Connected")

I don't know what colors and size to use but it should be more visible then the current indicator

**Comment by FredericJacobs** [comment]
That's what we used to do. But @abolishme proposed a loading bar. I think a Facebook-like connection bar is the best trade-off we can make between representing what actually happens and what the user expects to happen.

**Comment by bvorak** [comment]
I thought there is no on- or offline status for asynchronous messaging?

**Comment by FredericJacobs** [comment]
@bvorak: Your phone can be online or offline. It indicates if it's able to reach the TextSecure server or not. But you're always "online" in the sense that you can receive messages at all times.

**Comment by thenktor** [comment]
BTW: Threema uses the same method that @abcdev has suggested.

**Comment by FredericJacobs** [comment]
That's what we used to do but @abolishme got it changed. Can you chime in and open/close necessary issues?

**Comment by likyng** [comment]
I think that disabling the send button is not very user friendly. As on Android, it makes more sense in my opinion to leave the send button active and indicate on sent messages that they are not delivered yet (keep light blue colouring). Then queue those messages for sending and send them when connected to the network again. This way, people can write and send longer messages while offline (very, very useful feature for e.g. train rides with spotty connectivity).

**Comment by MacLemon** [comment]
Threema has a similar bar at the top that indicates connection status.

One problem with this is, that the user's focus is not there, but at the text input field. So this is *very* likely going unnoticed.
A greyed out Send button conveys the message that sending is not available, but leaves the user with the experience of “sending doesn't work half of the time, I'm using something else” because I need to send a message *now*.
While they switch to another messaging app the connection briefly returns and they're able to send their message from another app, and they're gone, perhaps using the messenger *that works* forever.

It's absolutely key to tell the user *why* sending is not available at that exact spot. So maybe change that button from “Send” to “Offline”. This also brings the problem of how to tell people that they need a data connection, because “I do have cellular reception, and I can always send SMS. So why doesn't this work? I'll just use SMS instead.”

This won't apply to some of the tech-savvy people, here or elsewhere, maybe not you, maybe not me. It does apply to the majority of users out there though and we should improve upon the lessons learned from other messengers since we're given the opportunity.

**Comment by michaelkirk-signal** [comment]
> In other messaging apps (like WhatsApp), you can write the message and press Send even if the phone is offline. The message is stored locally and the app sends the message when the phone is back online.

Hi @paoesco - we have a feature in the current beta release which does just this. If you'd like to try it out, and are willing to brave some occasional sadness that comes with using a beta release (possible crashes, data loss), sign up here: https://testflight.apple.com/join/8FHtd1Jq

Then hop on the tubes, fire away, and let us know how it goes.

**Comment by paoesco** [comment]
hop on 👍
