### ISSUE TITLE
Support for multiple devices for the same account

### ISSUE THREAD

**Issue by root42** [signalapp/Signal-iOS#823]
Similar to iMessage et al. I wish I could use Signal on multiple devices, using the same phone number. I would e.g. like to use Signal on my private iPhone and iPad, but as well on my business iPhone. I am already doing the same with iMessage. The private iPhone is used for authenticating the other devices via SMS text message. I would assume that something similar should be possible with Signal. 

I am not familiar with the cryptography used for Signal and Textsecure, but I would assume that one could encrypt using multiple keys, one for each device. But I have actually no idea, how Textsecure works in real life. ;)

**Comment by Toejam-Sunshine** [comment]
Agreed - Would be simpler to have ability to use same account in iPhone and iPad, like iMessenger.  However, if internals / design doesn't support this, make public aware that it's one tel. number with one device.  Thanks!

**Comment by riyapenn** [comment]
Similar to https://github.com/WhisperSystems/Signal-iOS/issues/211

**Comment by mahyar** [comment]
Now we have desktop support, would this be easier to implement?

**Comment by hirako-shinji** [comment]
would love multi device support. same number with different phones. i switch between two phones.

**Comment by tigrino** [comment]
The absence of multiple devices support is really a showstopper for me. I have two phones and a tablet and I want to be able to receive messages on either after registering with the same telephone number on all of them.

**Comment by rekster** [comment]
I have a WiFi only iPad tablet, would like to be able to use Signal on this as well as my phone and my Desktop system.  If Desktop is supported, why not a WiFi enabled tablet?

**Comment by ivanalonzo** [comment]
Can't we use the same method for using the key on the desktop client for allowing multiple mobile devices?

**Comment by spacekookie** [comment]
As far as I understood the situation a few months ago this was a limitation of their server backend, not the crypto or even necessarily the clients.

**Comment by Trolldemorted** [comment]
The server backend does not care what kind of user agent you register as a slave, but most likely SignalProtocolKit does not yet have support for slaves.

**Comment by AykutCevik** [comment]
Can't we use the same method like in the desktop client to link different devices to one account?

**Comment by Trolldemorted** [comment]
Of course, but someone has to implement it. I can help by explaining what has to be done during linking, if a contributor wants to work on this.

**Comment by lordmortis** [comment]
I’m interested in working on this. Do we have an iPad UI?

**Comment by Limero** [comment]
This really needs to happen. Being able to link an iPad to a phone the same way as the desktop client does, would be fantastic.

**Comment by NiklasBr** [comment]
If you allow multiple devices, can we *please* allow users to move data from one device to the next, e.g. via encrypted iTunes backups?

**Comment by Trolldemorted** [comment]
@lordmortis to keep your PR as small (and simple) as possible, you might want to start with running as a slave on iphones

**Comment by lordmortis** [comment]
Yeah, that’s the plan.

**Comment by Trolldemorted** [comment]
@lordmortis if you have any questions how the linking process works or how slave authenticate, just ask. We probably should move the discussion about implementation details to the [community forum](https://whispersystems.discoursehosting.net/), though.

**Comment by blueicehaller** [comment]
Here is one existing thread: [Multiple device support for iOS?](https://whispersystems.discoursehosting.net/t/multiple-device-support-for-ios/595)

**Comment by kenmanheimer** [comment]
I hope and would expect that multiple-device support will not be restricted to iPhones. Google Fi enables running multiple devices with the same phone number, for instance. I was sad to discover that enabling Signal on a second phone (silently) disabled it on the prior.

**Comment by evanrmurphy** [comment]
My friend who I message with often on Signal is now switching to a different messenger because he can't use the same Signal account on his iPad. It would be so great to have this feature! @lordmortis is this still something you're thinking of taking on?

**Comment by aalmangour** [comment]
So is this going to be implemented?

**Comment by odabrunz** [comment]
Another reason why I want this is that I use multiple users on my Android phone, and I don't want to be cut off from important messages just because I have switched to a different user on the same phone for a while.

I believe this happens fairly often to others as well, because some popular games associate in-game users with Android / Google users on the device, so you need to switch the device user to access a different in-game user.

So please make it possible to use the same Signal account from multiple Android users / Google IDs on the same device.

**Comment by rrobino** [comment]
Having multiple devices linked to one account is so intuitive, if not flat out implied by the presence of a Linked Devices item that I reckoned I just didn't understand yet, that I blithely went about creating an account on other devices.

Now my original account and all conversations associated with it, are (apparently) irretrievably lost, and there is no remedy that I have been able to find yet.  There should be a huge warning when provisioning app for the first time that if the user already has Signal installed on another device that, by configuring and activating the app on a new device that they will *LOSE EVERYTHING* on the other device, which was probably their main one.

If anyone reading this can point me in the right direction to at least salvage my "original" device/account, it would be much appreciated.  Meanwhile, implementing this feature may solve that problem too - and it's a feature that I personally feel has to be part of this product in order for it to be useful.

Had I known that this feature was not implemented when I installed the app and invited all of my friends to use it... I would never have considered Signal, despite the great work done in every other area.  It's just not realistic in this era to expect a person to stick to a single device - and not implementing this creates an insecure situation that is tough to resolve if the device is lost or stolen.

Please, please enhance the product with this feature, so that I do not have to find an alternative.  Thank you.  By the way, I personally would be willing to pay a small amount for extra devices beyond the initial/primary device.  So if someone wanted to fork the code at this point and make this project sustainable by means of steady revenue - well, I think that would be a win-win for potentially millions of people.

**Comment by trymeouteh** [comment]
This would be super handy. It would just be like the desktop versions of Signal but on your Andriod Tablet or iPad. This way if your phone is low on battery and is charging you can continue to message others and have voice or video calls with others.

This feature would make me stop using Wire for good.

**Comment by NathanJang** [comment]
Multiple devices would be great. While testing code on another device for an unrelated pull request I just made, I had to reinstall Signal on my main device, and lost all my messages. It's a little unfortunate that I got punished for trying to contribute 😕.

@rrobino's suggestion for a warning when registering on a new device is an great workaround. Is there a way for the app to warn if the account already exists during registration?

**Comment by simonelthis** [comment]
I don't see why this cannot be done. They made the desktop clients all that needs to be done is make the same thing for Andriod and iOS were the device will link itself to your phone. Signal will be like PulseSMS were you can message people on any device if it had this. This feature would put Signal a good lea ahead of WhatsApp.

And more and more apps on iOS and Andriod are having syncing options so you can switch between your tablet and smartphone.

**Comment by LafinJack** [comment]
Want. :D

**Comment by thenktor** [comment]
I'd like to use Signal on iPad as secondary Client, too. Just like I can do with iMessage or Wire.

**Comment by ivanalonzo** [comment]
I have a work-around that has been working pretty well for sometime with these limitations:
- This requires the use of groups
- It will not work for your main account's phone number

If this is ok with you, then here is my working solution (with the limitations above):
Since Signal supports groups, I have created a second signal account on my iPad. To do this, I used a gVoice number (if you are already using a gVoice number, you can use one from callcentric) on my iPad and created a group for my wife which includes her, my android signal account (main) and my iPad signal account (secondary). Through this group, I can keep my signal messages synced across all devices (the desktop app already supports syncing). I hope this works for you. 

I am not involved with Callcentric, but I have used it for a few years and it works pretty well. For this purpose, you only need the free service.

**Comment by gethob1** [comment]
Re: ivanalonzo
Callcentric terms and conditions state:

"Numbers assigned by CALLCENTRIC as Free Phone Numbers cannot be used for verification purposes with third-party services, including but not limited to WhatsApp, Craiglist, Viber, etc... As such, inbound calls from third-party services verification numbers will not complete to numbers assigned by Callcentric as Free Phone Numbers. Any limitations, restrictions, or terms pertaining to the Free Phone Number product are subject to change at any time."

Are you able to get it to work?

Unrelated to OP's issue, but curious/interesting: I wonder how Signal prevents someone from using someone else's phone number...  Let's say you start out using one phone number for Signal desktop PC, and stop paying that account, whether contract, pre-paid, or whatever, and then that number gets recycled to someone else.  What would stop someone from continuing to use that number for Signal even if no longer the owner of the account, and what would happen when the real owner tries to create a Signal account?  Would the registration be allowed and overwrite the existing so that incoming texts would be intercepted?  My understanding is Signal just works if the number exists and is active, and wouldn't be able to determine whether the user is the owner of the current active device.  I could be wrong.  Also wonder if Signal numbers can be spoofed by modifying the software/installation/whatever.  Seems like it could be a problem?

**Comment by ivanalonzo** [comment]
@gethob1 yes, I can get it to work with callcentric numbers (that's what my iPad uses).

**Comment by gethob1** [comment]
I guess they're not able to enforce their terms and conditions.

**Comment by ivanalonzo** [comment]
@gethob1 give it a try and let me know if it works.

**Comment by hperrin** [comment]
Let me know if this is inappropriate to post here, but for anyone interested in an e2ee messenger and protocol designed for multiple client use, check out https://github.com/hperrin/tunnelgram

It uses the Tunnelwire encryption scheme, so multiples clients are inherently supported, and don't require any extra setup or the original sign up device.

I don't know if Signal could use a similar approach to support multiple devices (I assume it could), but if anyone has any questions about how Tunnelgram/Tunnelwire supports it, I'd be happy to answer.

**Comment by gethob1** [comment]
I also don't intend to get off topic but these latest posts are potentially relevant.  This post doesn't solve the OP's problem and gets theoretical but pensive.  The OP's question raises bigger questions for me, see below.

Ideally, there would be an app that uses Signal protocol with no need for phone numbers.  We're not communicating via cell data anyway so why limit Signal to phone numbers? It makes no sense.  Just have unique IDs, multi-device support, and eliminate needing a carrier/SIM card just to have Signal.

And I haven't read the FAQs lately but think about this.  What if someone registers your number or somehow spoofs your SIM.  Does that mean they will take over your account and get all your messages and send on your behalf?  I don't know how Signal manage keys, devices in that regard but IMO Signal should be blind to devices for user security/privacy sake and only identify the user based on some unique ID # that only the user has and no one could spoof.  Again, I know I'm just thinking in total theory land here, know nothing of actual software workings.  If someone knows you use Signal and knows your number, it seems they could potentially pass a fake number to the emulator.  That is, I wonder how Signal knows the difference between me buying a new phone and installing the same SIM card in it vs. someone faking my SIM on an emulated device/ hacked app.

Re: hperrin
The tunnelgram doesn't say which mode of AES it uses (128-bit or 256-bit, half rounds/ full rounds?)  Makes a huge difference in whether it's safe or not.  Signal protocol I trust and I find it's kind of hard to get friends to switch from whatever they're using.

**Comment by hperrin** [comment]
@gethob1 Thanks for the tip. I added that info to the readme. (AES-256 in Output Feedback mode with a 128-bit initialization vector.)

**Comment by thenktor** [comment]
@gethob1 
> Ideally, there would be an app that uses Signal protocol with no need for phone numbers. We're not communicating via cell data anyway so why limit Signal to phone numbers? It makes no sense. Just have unique IDs, multi-device support, and eliminate needing a carrier just to have Signal.

Just use Wire (https://wire.com/) and you're done ;-)
But in my opionion the best thing about Signal is the use of phone numbers only. That makes it just as easy to use as WhatsApp. Everything else is just to complex for the majority of users. Most of them also will never use multi device support.

**Comment by michaelkirk-signal** [comment]
> Let me know if this is inappropriate to post here

Hey @hperrin et al, we only use GitHub for tracking bugs with intended behavior. For everything else, like feature requests and open discussion, please join our community forum: https://community.signalusers.org/

**Comment by spencerthayer** [comment]
They say it's on their "[roadmap](https://community.signalusers.org/t/multiple-device-support-for-ios/595/7)" but that was almost a year ago. Not sure it's much of a priority for Signal.

**Comment by cwgreene** [comment]
> Of course, but someone has to implement it. I can help by explaining what has to be done during linking, if a contributor wants to work on this.

@Trolldemorted is there a document that describes that linking process?

**Comment by peatrick** [comment]
**Bump.**

This has been a bit of a frustrating mess, I accidentally re-enabled Signal on my old phone, not knowing it was going to wipe all my "verified" contacts in the process, after upgrading to a new device.  Guess I'll have to assign Signal too another number on my old phone and pester folks from multiple directions... would love a software solution to this current dilemma.  Kthx, yer nice.

**Comment by Trolldemorted** [comment]
@cwgreene depends on what you consider a document. If source code is a document to you, there is
- [Signal-Windows' implementation](https://github.com/signal-csharp/Signal-Windows/blob/master/Signal-Windows/ViewModels/LinkPageViewModel.cs#L66)
- [signal-cli's implementation](https://github.com/AsamK/signal-cli/blob/e809792467f50ed482fa4a2fd6e5e1577d306e6f/src/main/java/org/asamk/signal/manager/Manager.java#L222)
- a [Signal-Android implementation](https://github.com/Trolldemorted/Signal-Android/blob/multidevice/src/org/thoughtcrime/securesms/service/LinkingService.java#L75)

Signal-Desktop obviously implements it too, but I don't know where.

**Comment by michaelkirk-signal** [comment]
We now use the community forums for discussing feature requests, and reserve GitHub for reporting bugs with currently implemented functionality. 


Please join the conversation there instead - here's a relevant thread: https://community.signalusers.org/t/allow-android-ios-devices-e-g-tablets-to-be-linked-to-the-primary-device-i-e-used-as-secondary-device-like-the-desktop-app/2884
