### ISSUE TITLE
Landscape mode / Horizontal layout support 

### ISSUE THREAD

**Issue by calis2002** [signalapp/Signal-iOS#937]
Hi,

i'm new to Signal and don't know if this is working as designed or if it's a bug but the screen rotation doesn't work on iPhone 6 with iOS 9.2 and Signal 2.1.3.

If this is working as designed then take this as an feature request ;)

Regards
calis

**Comment by marvinthepa** [comment]
+1

**Comment by mariussoutier** [comment]
:+1:

**Comment by abcdev** [comment]
:+1:
github lacks feature request upvotes so hard....

**Comment by 2-4601** [comment]
This used to be tracked here #302. Not sure why it was closed though.

**Comment by Fidge123** [comment]
:+1:

**Comment by jnachtigall** [comment]
:+1: mayor ux blocker

**Comment by lfxc** [comment]
+1
major ux issue, biggest complaint we get from our user group

**Comment by Floody2003** [comment]
+1

**Comment by 2-4601** [comment]
For those about to bump:
https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues
https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by gluxon** [comment]
I took a look at the Storyboard in Xcode and noticed that this feature appears to be 95% of the way there. Besides a gray bar underneath the navigation bar, is there anything keeping this feature from going to release?

I would like to try updating the Storyboard UI for landscape mode when I have time in a few weeks otherwise.

**Comment by richlv** [comment]
@2-4601, looks like it was closed a being tracked in #539. not sure how that is more helpful, but whatever works for the dev team :)

**Comment by snyfer** [comment]
+1

**Comment by mcmenace** [comment]
Any progress here? Feature request is >10 month old and an 8 month old comment states that the feature was 95% complete.

**Comment by wallenium** [comment]
Would be a usefull enhancement

**Comment by TreatyOfRome** [comment]
Related #1071

**Comment by MarianneF** [comment]
I'm a bit confused, why this is not showing any progress.
1. There is this here #937, as well as #302 and #696. So people seem to care about it.
2. The android version of signal does have landscape mode, shouldn't both versions be comparable?
3. On 23 June 2016 gluxon wrote here, that this feature would be 95% completed.
4. Beside all this (that it might be nearly finished for over a year now), the rotation of chats in a messenger is not too complicated, and there is even open source code available, which could more or less just be copied.

The argument, that Signal needs more people to contribute code should also not apply, because during the last year enormous improvements have been made - more than in other projects (like video calls). So there is quite a huge amount of "coding power".

**I do not want to criticize**, moan or grumble. I would just like to understand the problem? Is there someone in the team who just don't wants landscape for some reason? Does it help to donate money to the project? It this is nearly finished, I really doubt it helps much, if another person shows up.

Here a lil link I found from an old article. It shows a nice photo of @moxie0 with a smartphone, which he is holding in landscape - that is what i wanna do, too!

https://www.cnet.com/news/whispercore-app-encrypts-all-data-on-android/

**Comment by CarpetSnack** [comment]
Sorry, but this is bullshit.  Even on iPhone there is a need for landscape.. Why isn’t the default for any IOS app to support Landscape mode?  An iPad with a kbd will be in landscape mode.  Isn’t that obvious?

**Comment by charlesmchen-signal** [comment]
The latest beta release of Signal iOS includes full landscape support. If you would like to join the beta and provide feedback, you can find more information [here](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-2-35-release/5883).
